<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<properties>
		<game.assembly.descriptor>package.xml</game.assembly.descriptor>
		<!-- 打全量包时，使用哪个服务器的配置文件 -->
		<game.server>test</game.server>
	</properties>

	<parent>
		<groupId>cn.game</groupId>
		<artifactId>server</artifactId>
		<version>1.0</version>
		<relativePath>../server/pom.xml</relativePath>  <!--本例中此处是可选的 -->
	</parent>

	<artifactId>game</artifactId>
	<packaging>jar</packaging>

	<dependencies>
	<!-- 内部模块依赖（无需指定版本,从父模块继承） -->
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>util</artifactId>
		</dependency>

		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>core</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>protocol</artifactId>
		</dependency>
		
		<!-- 第三方依赖（如果在父模块中预定义了。则无需指定版本，如果只有这个这个模块使用，则可以直接指定版本） -->
		<!-- https://mvnrepository.com/artifact/org.lionsoul/ip2region -->
		<dependency>
		    <groupId>org.lionsoul</groupId>
		    <artifactId>ip2region</artifactId>
		    <version>1.7.2</version>
		</dependency>
		
	</dependencies>

	<build>
		<finalName>game</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.1.0</version>

				<configuration>
					<!--jar包名字是否在finalName后追加AssemblyId -->
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>${game.assembly.descriptor}</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<!-- this is used for inheritance merges 绑定到这个生命周期 -->
						<phase>package</phase>
						<goals>
							<!-- 执行一次 -->
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>


</project>