<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>cn.game</groupId>
	<artifactId>login</artifactId>
	<version>1.0</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>
	<build>
		<finalName>login</finalName>
			<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<release>17</release>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<!-- <version>2.2.1</version> -->
				<configuration>
					<!--jar包名字是否在finalName后追加AssemblyId -->
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>package.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<!-- this is used for inheritance merges 绑定到这个生命周期 -->
						<phase>package</phase>
						<goals>
							<!-- 执行一次 -->
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

<!-- 			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<excludeTransitive>false</excludeTransitive>
							<stripVersion>false</stripVersion>
						</configuration>
					</execution>
				</executions>
			</plugin>
			-->
			
			</plugins>
			
	</build>
	<dependencies>
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>util</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>protocol</artifactId>
			<version>1.0</version>
		</dependency>
		
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>core</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>com.github.wechatpay-apiv3</groupId>
			<artifactId>wechatpay-java</artifactId>
			<version>0.2.14</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.github.binarywang/weixin-java-pay -->
		<dependency>
			<groupId>com.github.binarywang</groupId>
			<artifactId>weixin-java-pay</artifactId>
			<version>4.6.5.B</version>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-web-templ-freemarker</artifactId>
			<version>4.2.1</version>
		</dependency>

	</dependencies>

</project>