# PbProtocol.java /u6240/u5728/u76ee/u5f55
PbProtocol.dir=C:/work_all/work/server/protocol/src/main/java/cn/game/protocol/protobuf
# /u751f/u6210/u7684/u5ba2/u6237/u7aefTest /u76ee/u5f55
client.test.dir=C:/work_all/work/simulationclient/src/main/java/cn/game/simulation/test/gen
# /u751f/u6210/u524d/u7aef/u7528/u7684js/u6587/u4ef6
client.js.dir=D:/src/First_party/program/tools/Proto

# /u662f/u5426/u5c06.proto/u6587/u4ef6/u7528protoc/u751f/u6210java/u4ee3/u7801
proto.to.java=true

# .proto /u6587/u4ef6/u76ee/u5f55
protos.dir=C:/work_all/work/server/protocol/src/main/java/cn/game/protocol/protos
# java/u6e90/u6587/u4ef6/u76ee/u5f55
java.src.dir=C:/work_all/work/server/protocol/src/main/java


charset=utf-8
