# PbProtocol.java \u6240\u5728\u76ee\u5f55
PbProtocol.dir=/protocol/src/main/java/cn/game/protocol/protobuf
# \u751f\u6210\u7684\u5ba2\u6237\u7aefTest \u76ee\u5f55
client.test.dir=/simulationclient/src/main/java/cn/game/simulation/test/gen
# \u751f\u6210\u524d\u7aef\u7528\u7684js\u6587\u4ef6
client.js.dir=/../Proto

# \u662f\u5426\u5c06.proto\u6587\u4ef6\u7528protoc\u751f\u6210java\u4ee3\u7801
proto.to.java=true

# .proto \u6587\u4ef6\u76ee\u5f55
protos.dir=/protocol/src/main/java/cn/game/protocol/protos
# java\u6e90\u6587\u4ef6\u76ee\u5f55
java.src.dir=/protocol/src/main/java

# \u897f\u6e38\u4e0d\u751f\u6210RequestTest\u7684proto\u6587\u4ef6
not.parse.protos=ServerMsg,MergeEquipMsg,StoryMsg,GmMsg,GemMsg,EquipMsg,DragonMsg,UnionMsg
# \u897f\u6e38\u4e0d\u89e3\u6790\u7684\u534f\u8bae\u524d\u7f00
not.parse.request.prefix=HC

charset=utf-8
