syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
//import "CommonMsg.proto" ;
//import "HeroMsg.proto" ;
import "RewardMsg.proto" ;
import "QuestMsg.proto" ;
// 活动协议
//@HandlerPackage cn.game.games.net.game.module.activity
//@MessageModule 11

//查看有哪些显示的活动
message ActivityListRequest_11000001{
}
//显示的活动列表
message ActivityListResponse_11000002{
   repeated ActivityInfo activitys = 1;
}

// 单个活动基本数据
message ActivityInfo{
	uint32 id = 1; 		//活动id Activity 表的id
	ActivityState state = 2;		// 活动状态
	int32 startTime = 3;			// 距离活动正式开始的时间（秒），针对状态是VIEW的活动
	int32 endTime = 4;			// 距离活动结束的时间（秒）,如果小于等于0 ，表示没有明确的结束时间，或者说一直存在
}
enum ActivityState{
	NONE = 0;		// 不显示此活动
	VIEW = 1  ;		// 活动展示，没有到活动正式开始时间，只能查看
	START = 2  ;	// 活动正式开始，可以参加活动
	CLOSE = 3;		// 活动过期关闭，不能参加，只能查看，或者领奖等操作。
}

//查看某个活动，是否有红点
message ActivityRedPointRequest_11000003{
	repeated int32 ids = 1;  // Activity 表id。
}
//查看的活动，是否有红点。
message ActivityRedPointResponse_11000004{
	repeated bool isRed = 1;
}


//活动状态改变推送，看具体情况选择性推送
message ActivityStatePush_11100006{
   ActivityInfo activity = 1;
}


//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻首充︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻
//查看首冲活动数据
message ActivityFirstChargeRequest_11000007{
   uint32 id = 1; 		//活动id Activity表的id,如果同类型活动有多个，可以用id区分。
}
//首冲活动
message ActivityFirstChargeResponse_11000008{
   repeated FirstChargeActivityInfo singleCharges = 1;// 已经购买的数据
}

//购买首冲礼包，只能购买有售价的礼包。
message ActivityFirstChargeBuyRequest_11000010{
   uint32 id = 1; 		//活动id Activity表的id,如果同类型活动有多个，可以用id区分。
   uint32 chargeId  = 2;    // FirstCharge 表id
}
message ActivityFirstChargeBuyResponse_11000011{
}

//领取首冲礼包奖励
message ActivityFirstChargeRewardRequest_11000012{
   uint32 id = 1; 		//活动id Activity表的 id,如果同类型活动有多个，可以用id区分。
   uint32 chargeId  = 2;    // FirstCharge 表id
}
message ActivityFirstChargeRewardResponse_11000013{
   repeated RewardInfo rewards = 2;  // 购买的物品
}

message FirstChargeActivityInfo{
   uint32 id = 1; //已经购买的 FirstCharge 表id礼包,例如买了1，相当于1、2、3都买了
   int32 status = 2; // 0：没到时间不能领  1: 到时间可以领 2: 领完了
}
//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼首冲︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼

// 七日狂欢
message ActivitySevenDaysCarnivalRequest_11000020{
   uint32 id = 1; 		//活动id Activity表的id,如果同类型活动有多个，可以用id区分。
}
message ActivitySevenDaysCarnivalResponse_11000021{
    repeated SevenDaysQuest sevenDay = 1;  //
}

message SevenDaysQuest{
    int32 day = 1;  // 第几天。 1- 7
	repeated QuestInfo quests = 2 ;  // 当前天数里面的任务。
}

// 七日签到,查看七日签到数据
message ActivitySevenDaysSigninInfoRequest_11000024{
   uint32 id = 1; 		//活动id Activity表的id,如果同类型活动有多个，可以用id区分。
}
message ActivitySevenDaysSigninInfoResponse_11000025{
   uint32 day = 1; 		//领完第几天的奖励
   bool canSignin = 2; 	//是否可以领签到奖励，当天领完就不能再领了。隔天才能领下一天的
  int32  activityId = 3;//活动id 前端根据活动id 区分是 7日的 还是30日的签到
}

// 七日签到,签到领奖 请求
message ActivitySevenDaysSigninRequest_11000026{
   uint32 id = 1; 		//活动id Activity表的id,如果同类型活动有多个，可以用id区分。
  bool  isExtReward = 2; //是否领取额外奖励 true  是， false 不是
}
// 七日签到,签到领奖 响应
message ActivitySevenDaysSigninResponse_11000027{
   repeated RewardInfo rewards = 2;  // 获得的物品
}


//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼活动任务领取︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//活动任务奖励领取 请求
message ActivityTaskRewardRequest_11000041{
  int32 activityId = 1;   //  活动唯一id
  repeated int32  taskIds = 2; //要领取的任务id集合 支持批量领取
}
//活动任务奖励领取 响应
message ActivityTaskRewardResponse_11000042{
  repeated RewardInfo rewards = 3; //任务奖励
}

//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼累充豪礼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//累充豪礼信息请求
message ActivityLeiChongInfoRequest_11000051{
  int32  activityId = 1; //查看的活动id
}
//累充豪礼信息响应
message ActivityLeiChongInfoResponse_11000052{
  int32  activityId = 1; //查看的活动id
  repeated int32 taskIds = 2;//包含的任务id
}

//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼每日豹利︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//每日豹利信息请求
message ActivityBaoLiInfoRequest_11000061{
  int32 activityId = 1; //查看的活动id
}
//每日豹利信息响应
message ActivityBaoLiInfoResponse_11000062{
  int32  activityId = 1; //查看的活动id
  repeated int32 taskIds = 2;//包含的任务id
}
//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼风云聚义︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//风云聚义信息请求
message ActivityQingShenInfoRequest_11000071{
  int32 activityId = 1; //查看的活动id
}
//风云聚义信息响应
message ActivityQingShenInfoResponse_11000072{
  int32  activityId = 1; //查看的活动id
  repeated int32 taskIds = 2;//包含的任务id
  int32 round = 3;  //轮次
  int32 roundTaskId = 4;//轮次的任务
}
//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼金钱豹爆爆︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
//金钱豹爆爆信息请求
message ActivityJQBInfoRequest_11000081{
  int32 activityId = 1; //查看的活动id
}
//金钱豹爆爆信息响应
message ActivityJQBInfoResponse_11000082{
  int32  activityId = 1; //查看的活动id
   int32 taskId = 2;//当前进行的任务id
}
