syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;


// 道具信息
message ItemInfo{
     uint32 id = 1;		//道具id  Item.xlsm表id
     uint32 count = 2;		//道具数量
}

// 资源数据
message AssetInfo{
     uint32 id = 1;		//资源id。Asset表的id
     uint64 count = 2;		//资源数量
}

// 物品信息
message GoodsInfo{

     uint32 id = 1;		//id，可以是Asset表id、Hero表的id、Item表的id等等
     uint32 count = 2;		//数量
}

message MoneyRecoverInfo{
     uint32 id = 1;		//id，Money表id
     uint32 time = 2;		//上次恢复的时间戳（秒）
}

// 英雄信息
message HeroInfo{
	string uid = 1;//英雄唯一id
	uint32 configId = 2;//Hero配置表 ID
	uint32 level = 3;//等级
	uint32 star = 4 ;// 星级
//	bool isBattle = 5; // 是否上阵了
	string fashionUid = 6 ;// 穿戴的时装唯一id
	uint32 quality = 7 ;  // 品质。
	uint32 battlePos = 8 ;  // 上阵位置 1-5 ，0未上阵
}

// 合成英雄信息
message HCHeroInfo{
	string uid = 1;//英雄唯一id
	uint32 configId = 2;//HCHero配置表 ID
	uint32 level = 3;//等级
	uint32 star = 4 ;// 星级
}
// 英雄武器
message HeroSwordInfo{
	string uid = 1;//武器唯一id
	uint32 configId = 2;//HeroSword配置表 ID
	uint32 star = 3 ;// 星级
}
//合并的英雄装备
message MergeEquipmentInfo{
  uint32 id  = 1; //Equip配置表id
  uint32 level = 2;  // 等级
}
//英雄装备
message EquipInfo{
  string uid	   = 1; //唯一id
  uint32 configId  = 2; //HeroEquip配置表id
  map<uint32, uint32> attrs = 6; //装备附加属性条目
}
//装备部位，1-头盔2-披风3-衣服4-项链5-戒指6-靴子，对应HeroEquip的ItemType。
message EquipPartInfo{
  uint32 type  = 1; //部位类型，1-6
  uint32 strength = 2; //强化等级
  uint32 breakthrough = 3; //突破等级
  string equipUid	 = 4; //这个装备部位上安装的装备唯一id
  repeated string gemUids	 = 5; //这个装备部位上安装的宝石唯一id
}
// 英雄时装
message HeroFashionInfo{
	string uid = 1;//时装唯一id
	uint32 configId = 2;//HeroFashion配置表 ID
	uint32 star = 3 ;// 星级
}

//英雄属性信息
message HeroAttrInfo{
	uint32 id 	 = 1;//
	uint32 value = 2;// 属性值
}

//英雄属性点数信息
message HeroAttrPointInfo{
	uint32 id 	 = 1;// AttributeTypeEnum 表的id
	uint32 value = 2;// 属性点数
}

//属性信息
message AttrGrowInfo{
	uint32 id 	 = 1;//  属性id
	uint32 startValue = 2;// 初始值
	uint32 growValue = 3;// 成长值
}

// 宝石数据
message GemInfo{
  string uid	   = 1; //唯一id
  uint32 configId  = 2; //Gem配置表id
  map<uint32, uint32> attrs = 3; //宝石附加属性条目
  bool isLock = 4;  // 锁定状态，true：锁定了。
}

// 龙数据
message DragonInfo{
  uint32 id  = 1; //Dragon配置表id
  uint32 star  = 2; //Dragon星级
}
// 龙技能数据
message DragonSkillInfo{
  uint32 id  = 1; //DragonSkil配置表id
  uint32 level  = 2; //技能等级
}


//技能信息
message SkillInfo{
	uint32 id = 1; //Skill表id
	repeated uint32 strengthenIds = 2;//已经激活强化项id,SkillBuff表的id
}

//宠物
message PetInfo{
	int32 id = 1; // SoulSoulPet表id
	int32 level = 2; // 等级
	int32 breakLevelMax = 3;  // 已经突破的最高等级，例如在20、40、60级时需要突破后才能继续升级，如果在40级时突破了， 则记录40
	repeated int32 skills = 4;  // 拥有的洗练技能， SoulPetSkill表id
	repeated int32 petSkillsToSave = 24;  // 已经消耗道具洗练出来尚未保存的技能id  SoulPetSkill 表id
}

// 神通
message SecretscriptInfo{
	int32 id = 1; // Secretscript表的SecretscriptMark字段。
	int32 level = 2; // 等级
	int32 star = 3;  // 星级
}


// 玩家的简单信息
message SimplePlayerInfo{
	string id = 1; 			// id
	string name = 2; 		//名称
	uint32 level = 3; 		// 等级
	uint32 combatEffectiveness = 4; // 战力
	uint32 head = 6; 		// 头像id
	uint32 headFrame = 7; 		// 头像框
	bool online = 8  ;      // 是否在线
	uint32 offlineTime = 9  ; // 如果离线，此值表示最近的下线时间，秒的时间戳
	string serverId = 10; // 玩家所在服务器id，暂时用不到
	string serverName = 11; // 玩家所在服务器名，暂时用不到
	uint32 tiandaoLevel = 12; // 天道修为等级。
}

// 玩家展示的名片数据
message PlayerShowInfo{
	int32 battleId = 1;   // 主线关卡进度  Battle表id
	string guild = 2; 		// 公会名称
  	repeated HeroInfo heros  = 7;        //当前阵容。
}

message PaymentOrderProto{
	string signData = 1;
	string paySig = 2;
	string signature = 3;
}

enum UpdateType{
  UPDATE = 0; // 更新
  ADD = 1; //增加
  DELETE = 2; //删除
}

