syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;


// 道具信息
message ItemInfo{
     uint32 id = 1;		//道具id  Item.xlsm表id
     uint32 count = 2;		//道具数量
}

// 货币
message CurrencyInfo{
     uint32 id = 1;		//资源id。ResourceEnum的id
     uint64 count = 2;		//资源数量
}

// 资源信息，角色资源
message ResourceInfo{

     uint32 id = 1;		//资源id。ResourceEnum的id
     uint64 count = 2;		//资源数量
}

// 物品信息，一般用来显示使用，不能代表最终获取的物品
message GoodsInfo{

     uint32 id = 1;		//id，可以是Role表的id，Item表的id等等
     uint32 count = 2;		//数量
}

// 英雄信息
message HeroInfo{
	uint64 uid = 1;//英雄唯一id
	uint32 configId = 2;//Hero配置表id
	uint32 level = 3;//等级
	uint32 star = 4 ;// 星级
	uint32 getTime = 11; // 英雄获取时间（时间戳，秒数）
}
// 角色信息
message RoleInfo{

	uint32 id = 1;//角色配置表id
//	uint32 level = 2;//角色等级
//	uint32 exp = 3;//当前经验
	uint32 star = 4 ;// 星级
	repeated uint32 occupationTrees = 5 ;// 已经解锁的天赋树，OccupationLevelTree的id
	repeated OccupationNodeInfo occupationNode = 6 ;// 已经解锁的天赋节点数据
	uint32 friendly = 7 ; 		// 亲密度
	uint32 friendlyLevel = 8 ; 		// 其密度等级
	bool oath = 9 ; 		// 是否誓约过了
    uint32 mechaLevel = 10; // 机甲强化等级
	uint32 getTime = 11; // 角色获取时间（时间戳，秒数）
	uint32 skin = 12; // 当前使用的皮肤id
    uint32 soulWeaponLevel = 13; // 灵武等级
    repeated uint32 skills  = 14;    // 角色已解锁的主动技能(最多6个)出生解锁默认3个,晋升最多解锁3个
    repeated uint32 skillsUsed = 15; // 当前使用的技能id,包括主动、被动、天赋技能。Skill.xlsm 表id
    uint32 state  	= 19;//角色状态  0正常 1 重伤 2阵亡
    uint32 skillPoint = 20 ;//技能点(用于激活技能强化项)
	repeated RoleAttrPointInfo attrPoints = 21; //(升级产生的)属性增加点数
	uint32 nameId = 22;//佣兵名字id，MercenaryName.xlsm表id
	repeated uint32 tagIds = 23; //角色拥有的标签
	repeated uint32 unlockGiftIds = 24; //角色解锁过的礼物卡,GiftCard表id
	bool lock = 25; //是否锁定(锁定状态下不可养成,比如:探索遗迹派遣)
  	uint32 exploreTime = 26; // 上次探索时间（时间戳，秒数）
  	uint32 promotionLevel = 27 ;// 晋升等级
  	uint32 promotionPoint = 28;//晋升点数
  	repeated EquipInfo equips = 29;	//角色身上的装备

}

//角色属性信息
message RoleAttrInfo{
	uint32 id 	 = 1;// RoleAttribute 表的id
	uint32 value = 2;// 属性值
}

//角色属性点数信息
message RoleAttrPointInfo{
	uint32 id 	 = 1;// AttributeTypeEnum 表的id
	uint32 value = 2;// 属性点数
}

//技能信息
message SkillInfo{
	uint32 id = 1; //Skill表id
	repeated uint32 strengthenIds = 2;//已经激活强化项id,SkillBuff表的id
}

// 玩家的简单信息
message SimplePlayerInfo{

	string id = 1; 			// id
	string name = 2; 		//名称
	uint32 level = 3; 		// 等级
	uint32 combatEffectiveness = 4; // 战力
	uint32 head = 6; 		// 头像id
	uint32 headFrame = 7; 		// 头像框
	bool online = 8  ;      // 是否在线
	uint32 offlineTime = 9  ; // 如果离线，此值表示最近的下线时间，秒的时间戳
	string serverId = 10; // 玩家所在服务器id
}

// 玩家展示的名片数据
message PlayerShowInfo{

	string guild = 2; 		// 公会名称
	uint32 combat = 3; 		// 战斗力
	uint32 praisedCount = 4 ; 		// 被点赞数量
	
}


// 皮肤数据
message SkinInfo{
  uint32 id = 1; //配置表id
}

// 芯片数据
message ChipInfo{
  string uid = 1; // 唯一id
  uint32 id = 2; //道具配置表id
  uint32 roleId = 3; //角色id
  uint32 position = 4; //位置
  uint32 grade = 5; //等级
  repeated ChipCommonAttrInfo commonAttrs = 6;//基础属性
  repeated ChipAffixAttrInfo affixAttrs = 7;//词缀
  bool lock = 8; //是否锁定
  uint32 getTime = 9; // 获取时间（时间戳，秒数）
}

// 角色天赋节点信息
message OccupationNodeInfo{

	uint32 id = 1;// OccupationLevelNode 表id
	uint32 level = 2;//等级
}

message ChipCommonAttrInfo{
  uint32 attr = 2; //属性
  uint32 initvalue = 3; //初始值
  uint32 growthvalue = 4; //成长值
}

message ChipAffixAttrInfo{
  AttrType type = 1;//类型
  uint32 attr = 2; //属性
  uint32 value = 3; //值
  uint32 minValue = 4; //最小值
  uint32 maxValue = 5; //最大值
}

enum AttrType{
  ATTR_NULL = 0;
  OLDATTR = 1; //现属性
  NEWATTR = 2; //新属性
}



//核心数据
message CoreUnitInfo{
  string uid = 1; // 唯一id
  uint32 id = 2; //道具配置表id
  uint32 roleId = 3; //角色id
  CoreUnitPos position = 4; //位置
  uint32 breakLevel = 5; //突破等级
  uint32 strengthLevel = 6; //强化等级
  bool lock = 7; //是否锁定
  uint32 getTime = 8; // 获取时间（时间戳，秒数）
}

enum CoreUnitPos{
  POS_NULL = 0;
  A = 1;
  B = 2;
  C = 3;
}

//主界面信息
message HomePageInfo{
	uint32 PosterGirlId = 1; //看板娘roleId
}

//装备数据
message EquipInfo{
	string uid	   = 1; //唯一id
	uint32 id  = 2; //配置表id
  uint32 roleId = 3; //所属角色id
  uint32 slot = 4; //所在槽位
  repeated uint32 buffs = 5; //效果id
  uint32 strength = 6; //强化等级
  //uint32 exp = 7;//经验值
}


enum UpdateType{
  UPDATE = 0; // 更新
  ADD = 1; //增加
  DELETE = 2; //删除
}

message MainCityBuffInfo{
  uint32 buffId 	= 1;	//buff id 对应Main\CityBuff表id
  uint32 count 	= 2;	//回合数
}


