syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;


// 道具信息
message ItemInfo{
     uint32 id = 1;		//道具id  Item.xlsm表id
     uint32 count = 2;		//道具数量
}

// 货币
message CurrencyInfo{
     uint32 id = 1;		//资源id。ResourceEnum的id
     uint64 count = 2;		//资源数量
}

// 资源信息，角色资源
message ResourceInfo{

     uint32 id = 1;		//资源id。ResourceEnum的id
     uint64 count = 2;		//资源数量
}

// 物品信息，一般用来显示使用，不能代表最终获取的物品
message GoodsInfo{

     uint32 id = 1;		//id，可以是Role表的id，Item表的id等等
     uint32 count = 2;		//数量
}

// 英雄信息
message HeroInfo{
	string uid = 1;//英雄唯一id
	uint32 configId = 2;//Hero配置表id
	uint32 level = 3;//等级
	uint32 star = 4 ;// 星级
	uint32 getTime = 11; // 英雄获取时间（时间戳，秒数）
}

//英雄属性信息
message HeroAttrInfo{
	uint32 id 	 = 1;// RoleAttribute 表的id
	uint32 value = 2;// 属性值
}

//英雄属性点数信息
message HeroAttrPointInfo{
	uint32 id 	 = 1;// AttributeTypeEnum 表的id
	uint32 value = 2;// 属性点数
}

//技能信息
message SkillInfo{
	uint32 id = 1; //Skill表id
	repeated uint32 strengthenIds = 2;//已经激活强化项id,SkillBuff表的id
}

// 玩家的简单信息
message SimplePlayerInfo{

	string id = 1; 			// id
	string name = 2; 		//名称
	uint32 level = 3; 		// 等级
	uint32 combatEffectiveness = 4; // 战力
	uint32 head = 6; 		// 头像id
	uint32 headFrame = 7; 		// 头像框
	bool online = 8  ;      // 是否在线
	uint32 offlineTime = 9  ; // 如果离线，此值表示最近的下线时间，秒的时间戳
	string serverId = 10; // 玩家所在服务器id
}

// 玩家展示的名片数据
message PlayerShowInfo{

	string guild = 2; 		// 公会名称
	uint32 combat = 3; 		// 战斗力
	uint32 praisedCount = 4 ; 		// 被点赞数量
}

//装备数据
message EquipInfo{
  string uid	   = 1; //唯一id
  uint32 id  = 2; //配置表id
  uint32 roleId = 3; //所属角色id
  uint32 slot = 4; //所在槽位
  repeated uint32 buffs = 5; //效果id
  uint32 strength = 6; //强化等级
}

message PaymentOrderProto{
	string signData = 1;
	string paySig = 2;
	string signature = 3;
}

enum UpdateType{
  UPDATE = 0; // 更新
  ADD = 1; //增加
  DELETE = 2; //删除
}

