syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
package Protos;
import "RewardMsg.proto" ;
// 章节关卡协议
// 开始关卡战斗请求
message BattleFieldStartRequest_13000001{
	uint32 type = 1; 	// 玩法类型，主线战役推图，日常挑战等。 1代表战役Battle表
	uint32 typeId = 2; // 玩法类型对应的配置表id。 如果上面的type是1，则是Battle表id
	uint32 fieldId = 3;	// BattleField关卡id，有的玩法可能包含多个关卡，做一下区分。
}

// 开始关卡战斗返回
message BattleFieldStartResponse_13000002{
	PlayerBattleAttrs attrs = 1;
}

// 玩家战斗属性数据
message PlayerBattleAttrs{
	map<int32,int32> playerAttrs = 4 ;// 玩家的属性，可能包括装备、宝石、炼金、武器等等系统的属性。
	repeated HeroAttr heroAttrs = 1 ; // 上阵英雄属性
	map<int32,int32> dragonAttrs = 2 ; // 龙属性，一般是龙的基础属性，加上龙的技能属性
	map<int32,int32> wallAttrs = 3 ;// 城池属性
}

// 英雄属性数据
message HeroAttr{
	string heroUid = 1;
	map<int32,int32> heroAttrs = 2 ; // 英雄属性
}

// 结束关卡战斗请求
message BattleFieldEndRequest_13000003{
	uint32 killMonsterCount = 1;	// 击杀怪物数量
	uint32 hpPercent = 2;	// 城池剩余血量百分比，如剩余40%血量，则为40
	bool win = 3;	        // 战斗是否成功，用血量百分比可能有误差。
}

// 结束关卡战斗
message BattleFieldEndResponse_13000004{
	repeated RewardInfo rewards = 1;		// 获得的奖励
}


// 肉鸽刷新,每天前3次免费，第四次看广告。
message BattleRougeRefreshRequest_13000005{
}

// 肉鸽刷新
message BattleRougeRefreshResponse_13000006{
}


//领取战役  首次胜利奖励	首次半血胜利奖励	首次无损胜利奖励
message BattleRewardRequest_13000022{
   uint32 id = 1; 			// Battle表的id
   uint32 index = 2; 			// 0、1、2   代表首次，半血、无损奖励
}
message BattleRewardResponse_13000023{
   repeated RewardInfo reward = 1;
}

// 战役信息
message BattleInfo{
	int32 id = 1;	//Battle表的id
	uint32 hpPercent = 2;	// 打完剩余血量百分比，如剩余40%血量，则为40
	int32 rewardIndex = 3; // 0、1、2   代表首次，半血、无损奖励,领到哪个了，如果没领过是-1
	bool finish = 4; // 这个战役是否通关了。
}
