syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto";
// 章节关卡协议
// 开始关卡战斗请求
message BattleFieldStartRequest_13000001{
	uint32 type = 1; 	// 玩法类型，主线战役推图，日常挑战等。 1代表主线战役，2 道心磨砺 3心魔试炼   11 合成的主线战役12 每日挑战 20 失落真经 6世界boss
	uint32 typeId = 2; // 玩法类型对应的配置表id。 根据上面的type不同可能是不同的表id，例如1、2、3是Battle表id， 11 、12 是HCBattle表id;

	uint32 fieldId = 3;	// BattleField关卡id，有的玩法可能包含多个关卡，做一下区分。不一定有。
}

// 开始关卡战斗返回
message BattleFieldStartResponse_13000002{
	PlayerBattleAttrs attrs = 1;
}

// 玩家战斗属性数据
message PlayerBattleAttrs{
	map<int32,int32> playerAttrs = 4 ;// 玩家的属性，可能包括装备、宝石、炼金、武器等等系统的属性。
	repeated HeroAttr heroAttrs = 1 ; // 上阵英雄属性
	map<int32,int32> dragonAttrs = 2 ; // 龙属性，一般是龙的基础属性，加上龙的技能属性
	map<int32,int32> wallAttrs = 3 ;// 城池属性
}

// 英雄属性数据
message HeroAttr{
	string heroUid = 1;
	map<int32,int32> heroAttrs = 2 ; // 英雄属性
}

// 结束关卡战斗请求
message BattleFieldEndRequest_13000003{
	uint32 killMonsterCount = 1;	// 击杀怪物（小怪+头目）数量
	uint32 killMonsterBossCount = 6;	// 击杀首领数量
	uint32 hpPercent = 2;	// 城池剩余血量百分比，如剩余40%血量，则为40
	bool win = 3;	        // 战斗是否成功，用血量百分比可能有误差。
	uint32 battleTime = 4;	        // 战斗时长（秒）
	uint32 damage = 8;	        // 战斗伤害，例如世界boss战斗需要这个数值。
}

// 结束关卡战斗
message BattleFieldEndResponse_13000004{
	repeated RewardInfo rewards = 1;		// 获得的奖励
}


// 关卡快速战斗请求,也可以当扫荡来使用
message BattleFieldQuickEndRequest_13000005{
	uint32 type = 1; 	// 玩法类型，主线战役推图，日常挑战等。 1代表主线战役，2 道心磨砺 3心魔试炼   11 合成的主线战役12 每日挑战 20 失落真经
	uint32 typeId = 2; // 玩法类型对应的配置表id。 根据上面的type不同可能是不同的表id，例如1、2、3是Battle表id， 11 、12 是HCBattle表id;
	uint32 subId = 3; // 某些typeId类型的，可能需要额外的子id或者进度之类的数据
	bool win = 4;	   // 战斗是否成功，看具体玩法需要，如果失败了什么也不处理，则失败时不用发这个快速战斗的请求。
}

// 关卡快速战斗响应
message BattleFieldQuickEndResponse_13000006{
	repeated RewardInfo rewards = 1;		// 获得的奖励
}

// 看广告并分享之后额外获得xx倍奖励
message BattleShareRequest_13000007{
}

// 看广告并分享之后额外获得xx倍奖励
message BattleShareResponse_13000008{
	repeated RewardInfo rewards = 1;		// 获得的奖励
}

// 复活
message BattleReliveRequest_13000010{
	int32 type = 1;   // 1分享 2广告 3消耗资源
}

//复活
message BattleReliveResponse_13000011{
}


//领取战役  首次胜利奖励	首次半血胜利奖励	首次无损胜利奖励,可以一次领多个战役的。
message BattleRewardRequest_13000022{
   repeated uint32 id = 1; 			// Battle表的id
   repeated uint32 index = 2; 			// 0、1、2   代表首次，半血、无损奖励

}
message BattleRewardResponse_13000023{
   repeated RewardInfo reward = 1;
}

//合成领取战役  首次胜利奖励	首次半血胜利奖励	首次无损胜利奖励,可以一次领多个战役的。
message HCBattleRewardRequest_13000027{
   repeated uint32 id = 1; 			// Battle表的id
   repeated uint32 index = 2; 			// 0、1、2   代表首次，半血、无损奖励

}
message HCBattleRewardResponse_13000028{
   repeated RewardInfo reward = 1;
}


//关卡扫荡
message BattleSweepRequest_13000024{
   uint32 id = 1; 			// Battle表的id
}
message BattleSweepResponse_13000025{
   repeated RewardInfo reward = 1;
}


// 合成关卡扫荡
message HCBattleSweepRequest_13000040{
   uint32 id = 1; 			// HCBattle表的id
}
message HCBattleSweepResponse_13000041{
   repeated RewardInfo reward = 1;
}




/*** 领取巡逻奖励 ***/
message BattlePatrolRewardRequest_13000044{
	bool isFast = 1; // true ：快速巡逻，直接领取固定时长收益。 false： 根据时长领取收益
	bool advertising = 2; // 看广告领取快速巡逻收益，只有是快速巡逻是这个值才有用。
}

message BattlePatrolRewardResponse_13000045{
	repeated RewardInfo rewards = 1;// 随机掉落的奖励
	int32 exp = 2;					// 增加的经验  --- 客户端需本地增加经验
	int32 gold = 3;					// 增加的金币 --- 客户端需本地增加金币
}

// 战役信息
message BattleInfo{
	int32 id = 1;	//Battle表的id
	uint32 hpPercent = 2;	// 打完剩余血量百分比，如剩余40%血量，则为40,可能用不到了
	repeated int32 rewardIndex = 3; // 0、1、2  。领过的章节宝箱
	bool finish = 4; // 这个战役是否通关了。
	uint32 battleTime = 5;	        // 战斗时长（秒），或者说是波数
}

// 巡逻/挂机  数据
message PatrolInfo{
	int32 rewardTime = 1;			// 最后一次领取巡逻奖励的时间(秒时间戳)
	int32 quickPatrolCount = 2;		// 快速巡逻次数，巡逻过的次数
	int32 adPatrolCount = 3;		// 看广告快速巡逻次数，巡逻过的次数
}

/*** 保存阵容 ***/
message BattleLineupRequest_13000048{
	int32 battleType = 1;			// 玩法类型，梦魇秘境  9   大道争锋 50
	LineupInfo lineup = 2;//  阵容数据
}
message BattleLineupResponse_13000049{
}



/*** 合成游戏保存棋盘数据 ***/
message HCBattleDataSaveRequest_13000100{
	string data = 1;			//
}
message HCBattleDataSaveResponse_13000101{
}

/*** 合成游戏请求棋盘数据 ***/
message HCBattleDataRequest_13000102{
}
message HCBattleDataResponse_13000103{
	string data = 1;			//
}


// ****************************************道心磨砺/心魔试炼********************************************
///*** 查看道心磨砺/心魔试炼数据 ***/
message BattleDaoHeartRequest_13000055{
	int32 type = 1;					// 2 道心 3 心魔
}

message BattleDaoHeartResponse_13000056{
	int32 completedId = 1;			//最新通关过的（Battle）表id
	int32 nextId = 2;				// 最新通关的下一关，尚未通关的 （Battle）表id
	repeated int32 randomBuff = 3;			// 每天不同的随机 增益或者减益buff， HeroBUFF表id
	int32 freeSweepRemaning = 4;      // 免费剩余扫荡次数。
	int32 paySweepRemaning = 5;      // 收费剩余扫荡次数。
}

/*** 扫荡道心磨砺/心魔试炼关卡 ***/
message BattleDaoHeartSweepRequest_13000060{
	int32 type = 1;					// 2 道心 3 心魔
	int32 id = 2;					// （Battle）表id
}
message BattleDaoHeartSweepResponse_13000061{
	repeated RewardInfo rewards = 1;//
}

/*** 一键扫荡道心磨砺/心魔试炼关卡 ***/
message BattleDaoHeartSweepBatchRequest_13000062{
	int32 type = 1;					// 2 道心 3 心魔
	int32 id = 2;					// （Battle）表id
	bool pay = 3;				// 是否直接使用付费次数。
}
message BattleDaoHeartSweepBatchResponse_13000063{
	repeated RewardInfo rewards = 1;//
}


/*** 查看道心磨砺/心魔试炼通关奖励领取情况 ***/
message BattleDaoHeartSweepRequest_13000064{
	int32 type = 1;					// 2 道心 3 心魔
}
message BattleDaoHeartSweepResponse_13000065{
	repeated int32 id = 2;					// 已经领取过通关奖励的关卡id， （Battle）表id
}

/*** 领取道心磨砺/心魔试炼关卡通关奖励 ***/
message BattleDaoHeartSweepRequest_13000066{
	int32 type = 1;					// 2 道心 3 心魔
	int32 id = 2;					// （Battle）表id
}
message BattleDaoHeartSweepResponse_13000067{
	repeated RewardInfo rewards = 1;//
}


// ****************************************梦魇秘境********************************************

/*** 请求梦魇秘境数据 ***/
message BattleNightmareRealmRequest_13000080{
}
message BattleNightmareRealmResponse_13000081{
	repeated LineupInfo lineups = 1;//  阵容数据
	repeated int32 randomBuff = 3;			// 每天不同的随机 增益或者减益buff， HeroBUFF表id
	int32 buffRefreshTimes = 4;  // 可用的buff刷新次数
	repeated int32 quickRewardId = 5;    // 领取过的快速奖励的Battle表id(Battle表ClearGameReward有值的)
	map<int32,int32> buffIds = 6;		//  选择使用的全部buff,key NightmareRealmBuff表id: value:等级
	int32  startBattle = 8;			//  手动战斗的起始关卡 Battle表id
	// 是否可以进行扫荡， 如果为true，需要先进行扫荡在手动挑战，如果为false 可以直接挑战
	bool canQuickReward = 9;
}

/*** 梦魇秘境更新buff***/
message BattleNightmareRealmBuffUpdateRequest_13000082{
	map<int32,int32> buffIds = 1;			//  使用的全部buff，如果是null表示放弃本次加成。key NightmareRealmBuff表id: value:等级
}
message BattleNightmareRealmBuffUpdateResponse_13000083{
}

/*** 梦魇秘境快速战斗***/
message BattleNightmareRealmQuickRequest_13000084{
}
message BattleNightmareRealmQuickResponse_13000085{
	repeated RewardInfo rewards = 1;//
}

message LineupInfo{
	int32 seq = 1; 							// 阵容顺序，从0开始
	repeated string heroUid = 2;			// 英雄唯一id
	repeated int32 heroId = 3;			// 英雄配置表id
}
// 某个玩法的阵容数据
message BattleLineupInfo{
	int32 battleType = 1;			// 玩法类型，梦魇秘境  9  ，大道争锋（离线pvp）50
	repeated LineupInfo lineups = 2;//  阵容数据
}


// ****************************************每日挑战********************************************

// 领取每日挑战活跃积分奖励
message BattleDayChallengeReceiveActivePointRequest_13000070
{
	int32 index = 1 ;  // 0-3，一共4个奖励，领哪个
}

message BattleDayChallengeReceiveActivePointResponse_13000071
{
	repeated RewardInfo rewards = 1 ; 			// 获得的奖励
}

message DayChallengeInfo{
   int32 battleTimes   = 1; //每日挑战，挑战过的次数。
   int32 battleId   = 2; //每日挑战，每天不同的Battle 表id。
   repeated int32 randomBuff = 3;			// 每天不同的随机 增益或者减益buff， HeroBUFF表id
   repeated int32 rewardIndex = 4;			// 已经领取过奖励箱子的索引， 如果4个箱子就是0 - 3 。
}


// ****************************************灵魄之战********************************************

// 请求灵魄之战数据
message BattleSpiritualInfoRequest_13000090
{
}

message BattleSpiritualInfoResponse_13000091
{
	BattleSpiritualInfo battleSpiritualInfo = 1;
}

// 领取灵魄之战活跃积分奖励
message BattleSpiritualReceiveActivePointRequest_13000092
{
	repeated int32 index = 1 ;  // 0-3，一共4个奖励，领哪个
}

message BattleSpiritualReceiveActivePointResponse_13000093
{
	repeated RewardInfo rewards = 1 ; 			// 获得的奖励
}

message BattleSpiritualInfo{
   int32 battleTimes   = 1; //当天累计挑战过的次数。
   int32 battleId   = 2; //当前难度，（Battle表id,类型是灵魄之战）
   repeated int32 randomBuff = 3;			// 每天不同的随机 增益或者减益buff， HeroBUFF表id
   repeated int32 rewardIndex = 4;			// 已经领取过奖励箱子的索引， 如果4个箱子就是0 - 3 。
   int32 changeBattleTimes   = 6; //升降难度次数。
   bool adsGetBattleTimes = 7;    // 是否需要看广告获得挑战次数，打完第一次，第二次需要先看广告。
}

// 看广告获取灵魄之战挑战次数
message BattleSpiritualGetTimesRequest_13000094
{
}

message BattleSpiritualGetTimesResponse_13000095
{
}

// 补满积分。
message BattleSpiritualGetPointRequest_13000096
{
}

message BattleSpiritualGetPointResponse_13000097
{
}

//  提升或者降低难度
message BattleSpiritualChangeBattleRequest_13000098
{
	int32 battleId   = 2; //提升或者降低到的难度（Battle表id）
}

message BattleSpiritualChangeBattleResponse_13000099
{
}



// ****************************************失落真经********************************************

// 请求失落真经数据
message BattleLostInfoRequest_13000201
{
}

message BattleLostInfoResponse_13000202
{
	int32 battleId = 1; //当前可打的战役id（还没通关的）战斗关卡。
	int32 battleStage = 2; //当前可打的失落真经非战斗关卡，从1开始，如果为0表示打战斗关卡
	repeated int32 randomBuff = 4; // 只有战斗关才有。每天不同的随机 增益或者减益buff， HeroBUFF表id。
	int32 historyMaxBattle = 5; // 历史最高关卡，今天以前打的最高关
	int32 historyMaxbattleStage = 6; // 历史最高关卡，今天以前打的最高关 （从1开始，如果为0表示打战斗关卡）
	bool historyMaxBattleReward = 7; // 历史最高关卡奖励是否已经领取了。（今天）
}

// 领取失落真经历史最高关卡奖励
message BattleLostDayRewardRequest_13000203
{
}

message BattleLostDayRewardResponse_13000204
{
	repeated RewardInfo rewards = 1;//
}

// ****************************************世界boss********************************************

// 请求世界boss数据
message BattleWorldBossInfoRequest_13000301
{
}

message BattleWorldBossInfoResponse_13000302
{
	string cumulativeDamage = 1 ;  //今日累计伤害
	string maxDamageToday = 2 ;  //今日最高伤害
	int32 rank  = 3 ;  // 我的排名，暂时没有。
	int32 battleTimes  = 4 ;  // 今日已经挑战次数。每天第一次免费，以后需要付费购买。
	int32 buyTimes  = 5 ;  // 今日付费购买次数
	int32 rewardId  = 8 ;  // 已经领取过的宝箱id，WorldBossReward表id， 如果没领过，0或者不存在。
}

// 购买世界boss挑战次数
message BattleWorldBossBuyTimesRequest_13000303
{
}

message BattleWorldBossBuyTimesResponse_13000304
{
}
// 领取世界boss伤害宝箱奖励
message BattleWorldRewardRequest_13000305
{
}

message BattleWorldRewardResponse_13000306
{
	repeated RewardInfo rewards = 1;		// 获得的奖励
}



// 肉鸽刷新,每天前3次免费，第四次看广告。
message BattleRougeRefreshRequest_13000052{
}

// 肉鸽刷新
message BattleRougeRefreshResponse_13000053{
}


/*** 领取体力 ***/
message BattleStaminaRequest_13000050{
	int32 time = 1; //领取哪个时间的体力
}

message BattleStaminaResponse_13000051{
}
// ****************************************大道争锋********************************************
//目标列表刷新 请求
message BattlePvPTargetListRequest_13000111{
	bool refreshFlag = 1;//true 进入玩法首次刷新
	bool  useCost  =2; //true 使用付费刷新 扣除资源; false 使用免费刷新
}

//目标列表刷新 响应
message BattlePvPTargetListResponse_13000112{
	repeated SimplePlayerInfo targetList = 1;//查询到的目标列表
	repeated int32 scoreList = 2;//查询到的目标的当前积分列表
	int32 freeRefreshNum = 3; //今日 免费刷新次数
	int32 refreshNum = 4; //今日 付费刷新次数

}

//开始战斗请求
message BattlePvPStartRequest_13000113{
	string targetId = 1; //要挑战的对手的ID  可能是NPC 也可能是玩家
}
//开始战斗响应
message BattlePvPStartResponse_13000114{
		PlayerBattleAttrs selfAttrs = 1;  //我自己的属性
		PlayerBattleAttrs targetAttrs = 2; //目标的属性 null 则为NPC
		BattleLineupInfo targetLineupInfo = 3; // 目标的阵容 null 则为NPC
	  BattleSecretscriptInfo targetSecretscriptInfo = 4; // 目标当前使用的秘术  null 则为NPC

}
//结算战斗请求
message BattlePvPEndRequest_13000115{
	uint32 killMonsterCount = 1;	// 击杀怪物（小怪+头目）数量
	uint32 killMonsterBossCount = 2;	// 击杀首领数量
	uint32 hpPercent = 3;	// 城池剩余血量百分比，如剩余40%血量，则为40
	bool win = 4;	        // 战斗是否成功，用血量百分比可能有误差。
	uint32 battleTime = 5;	        // 战斗时长（秒）
	uint32 damage = 6;	        // 战斗伤害，例如世界boss战斗需要这个数值。
	int32 endType = 7; 				  // 结算类型: 0 正常结算; 1 主动退出战斗; 2 扫荡结算
	string targetId = 8; 					//要挑战的对手的ID  可能是NPC 也可能是玩家

}
//结算战斗响应
message BattlePvPEndResponse_13000116{
	repeated RewardInfo rewards = 1;
	int32 selfScore = 2;//我的新积分
	int32 targetScore = 3; //对方的积分
}
//获取大道争锋信息 请求
message BattlePvPInfoRequest_13000117{
}
//获取大道争锋信息 响应
message BattlePvPInfoResponse_13000118{
	int32 num = 1; //今天已经挑战的次数
	int32 settlementDayTimer = 2; //今天结算时间戳
	int32 settlementSeasonTimer = 3; //当前赛季的结算时间戳
	int32 nextSeasonTimer = 4; //下一个赛季时间戳
	int32 buyNum = 5; //今日购买的挑战券次数
	map<int32, int32> secretscriptMap = 6; // 神通PVP 阵容 key  id; value 位置 1-5 0表示下阵
	int32 freeRefreshNum = 7; //今日 免费刷新次数
	int32 refreshNum = 8; //今日 付费刷新次数
	repeated SimplePlayerInfo targetList = 9; //之前刷出来的列表
	repeated int32 scoreList = 10;//之前刷出来的列表的目标的当前积分列表


}
//购买挑战券 请求
message BattleBuyPvPTimeRequest_13000121{
}
//购买挑战券 响应
message BattleBuyPvPTimeResponse_13000122{
	int32 buyNum = 1; //今日购买的挑战券次数
	repeated RewardInfo rewards = 2; // 获得的奖励
}
//@NotUseStart
//神通秘术 消息
message BattleSecretscriptInfo{
	map<int32, int32> secretscriptPosMap = 1; //神通位置信息  key id , value pos
	repeated SecretscriptInfo secretscriptList = 2; // 神通信息
}
//@NotUseEnd

