syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
//import "RewardMsg.proto" ;
//import "BaseMsg.proto" ;

//一些玩家级别的养成

// 潜力修炼，升级
message DevelopPotentialLvUpRequest_25000001{
	uint32 id = 1;  	//属性id。Potential表PotentialMark列
}

message DevelopPotentialLvUpResponse_25000002{
}


// 潜力修炼，突破
message DevelopPotentialBreakRequest_25000003{
	uint32 id = 1;  	//属性id。Potential表PotentialMark列
}

message DevelopPotentialBreakResponse_25000004{
}


// 强援修炼，升级
message DevelopRescueLvUpRequest_25000007{
	uint32 id = 1;  	//属性id。Rescue表PotentialMark列
}

message DevelopRescueLvUpResponse_25000008{
}


// 天道修为晋升，提升等级。
message DevelopHeavenlyDaoLvUpRequest_25000010{
}

message DevelopHeavenlyDaoLvUpResponse_25000011{
}

//  **************************** 乾坤镜 ***************************

//灵魄数据
message SpiritualInfo{
  uint32 quality  = 1; //  品质
  int32 level = 2;
  map<uint32, uint32> attrs = 3; //附加属性条目 ， id->数值
}

// 乾坤逆转请求
message QianKunMirrorReversalRequest_25000020{
}

message QianKunMirrorReversalResponse_25000021{
	SpiritualInfo spiritual = 1;
}


// 替换或者丢弃灵魄
message QianKunMirrorReplaceRequest_25000022{
	bool replace = 1; // true 替换， false  丢弃。
}

message QianKunMirrorReplaceResponse_25000023{
}

