syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;

//一些玩家级别的养成

// 潜力修炼，升级
message DevelopPotentialLvUpRequest_25000001{
	uint32 id = 1;  	//属性id。Potential表PotentialMark列
}

message DevelopPotentialLvUpResponse_25000002{
}


// 潜力修炼，突破
message DevelopPotentialBreakRequest_25000003{
	uint32 id = 1;  	//属性id。Potential表PotentialMark列
}

message DevelopPotentialBreakResponse_25000004{
}


// 强援修炼，升级
message DevelopRescueLvUpRequest_25000007{
	uint32 id = 1;  	//属性id。Rescue表PotentialMark列
}

message DevelopRescueLvUpResponse_25000008{
}


// 天道修为晋升，提升等级。
message DevelopHeavenlyDaoLvUpRequest_25000010{
}

message DevelopHeavenlyDaoLvUpResponse_25000011{
}

//  **************************** 乾坤镜 ***************************

// 乾坤镜相关数据
message QianKunMirrorInfo{
	// 当前安装的灵魄，按照数组的顺序作为安装的顺序
	repeated SpiritualInfo spiritual = 1;
	SpiritualInfo spiritualReplace = 2;  // 已经逆转出来的，尚未选择丢弃或者替换的灵魄
	repeated int32 spiritualRootIds = 3; // 已经点亮的  SpiritualRoot 表id
	int32 startPos = 4; // 乾坤逆转起始顺序。 从0开始到5，再从0开始

}
//灵魄数据
message SpiritualInfo{
  uint32 quality  = 1; //  品质
  int32 level = 2;
  repeated AttrGrowInfo atts = 3; //附加属性条目
}

// 乾坤逆转请求
message QianKunMirrorReversalRequest_25000020{
}

message QianKunMirrorReversalResponse_25000021{
	SpiritualInfo spiritual = 1;
}


// 替换或者丢弃灵魄
message QianKunMirrorReplaceRequest_25000022{
	bool replace = 1; // true 替换， false  丢弃。
}

message QianKunMirrorReplaceResponse_25000023{
	repeated RewardInfo rewards = 1 ; 			// 分解后获得的物品
}

// 点亮/解锁 灵根淬炼
message QianKunMirrorSpiritualRootUnlockRequest_25000024{
  int32 id = 1; // SpiritualRoot 表id
}

message QianKunMirrorSpiritualRootUnlockResponse_25000025{
}


