syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
//import "BaseMsg.proto" ;
// 龙相关协议

//龙解锁
message DragonUnlockRequest_17000001{
  int32 id = 1; // Dragon表id
}

message DragonUnlockResponse_17000002{
}


//龙升星
message DragonStarUpRequest_17000003{
  int32 id = 1; // Dragon表id，似乎同id龙只有一个
}

message DragonStarUpResponse_17000004{
}


//龙技能升级
message DragonSkillUpRequest_17000005{
  int32 id = 1; //DragonSkill表id
}

message DragonSkillUpResponse_17000006{
}



