syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
package Protos;
import "RewardMsg.proto" ;

//@HandlerPackage cn.game.games.net.game.module.draw
//@Function PleaseGod
//@MessageModule 37

// 请求卡池界面数据
message DrawListRequest_37000001{
	int32  id = 1;  // Draw表id，代表高级抽卡还是至尊抽卡。
}

// 响应卡池界面
message DrawListResponse_37000002{
	DrawInfo draw = 1;  // 抽卡相关数据
}

message DrawInfo{
	// 废弃了：  还有xxx次赠送xxx品质的卡，key:品质,value:次数
	map<int32,int32> giftRemainingTimes = 1;
	// 废弃了： 赠送当前品质的卡，需要的次数。 key:品质,value:次数
	map<int32,int32> giftMaxTimes = 3;
	int32 nextFreeTime = 2;  // 距离下次免费单抽的时间(秒)

	int32  wishHeroId = 5;  // 选择的心愿英雄id
	int32  wishHeroTimes = 6;  // 还剩几次红卡次数必出心愿英雄，最小是1
}


// 请求抽卡
message DrawRequest_37000003{
	int32  id = 1;  // Draw表id，代表高级抽卡还是至尊抽卡。
	bool ten = 2;  // 是否是十连抽
	bool freeOnce = 3;  // 是否是免费的单抽
}

// 抽卡结果
message DrawResponse_37000004{
	repeated RewardInfo rewards	=	1;	// 抽卡获得的英雄,道具等。
	int32 gold =	2;	// 抽卡获得的金币
	DrawInfo draw = 3;  // 更新相关数据
	repeated RewardInfo heros	=	4;	// 额外赠送的英雄，废弃了
}


// 选择心愿红卡
message DrawHeroWishRequest_37000005{
	int32  heroId = 1;  // Hero表id
}

// 选择心愿红卡返回
message DrawHeroWishResponse_37000006{
}


