syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
//仙友相关协议

//仙友 送礼
message FairyFriendGiftRequest_27000001{
	int32 id = 1; // FairyFriend表id
	int32 itemId = 2; // 选择送的道具id
	int32 count = 3; // 送礼次数，1次或10次，也是消耗道具数量
}
message FairyFriendGiftResponse_27000002{
	// 送礼更新后的仙友数据
	FairyFriendInfo fairyFriendInfo = 1;
}

// 仙友数据
message FairyFriendInfo{
	int32 id = 1; // FairyFriend表id
	int32 exp = 2; // 经验，也就是好感度
	int32 level = 3 ; // 好感度等级。
}

//仙友 切磋
message FairyFriendFightRequest_27000003{
	int32 id = 1; // FairyFriendFight表id
}

message FairyFriendFightResponse_27000004{
}

//领取仙友切磋奖励
message FairyFriendFightRewardRequest_27000005{
	int32 id = 1; // FairyFriendFight表id
}

message FairyFriendFightRewardResponse_27000006{
	repeated RewardInfo reward = 1;	// 获得的奖励
}

//仙友寻缘、游历
message FairyFriendTravelRequest_27000007{
	int32 count = 1; // 寻缘次数，1次或10次
}

message FairyFriendTravelResponse_27000008{
	repeated RewardInfo reward = 1;	// 获得的奖励
	repeated int32 travelId = 2;  // 寻缘到了哪个地方 FairyFriendFightTraveling 表id,一次游历到一个地方
	repeated int32 favorabilityCount = 3;  // 额外增加的仙友好感度数量,一次增加一个仙友好感度
	repeated FairyFriendInfo fairyFriend = 4; // 增加好感度的仙友，增加后的数据。,一次增加一个仙友好感度

}

