syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "RewardMsg.proto" ;

// 请求好友列表
message FriendListRequest_30000001{
}

//  好友数据
message FriendListResponse_30000002{
	repeated FriendInfo friends = 1;  // 好友列表
}
// 请求黑名单列表
message FriendBlackListRequest_30000051{
}

//  黑名单数据
message FriendBlackListResponse_30000052{
	repeated SimplePlayerInfo players = 1;  //
}

// 请求好友申请列表
message FriendApplyListRequest_30000053{

}

message FriendApplyListResponse_30000054{
	repeated SimplePlayerInfo players = 1;    // 好友申请列表
}


// 搜索符合条件的推荐好友
message FriendRecommendRequest_30000003{
}

//  推荐好友列表
message FriendRecommendResponse_30000004{
   repeated SimplePlayerInfo  players = 1;
}

//申请成为对方好友,支持批量
message FriendApplyRequest_30000005{
   repeated string playerIds = 1;		//向哪些玩家申请
}

message FriendApplyResponse_30000006{

}

//处理好友申请,包含批量处理
message FriendApplicationRequest_30000007{
   repeated string playerIds = 1;		//处理申请的玩家id
   bool agree = 2;						//true同意申请，false拒绝
}

message FriendApplicationResponse_30000008{
   repeated string friendIds = 1;				//成功加为好友的玩家id，可能因为某些原因，有些玩家会添加失败。
}

// 删除好友,从黑名单里移除也用这个协议
message FriendDeleteRequest_30000009 {
	string id = 1; 		// 好友id
}
message FriendDeleteResponse_3000000a {

}

// 将好友加入到黑名单
message FriendBlackRequest_30000010 {
	string id = 1; 		// 玩家id
}
message FriendBlackResponse_30000011 {

}

//赠送好友友情点，注意人数不要发多了，超过每日次数限制。
message FriendGiftRequest_30000012{
   repeated string friendId = 1;		//赠送的好友id
}

message FriendGiftResponse_30000013{

}


//领取好友赠送的友情点，包含一键领取，注意人数不要领多了，超过每日次数限制。
message FriendGiftReceiveRequest_30000014{
   repeated string friendId = 1;		//好友id
}

message FriendGiftReceiveResponse_30000015{
   repeated RewardInfo rewards = 1;  // 获得的物品,这里是友情值
}

// 好友的数据
message FriendInfo {
	SimplePlayerInfo player = 1 ;		// 好友基本数据
	FriendGiftInfo gift= 2 ;			// 好友送礼数据
}

// 好友送礼数据
message FriendGiftInfo {
	bool giftToFriend = 1 ;  // 是否给这个好友送过友情点
	bool giftToMe = 2  ;      // 这个好友是否给我送过友情点
	bool receive = 3  ;      // 如果好友给我送友情点了，我是否领取过
}

/********** 下面的协议只有服务器用到 ***********/

//玩家收到其他服务器的好友申请
message FriendApplyPush_30000022{

   int64 playerId = 1;			//收到申请的玩家
   int64 applyPlayerId = 2;		// 申请人id
   string applyPlayerServer = 3;  // 申请人所在服务器
}


//增加其他服务器的好友
message FriendAddPush_30000023{

   int64 playerId = 1;		//待增加的玩家id
   int64 friendId = 2;		// 新加入的好友id
   string friendServer = 3;  // 好友所在服务器id
}


//删除其他服务器的好友
message FriendDelPush_30000024{

   int64 playerId = 1;		//待操作的玩家id
   int64 friendId = 2;		// 删除的好友id
}

// 赠送礼物推送
message FriendGiftPush_30000028{

   int64 sendPlayerId = 1;		//发起赠送的玩家id
   int64 recvPlayerId = 2;		// 接受送礼的玩家id
}









