syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
// Gm协议
// 查看某玩家数据，优先id，如果id没有通过name查询。
message GmPlayerRequest_77000021{
	string channel = 1; // 渠道，暂时用不到。
	string serverId = 2; // 服务器id，暂时用不到。
	string playerId = 3;
	string name = 4;
}

//  查看玩家数据响应
message GmPlayerResponse_77000022{
	GmPlayerInfo player = 1;
}

// 查询订单,哪个参数有值用哪个查，如果都没有值
message GmOrderRequest_77000025{
	string playerId = 1;
	// 内部订单号
	string internalOrderId = 2;
	string createDate = 3;
	string productId = 4 ;   // 商品id;
	//如果上面的参数都没有，则查询全部，用下面分页的参数
	int32  pageNum = 5;		// 第几页
	int32  pageSize = 6;   // 每页记录数
}

//  订单响应。
message GmOrderResponse_77000026{
    repeated OrderInfo orders = 1;
}


// 补单
message GmOrderReimburseRequest_77000027{
	string internalOrderId = 1;
}

//  补单响应。
message GmOrderReimburseResponse_77000028{
}


// gm给指定玩家发邮件 已废弃
message GmMailPlayerSendRequest_77000040{
	string serverId = 14; // 服务器id，暂时用不到
	repeated string playerId = 2;  // 接受邮件的玩家,类型是个人邮件时有效
	string title = 3;  			//标题
	string content = 4;  		//内容
	int32 sendTime = 5;  		//个人邮件的发送时间（秒时间戳）
	bool oneKeyReiceve = 8;		// 是否允许一键领取
	repeated GoodsInfo attachments = 9;	//附件奖励
}
message GmMailPlayerSendResponse_77000041{
}


// gm给指定服务器发邮件
message GmMailServerSendRequest_77000048{
	repeated string serverId = 1; // 全服邮件 允许的服务器 id
	string title = 2;  			//标题
	string content = 3;  		//内容
	int32 sendStartTime = 4;  		//全服邮件的 验证起始时间（秒时间戳）
	int32 sendEndTime = 5;  		//全服邮件的验证 截止时间（秒时间戳）
	repeated GoodsInfo attachments = 6;	//附件奖励
	int32 levelStart = 7;  		//限制起始等级
	int32 levelEnd = 8;  		//限制结束等级
	repeated string playerIds = 9;  // 接受邮件的玩家,类型是个人邮件时有效
	int32 timeCheckType = 10;      //全服邮件 时间校验方式 0 登录时间 1 注册时间

}
message GmMailServerSendResponse_77000049{
}



// 查看邮件列表
message GmMailListRequest_77000042{
	repeated string serverId = 1; // 服务器id，暂时用不到。全服邮件会选多个服务器id，个人邮件用1个
	int32 type = 2;  				// 1 个人邮件 2 全服邮件 0 个人邮件+全服邮件
	//查询参数
	string title = 3;  			//标题
	string content = 4;  		//内容
	int32 startTime = 5;  		//邮件创建的开始时间
	int32 endTime = 7;  		//邮件创建的结束时间
	int32 status = 10;   			//1 暂未审核 2 审核成功  3审核失败。0 全部状态
	// 分页显示
	int32  pageNum = 20;		// 第几页
	int32  pageSize = 21;   // 每页记录数
}
message GmMailResponse_77000043{
	repeated GmMailInfo mails = 1;
}

// 审核邮件
message GmMailCheckRequest_77000044{
	repeated string uid = 1; //
}
message GmMailCheckResponse_77000045{
}


// 删除邮件
message GmMailDeleteRequest_77000046{
	repeated string uid = 1; //
}
message GmMailDeleteResponse_77000047{
}


// 邮件数据
message GmMailInfo{
	string uid = 1;  			//邮件唯一id
	int32 type = 2;   			// 0 个人邮件 1 全服邮件
	string title = 3;  			//标题
	string content = 4;  		//内容
	int32 createTime = 5;  		//创建时间（秒时间戳）
	int32 checkTime = 6;  		//审核通过时间（秒时间戳）
	string sendName = 7;  			//发件人
	string checkName = 8;  			//审核人
	repeated GoodsInfo attachments = 9;	//附件奖励
	int32 status = 10;   			//0 未审核; 1 已审核  3审核失败。
	repeated string serverId = 11; // 邮件发送区服，暂时用不到
	int32  timeCheckType = 12;      //全服邮件 时间校验方式 0 登录时间 1 注册时间
  int32 levelStart = 13;      //限制起始等级
  int32 levelEnd = 14;      //限制结束等级
  repeated string playerIds = 15;  // 接受邮件的玩家,类型是个人邮件时有效
}



// 增加公告
message GmNoticeAddRequest_77000060{
	GmNoticeInfo notice = 1;
}

message GmNoticeAddResponse_77000061{

}

// 更新公告
message GmNoticeUpdateRequest_77000062{
	GmNoticeInfo notice = 1;// 待更新公告，注意设置uid参数
}

message GmNoticeUpdateResponse_77000063{

}

// 删除公告
message GmNoticeDeleteRequest_77000064{
	repeated string uid = 1;
}

message GmNoticeDeleteResponse_77000065{

}


// 查看公告列表
message GmNoticeListRequest_77000066{

}

message GmNoticeListResponse_77000067{
	repeated GmNoticeInfo  notices = 1;
}
message GmNoticeInfo{
	string channel = 1; // 渠道，暂时用不到。
	string uid = 2; // 公告唯一id，服务端生成。
	string title = 3;  			//标题
	string content = 4;  		//内容
	int32 startTime = 5;  		//公告执行开始时间（秒时间戳）
	int32 endTime = 7;  		//公告执行结束时间（秒时间戳）
}



// 关闭服务器
message GmShutdownServerRequest_77000001{

}

// 关闭服务器响应
message GmShutdownServerResponse_77000002{

}

// 请求封号列表
message GmAccountForbidListRequest_77000003{
	// 分页显示
	int32  type = 1; //封禁类型 0 所有， 1 封禁账号，2 禁言
	int32  pageNum = 20;		// 第几页
	int32  pageSize = 21;   // 每页记录数
}
// 响应封号列表
message GmAccountForbidListResponse_77000004{
	repeated ForbidAccountInfo accounts = 1; // 被封的账号
}

// 封号信息
message ForbidAccountInfo{
	string playerId 	= 1;// 封停玩家id
	string name 		= 2; //封停玩家名
	string channel = 3; // 渠道，暂时用不到。
	int32 startTime = 4;  		//开始封停时间（秒时间戳）
	int32 endTime = 5;  		//封停结束时间（秒时间戳），如果小于0表示永久封停
	string reason 		= 8; //封禁原因
	int32  type = 9; //封禁类型 0 所有， 1 封禁账号，2 禁言
}


// 请求封号
message GmAccountForbidRequest_77000005{
	repeated string playerId 	= 1;
	string reason 		= 2;//封禁原因
	int32 endTime	= 3;//封停结束时间（秒时间戳），如果小于0表示永久封停
	int32  type = 4; //封禁类型 0 所有， 1 封禁账号，2 禁言
}
// 响应封号
message GmAccountForbidResponse_77000006{
}

// 请求解封
message GmAccountUnblockRequest_77000007{
	repeated string playerId = 1;
}
// 响应解封
message GmAccountUnblockResponse_77000008{
}


// 请求gm操作记录列表
message GmOperationRequest_77000071{
	string account = 1;
	string functionName = 3;  // 功能名称
	int32 startTime = 4;  		//开始时间
	int32 endTime = 5;  		//结束时间
	string detail = 8;		//操作详情
	string reason = 9;		//操作原因
		// 分页显示
	int32  pageNum = 20;		// 第几页
	int32  pageSize = 21;   // 每页记录数
}
// gm操作记录
message GmOperationResponse_77000072{
	repeated GmOperationInfo records = 1;
}

// gm操作记录
message GmOperationInfo{
	string account = 1;	// 账号、用户名
	string ip = 2;
	string functionName = 3;  // 功能名称
	string opType = 4;  // 操作方式
	int32 createTime = 5;  		//创建时间
	repeated string serverIds = 6;		//操作的服务器id集合
	repeated string playerIds = 7;		//操作的玩家id集合
	string detail = 8;		//操作详情
	string reason = 9;		//操作原因

}


//用户基本信息
message GmPlayerInfo{
	string serverId = 1;
	string plantform = 2;
	string channel = 3;

    string playerId = 4;//账号id，角色id。
    string name = 5;//用户名,昵称
    uint32 level = 6;//等级

   	map<uint32, uint64> assets = 8;   // 主要是货币，附带一些经验体力等数据。   key:Asset表id
	string unionId = 9; // 工会id
	string unionName = 10; // 工会名
	bool isOnline = 11; // 是否在线。
	uint32 createTime  = 12; // 创建时间，秒时间戳
	uint32 lastLoginTime  = 13; // 最后登录时间，秒时间戳
	uint32 curBattleId  = 14; // 当前所在关卡
	uint32 power  = 15; // 战力

	uint32 chargeCumulation  = 50; //累计充值金额
	uint32 moneyCumulation  = 51; //累计获取现金券数量？

}
// 订单数据
message OrderInfo{
	string serverId = 1;
	string plantform = 2;

    uint32 playerId = 4;//账号id，角色id。
    string name = 5;//用户名,昵称
    string internalOrderId = 6;// 内部订单号
    string status = 7;// 订单状态
	string channel = 3; // 渠道

	string productId = 10 ;   // 商品id;
	int32 price = 11 ;   // 价格;

	string source = 15; //充值来源
	string gift = 16; //礼包内容
	int32 payCount = 17; //付款金额
	string createTime = 18; //订单创建时间
	string updateTime = 19; //订单修改时间

}


// 操作服务器重启等
message GmServerOpRequest_77000030{
	string serverId = 1;
	int32 opType = 2 ;   // 1关闭，2重启（启动）
}
// 操作服务器重启等
message GmServerOpResponse_77000031{
}


// 改变服务器状态
message GmServerStatusRequest_77000032{
	string serverId = 1;
	int32 status = 2 ;   // 1正常开放，2维护
}
// 改变服务器状态
message GmServerStatusResponse_77000033{
}




// 请求踢下线
message GmPlayerLogoutRequest_77000009{
	string playerId = 1;
}
// 响应踢下线
message GmPlayerLogouttResponse_7700000a{
	uint32 errorCode = 1;
}

