syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
// Gm协议

// 关闭服务器
message GmShutdownServerRequest_77000001{

}

// 关闭服务器响应
message GmShutdownServerResponse_77000002{

}


// 请求封号列表
message GmForbidAccountListRequest_77000003{

}
// 响应封号列表
message GmForbidAccountListResponse_77000004{
	repeated ForbidAccountInfo accounts = 1; // 被封的账号
}

// 封号信息
message ForbidAccountInfo{
	string playerId 	= 1; 			
	string name 		= 2; 		
	uint32 level 		= 3; 		
	string reason 		= 4; //封禁原因
	string unblockTime	= 5;//解封时间
}



// 请求封号
message GmForbidAccountRequest_77000005{
	string playerId 	= 1;
	string reason 		= 2;//封禁原因
	string unblockTime	= 3;//解封时间
}
// 响应封号
message GmForbidAccountResponse_77000006{
	uint32 errorCode = 1;
}


// 请求解封
message GmUnblockAccountRequest_77000007{
	string playerId = 1;
}
// 响应解封
message GmUnblockAccountResponse_77000008{
	uint32 errorCode = 1;
}

// 请求踢下线
message GmPlayerLogoutRequest_77000009{
	string playerId = 1;
}
// 响应踢下线
message GmPlayerLogouttResponse_7700000a{
	uint32 errorCode = 1;
}

// gm给指定玩家发邮件
message GmPlayerMailRequest_77000010{
	int64 playerId = 1;
	uint32 id = 3 ;			//Mail表id
	string title = 5;  			//标题，如果有值用这个值，如果没有从Mail表里面取内容
	string content = 8;  		//内容，如果有值用这个值，如果没有从Mail表里面取内容
	repeated GoodsInfo attachments = 13;	//附件奖励

}
message GmPlayerMailResponse_77000011{
	uint32 errorCode = 1;
}
