syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;
//合成英雄相关协议


//英雄升级
message HCHeroUpLevelRequest_26000001{
  string uid = 1; // 英雄唯一id
  bool ads = 2; // 是否是看广告升级，看广告升级不消耗资源，每天有免费次数
}

message HCHeroUpLevelResponse_26000002{
}

//英雄升星，也就是觉醒
message HCHeroStarUpRequest_26000003{
  string uid = 1; // 英雄唯一id
}

message HCHeroStarUpResponse_26000004{
}

//切换使用的英雄
message HCHeroBattleRequest_26000005{
  string uid = 1; // 英雄唯一id
}

message HCHeroBattleResponse_26000006{

}

//使用碎片合成英雄
message HCHeroCompositeRequest_26000007{
  int32 id = 1; // HCHero表id
}

message HCHeroCompositeResponse_26000008{
	HCHeroInfo hero = 1;
}


//看广告获得英雄碎片
message HCHeroAdsRequest_26000009{
	int32 id = 1; // HCHero表id
}

message HCHeroAdsResponse_2600000a{
	repeated RewardInfo reward = 1;	// 获得的奖励
}



