syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
// 英雄相关协议

//英雄升级
message HeroUpLevelRequest_16000001{
  string uid = 1; // 英雄唯一id
}

message HeroUpLevelResponse_16000002{
}

//英雄一键升级,自动升级到最高级。
message HeroUpLevelMaxRequest_16000021{
  string uid = 1; // 英雄唯一id
}

message HeroUpLevelMaxResponse_16000022{
	int32 level = 1; // 升到的等级
}


//英雄合成,也就是升星，突破。当前品质下可以升星，星级升满之后进行突破，改变品质。
message HeroConflateRequest_16000003{
  string uid = 1; // 本体英雄唯一id
  // 被消耗的英雄唯一id,如果使用了万能耗材，万能耗材不用填写这个值
  repeated string consumedUid = 2;
}
// 合成返回,客户端这里自己把相关的英雄、万能耗材扣掉。
message HeroConflateResponse_16000004{
	HeroInfo hero = 1;	// 本体英雄，不删除，保留uid，只改变品质和星级。
}


//英雄上阵
message HeroBattleRequest_16000005{
  string uid = 1; // 英雄唯一id
}

message HeroBattleResponse_16000006{
}


//英雄等级重置,返还升级材料
message HeroLevelResetRequest_16000007{
  string uid = 1; // 英雄唯一id
}

//客户端看看自己读表返还升级的材料
message HeroLevelResetResponse_16000008{

}


//英雄品质重置
message HeroQualityResetRequest_16000011{
  string uid = 1; // 英雄唯一id
}

message HeroQualityResetResponse_16000012{
	repeated HeroInfo heros = 1;	// 返还的本体英雄卡牌，需要uid
	repeated ItemInfo items = 2;	// 返还的万能突破道具。
}



