syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "RewardMsg.proto" ;
//@File 英雄相关协议

//@HandlerPackage cn.game.games.net.game.module.develop.hero
//@MessageModule 16


//英雄升级
message HeroUpLevelRequest_16000001{
  string uid = 1; // 英雄唯一id
}

message HeroUpLevelResponse_16000002{
}

//英雄一键升级,自动升级到最高级。
message HeroUpLevelMaxRequest_16000021{
  string uid = 1; // 英雄唯一id
  int32 maxLevel = 2; // 指定升级到最高多少级，如果为0表示自动升级到最高等级。
}

message HeroUpLevelMaxResponse_16000022{
	int32 level = 1; // 升到的等级
}

//批量英雄升级，能升级哪个升级哪个
message HeroUpLevelBatchRequest_16000023{
}

message HeroUpLevelBatchResponse_16000024{
	repeated HeroInfo heros = 1;	// 升级后的英雄等级数据，注意这里只取uid和等级数据,其他数据可能没有设置
}
//批量升级上阵的英雄，按照品质和星级的顺序
message HeroBattleUpLevelBatchRequest_16000025{
}

message HeroBattleUpLevelBatchResponse_16000026{
	repeated HeroInfo heros = 1;	// 升级后的英雄等级数据，注意这里只取uid和等级数据,其他数据可能没有设置
}

//英雄合成,也就是升星，突破。当前品质下可以升星，星级升满之后进行突破，改变品质。
message HeroConflateRequest_16000003{
  repeated HeroConflateInfo heroConflateInfo = 2;
}
// 合成返回,客户端这里自己把相关的英雄、万能耗材扣掉。
message HeroConflateResponse_16000004{
  repeated HeroInfo hero = 1;	// 本体英雄，不删除，保留uid，只改变品质和星级。
}
message HeroConflateInfo{
	  string uid = 1; // 本体英雄唯一id
  	// 被消耗的英雄唯一id,如果使用了万能耗材，万能耗材不用填写这个值,  废弃了。
  	repeated string consumedUid = 2;
  	// 消耗的同职业碎片id和数量
  	map<int32,int32> sameProfessionItems = 5 ;
}

//英雄上阵
message HeroBattleRequest_16000005{
  string uid = 1; // 英雄唯一id
  int32 pos = 2;   // 1- 5;
}

message HeroBattleResponse_16000006{

}


//英雄下阵
message HeroBattleDismissRequest_16000009{
  string uid = 1; // 英雄唯一id
}

message HeroBattleDismissResponse_1600000a{

}


//英雄等级重置,返还升级材料
message HeroLevelResetRequest_16000007{
  repeated string uid = 1; // 英雄唯一id
}

//客户端看看自己读表返还升级的材料
message HeroLevelResetResponse_16000008{

}


//英雄品质重置
message HeroQualityResetRequest_16000011{
  string uid = 1; // 英雄唯一id
}
// 英雄品质重置返回
message HeroQualityResetResponse_16000012{
	HeroInfo hero = 1;	// 重置后的英雄数据
	repeated RewardInfo items = 2;	// 返回的本体碎片，和同职业碎片
}

//请求免费英雄日租卡，这个只有在功能开启的时候请求一下，不能重复请求
message HeroFreeDayRentRequest_16000030{
}

message HeroFreeDayRentResponse_16000031{
	repeated HeroInfo heros = 1;	// 免费日租英雄
}

//选择某个英雄日租卡。
message HeroFreeDayRentChooseRequest_16000032{
	string uid = 1; // 日租卡英雄uid。
}

message HeroFreeDayRentChooseResponse_16000033{
}



//查看图鉴数据
message HeroIllustrationsListRequest_16000040{
}

message HeroIllustrationsListResponse_16000041{
	repeated int32 heroIds = 1; 	// 曾经拥有过，但是现在已经不在了的英雄id  Hero表id
	repeated HeroIllustrationsInfo heros  = 2;  // 图鉴领奖
}

// 可以领取图鉴奖励的英雄
message HeroIllustrationsInfo{
	int32 heroId = 1;			// Hero表id
	repeated int32 quality  = 2; // 品质对应的奖励，如果品质等于英雄的初始品质，则表示获得奖励，
	// 如果大于初始品质，则是突破到该品质的奖励
}

//一键领取英雄的图鉴奖励
message HeroIllustrationsRewardRequest_16000042{
}

message HeroIllustrationsRewardResponse_16000043{
	repeated RewardInfo reward = 2;	// 获得的奖励
}

//使用英雄碎片合成英雄
message HeroFragmentComposeRequest_16000050{
	repeated int32 heroId = 1;			// Hero表id
}

message HeroFragmentComposeResponse_16000051{
	repeated RewardInfo reward = 2;	// 获得的奖励
}
//英雄分解成碎片
message HeroDisassembleRequest_16000052{
	string uid = 1;			// 待分解的英雄唯一id
}

message HeroDisassembleResponse_16000053{
	repeated RewardInfo reward = 2;	// 获得的奖励
}


