syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;

// 道具相关协议

//出售
message DeprecatedItemSaleRequest_0b000001{
  uint32 id = 1;
  uint32 num = 2;
}

message DeprecatedItemSaleResponse_0b000002{

}

//使用道具
message DeprecatedItemUseRequest_0b000003{
     uint32 id = 1;				//道具ID
     uint32 count = 2;		//使用数量
}

// 使用道具后可能会给资源，道具等。
message DeprecatedItemUseResponse_0b000004{
	 repeated RewardInfo reward  = 1; // 获取的东西
}

//分解
message DecomposeRequest_0b000005{
  repeated string uid = 1;	//uid
  int32 type = 2; //类型 GoodsTypeEnum 里的id
}

message DecomposeResponse_0b000006{
  repeated RewardInfo reward  = 1;  //获取的东西
}

//锁定
message EquipLockRequest_0b000007{
    string uid = 1;
    int32 type = 2; //类型 GoodsTypeEnum 里的id
}

message EquipLockResponse_0b000008{

}


//丢弃道具请求
message ItemDiscardRequest_0b000103 {
	uint32 gridId = 1; 	//背包格子id
  	uint32 num 	= 2; 	//丢弃的数量
}
//丢弃道具响应
message ItemDiscardResponse_0b000104{

}

//使用道具请求
message ItemUseRequest_0b000107{
  uint32 gridId 	= 1; //背包格子id
  uint32 targetId 	= 2; //指定对象id (角色uid或队伍id)
} 
//使用道具响应
message ItemUseResponse_0b000108{
	uint32 gridId 	= 1; //背包格子id
	uint32 targetId = 2;//指定对象id (角色id或队伍id)
}

//一键整理背包请求
message ItemBagSortRequest_0b000113{

}
//一键整理背包响应
message ItemBagSortResponse_0b000114{
	repeated BagGridInfo bagGridInfos = 1; //背包格子
}


// -------------------------PUSH--------------------------------

// 背包格子推送
message ItemBagGridPush_0b000320{
	repeated BagGridInfo bagGridInfos = 1; //背包格子
}


//背包数据
message BagInfo {
	repeated ResourceInfo resources = 1; //探索中获得的资源
	repeated BagGridInfo bagGridInfos = 2; //背包格子
//	repeated ItemInfo otherItems = 3; //不占格子的道具
}

//背包格子
message BagGridInfo {
	int32 id = 1;			//格子id,从1开始
	ItemInfo item = 2; 		//道具
	EquipInfo equip = 3; 	//装备
}


