syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "RewardMsg.proto" ;

//请求邮件列表。
message MailListRequest_12000001{

}

//邮件列表数据
message MailListResponse_12000002{
	repeated MailInfo mails  = 1;        //
}

//查看未读邮件
message MailSeeRequest_12000003{
	string  uid = 1 ;	//邮件id,如果是null表示一键读取所有未读邮件
}

//
message MailSeeResponse_12000004{
}


//领取邮件奖励
message MailReceiveRequest_12000005{
	string  uid = 1 ;	//邮件id,如果是null表示一键领取所有的附件奖励
}

//领取邮件奖励返回
message MailReceiveResponse_12000006{
	repeated RewardInfo rewards  = 1;        //
}

//删除邮件
message MailDeleteRequest_12000007{
	string uid = 1 ;	//邮件id,如果是null表示删除所有已读邮件
}

//删除邮件返回
message MailDeleteResponse_12000008{
}


//新邮件推送
message MailNewPush_12010001{
	MailInfo mail  = 1;  // 邮件内容
}

// 单个邮件数据
message MailInfo{
	// 邮件类型，1: 公告邮件 2 : 系统邮件
	uint32 type = 1  ;
	string uid = 2 ;			//邮件唯一id
	uint32 id = 3 ;			//Mail表id
	string sender = 4;			//发件人,暂时不用。
	string title = 5;  			//标题，如果有值用这个值，如果没有从Mail表里面取内容
	string content = 8;  		//内容，如果有值用这个值，如果没有从Mail表里面取内容
	uint32 time = 9;			//发送时间（时间戳，秒）或者说是收到的时间
	uint32 expireTime = 10;		//过期时间（时间戳，秒）,如果为0表示不过期。
	bool see = 11;				//是否查看过
	bool receive = 12;			//是否领取过附件奖励
	repeated GoodsInfo attachments = 13;	//附件奖励
}


// 下面协议只服务器用到。


//邮件


