syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
//import "RewardMsg.proto" ;
//@File 宠物相关协议

//@HandlerPackage cn.game.games.net.game.module.develop.pet
//@Function SoulPets
//@MessageModule 19

//碎片合成宠物
message PetCompositeRequest_19000001{
  int32 id = 1; // SoulSoulPet表id
}

message PetCompositeResponse_19000002{
}


//宠物升级
message PetUpLevelRequest_19000003{
  int32 id = 1; // SoulPet表id
}

message PetUpLevelResponse_19000004{
}

//宠物突破
message PetBreakUpRequest_19000005{
  int32 id = 1; // SoulPet表id
}

message PetBreakUpResponse_19000006{
}


//宠物洗练
message PetRefineRequest_19000007{
  int32 id = 1; // SoulPet表id
}

message PetRefineResponse_19000008{
	repeated int32 skills = 1;  // 洗练技能， SoulPetSkill 表id ，显示用。
}


//实际保存上一次刷新出来的技能
message PetRefineSaveRequest_19000009{
	int32 id = 1; // SoulPet表id
}

message PetRefineSaveResponse_1900000a{
}


//宠物上阵
message PetBattleRequest_19000011{
  int32 id = 1; // 上阵传SoulPet表id,下阵传0
}

message PetBattleResponse_19000012{
}

//激活宠物羁绊
message PetBondsActivateRequest_19000013{
  int32 id = 1; //   SoulPetBook表id
}

//激活宠物羁绊返回，前后端分别加羁绊元宝
message PetBondsActivateResponse_19000014{
}

//升级宠物羁绊
message PetBondsUpLevelRequest_19000015{
  int32 id = 1; //   SoulPetBook表id
}
//升级宠物羁绊返回，前后端分别加羁绊元宝
message PetBondsUpLevelResponse_19000016{
}


// 抽宠物


