syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;
import "ShopMsg.proto" ;
import "BattleMsg.proto" ;
import "QuestMsg.proto";
import "DevelopMsg.proto";
import "FairyFriendMsg.proto";

/*** 登陆****/
message PlayerLoginRequest_01000001{
	string sessionId = 1; //登陆服产生的会话id
	bool reconnect = 2; // 是否是断线重连,true:断线重连，false:普通登陆

	//其他一些和BI相关的参数
	string verstion = 3; // 客户端版本，如果版本不匹配不能登陆（暂时不做这个，只用在bi）
	int32 platform = 20; //平台标示：  1	IOS APP ，2	安卓 APP ，3	IOS小游戏，4	安卓小游戏，5	window 微信小游戏，6	mac微信小游戏
	string adChannel = 30; //推广渠道id 。  IOS广告_小程序_小程序投放 ： 4019392002   android_微信小程序_小程序 ： 2019402002
	string sdkPayChannel = 31; //充值渠道id ：0010安卓充值 ， 0020 IOS充值
	string sdkVersion = 40; //  SDK版本号：小游戏定死为“NULL”
	string system = 41; //  系统: 小游戏定死“system”
	string clue_token = 50; // 目前是在调起微信小程序时调用wx.getLaunchOptionsSync()获取到所有的参数内容并且转成Json字符串。

	//    string deviceId = 25; //设备唯一标识：MAC或者UUID或者IMEI，这里小游戏变为账号id ，即微信的openid
	//    string accountId = 26; //登录账号id，这里是微信的unionid
	// 这两个暂时用不到
	//  int32 accountType = 10; //渠道类型
	//	string sdkDeviceId = 24;
}

/*** 用户登陆,返回游戏数据 ***/
message PlayerLoginResponse_01000002{
	PlayerAllInfo info = 1;					// 用户的所有游戏数据
	bool reconnect = 2;						// 是否是断线重连
	string time = 3;			// 服务器当前时间,毫秒时间戳
}


/*** 退出登陆****/
message PlayerLogoutRequest_01000003{
}

/*** 退出登陆* ***/
message PlayerLogoutResponse_01000004{
}


// 退出登录推送(客户端登录多个账号，或者服务器关闭等)
message PlayerLogoutPush_01100030{
}

/*** 修改名字 **/
message PlayerNameRequest_01000011{
    string name = 1;
}
/*** 修改名字返回 **/
message PlayerNameResponse_01000012{
}
/*** 修改头像 **/
message PlayerHeadRequest_01000013{
    int32 head = 1;
}
/*** 修改头像返回 **/
message PlayerHeadResponse_01000014{
}
/*** 修改头像框 **/
message PlayerHeadFrameRequest_01000015{
    int32 headFrame = 1;
}
/*** 修改头像框返回 **/
message PlayerHeadFrameResponse_01000016{
}


/*** 修改性别 **/
message PlayerGenderRequest_01000017{
    bool isMan = 1;
}
/*** 修改性别返回 **/
message PlayerGenderResponse_01000018{
}

/*** 修改形象 **/
message PlayerImageRequest_01000019{
    int32 image = 1;
}
/*** 修改形象返回 **/
message PlayerImageResponse_0100001a{
}


/*** 断线重连，和手机端通用 **/
message PlayerReconnecRequest_01000065{
    string sessionId = 1;//登陆服产生的会话id
    uint32 playerId = 2;//玩家id
}
/*** 断线重连，和手机端通用 **/
message PlayerReconnecResponse_01000066{
	PlayerAllInfo playerInfo = 1;					// 用户的所有游戏数据
	string time = 2;			// 服务器当前时间,毫秒时间戳

}

/*** 心跳 ****/
message PlayerHeartbeatRequest_01000005{

}
/*** 心跳返回 ****/
message PlayerHeartbeatResponse_01000006{
	string time = 1;			// 服务器当前时间
}


/*** 对于客户端的请求，如果服务器处理过程中出现未知异常，导致没有返回对应的响应包时，返回此错误消息 ****/
message PlayerErrorPush_01000099{
  string error = 1;    //服务端的异常堆栈 
}

// 炼金数据
message AlchemyInfo{
  uint32 configId  = 1; //Alchemy配置表id
  uint32 level = 2;	 	// 炼金等级
}


/*** 产生小云宝箱 推送 ***/
message PlayerCloudBoxPush_01100040{
	CloudBoxInfo cloudBox = 1;
}

/*** 领取小云宝箱奖励 ***/
message PlayerCloudBoxRequest_01000042{
}

message PlayerCloudBoxResponse_01000043{
	repeated RewardInfo rewards = 1;
}
// 小云宝箱
message CloudBoxInfo{
     repeated GoodsInfo items  = 5; // 宝箱里的物品
}

message ExpLevelInfo{
    uint32 id = 1;		//Asset表id,用来区分什么类型的经验或者等级
    uint32 exp = 2;  	//当前经验
    uint32 level = 3;	//当前等级。
}

/*** 如果经验和等级有变化的时候，推送这个协议，客户端用这个数据覆盖本地数据。 ***/
message PlayerExpLevelPush_01100050{
   ExpLevelInfo expLevel = 1;   //
}

/*** 保存新手引导步骤 ***/
message PlayerGuideRequest_01000060{
	uint32 type = 1;  	//类型
    uint32 step = 2;	//该类型下进行到哪一步了
}

message PlayerGuideResponse_01000061{
}

message GuideInfo{
	uint32 type = 1;  	//类型
    uint32 step = 2;	//该类型下进行到哪一步了
}


// 搜索玩家
message PlayerSearchRequest_0100000b{
	// 有id尽量传id，按照id搜，没有id传name按照name搜
	 string playerId = 1;
	 string playerName = 2;
}

//  搜索出来的玩家
message PlayerSearchResponse_0100000c{
   SimplePlayerInfo player = 1;
}


/*** 获取一个玩家的展示数据 ***/
message PlayerShowRequest_01000039{
	// 有id尽量传id，按照id搜，没有id传name按照name搜
	 string playerId = 1;
	 string playerName = 2;
}

message PlayerShowResponse_0100003a{
	// 玩家基本信息SimplePlayerInfo在请求之前应该能获取到，这里就不发了。
	PlayerShowInfo player = 1;
}


//@NotUseStart

/*** 获取一组玩家简略信息 本服 ***/
message PlayerBriefInfoRequest_01000007{
	repeated string playerIds = 1;
}

message PlayerBriefInfoResponse_01000008{
	repeated SimplePlayerInfo players = 1;
}

/*** 获取一组玩家简略信息 查询本服和跨服 ***/
message PlayerBriefInfoOtherRequest_01000009{
	repeated string playerIds = 1;
	repeated string serverIds = 2; // 服id
}

message PlayerBriefInfoOtherResponse_0100000a{
	repeated SimplePlayerInfo players = 1;
}

/*** 炼金请求 ***/
message PlayerAlchemyRequest_01000040{
  uint32 configId  = 1; //Alchemy配置表id
}

message PlayerAlchemyResponse_01000041{
}
/*** 请求巡逻数据，一般是在功能刚开启时请求。  ***/
message PlayerPatrolInfoRequest_01000070{
}

message PlayerPatrolInfoResponse_01000071{
	PatrolInfo patrol = 1;//巡逻/挂机
}

/*** 跨天的时候，通知在线的客户端，重置跨天的一些数据，一般是客户端缓存了的数据，才需要重置。
 客户端在接受到这个协议后可以选择直接重置本地的某些玩法的数据，或者重新请求服务端来刷新数据，具体功能具体分析。
 ****/
message PlayerResetPush_01100016{
	int32 type = 1 ; 	// （这个字段暂时用不到，先保留）1 表示0点的刷新，  2表示5点的刷新（这个字段暂时用不到，先保留）
}
//@NotUseEnd


/*** 请求公告数据 **/
message NoticeRequest_01000050{
}
/*** 公告内容 **/
message NoticeResponse_01000051{
	string notice = 1;
}

/*** 请求红点，判断所有功能红点的状态。 **/
message PlayerRedPointRequest_01000075{
	repeated int32 type = 1;  // InitialUI 表id,功能类型
}
/*** 红点结果 **/
message PlayerRedPointResponse_01000076{
	repeated bool isRed = 1;
}

/*** 请求玩家资产，测试使用，一般用来比对前后端资源，检查资源不同步的操作。  **/
message PlayerAssetDataRequest_01000200{
}
/***  **/
message PlayerAssetDataResponse_01000201{
   map<uint32, uint64> assets = 2;   // 主要是货币，附带一些经验体力等数据。   key:Asset表id
   repeated ItemInfo items  = 5;        //道具  Item表
}


/*** 请求玩家的调查问卷数据  **/
message PlayerQuestionnaireRequest_01000300{
}
/*** 调查问卷数据 **/
message PlayerQuestionnaireResponse_01000301{
   map<uint32, bool> questionnaire = 1;   //当前可以看到的问卷id（Questionnaire表id），和是否领取过的状态。
}

/*** 领取问卷奖励  **/
message PlayerQuestionnaireRewardRequest_01000302{
	uint32 id = 1;  // Questionnaire 表id
}
/***  领取问卷奖励返回 **/
message PlayerQuestionnaireRewardResponse_01000303{
	repeated RewardInfo rewards = 1 ; 			// 获得的奖励
}


// 一次推送多个消息
message PlayerBatchPush_01100100 {
  repeated BatchItem items = 1;
}

message BatchItem {
  int32 msgId = 2;
  bytes payload = 4;
}

//用户基本信息
message PlayerInfo{
    uint32 id = 1;//用户id
    string name = 2;//用户名,昵称
    bool isMan = 3;//性别，是否是男的
    uint32 head = 10;//头像id
    uint32 headFrame = 11;//头像框id
    uint32 image = 12;//形象
	string offlineTime	= 	22;	//上次下线时间的时间戳（毫秒）
}
/*** 玩家所有数据，一般在创建用户后，或者登陆后下发 ***/
message PlayerAllInfo{
   PlayerInfo player = 1;    	// 用户基本信息。
   map<uint32, uint64> assets = 2;   // 主要是货币，附带一些经验体力等数据。   key:Asset表id
   map<uint32, uint64> assetRecover = 3;  // key:Asset表id。一些定时恢复的资源，例如体力，value：上次恢复的时间戳（毫秒）
   map<uint32, uint32> levels = 4;    	//key:Asset表id。 各种等级，比如key要是玩家经验，那value就是玩家等级；如果key是捕鱼玩法的经验，则value是捕鱼玩法的等级。
   repeated ItemInfo items  = 5;        //道具  Item表

//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻养成部分︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻
   repeated HeroFashionInfo fashions = 6;        //所有时装
   repeated HeroInfo heros  = 7;        //英雄 Hero表
   repeated HeroSwordInfo swords = 8;        //所有英雄武器，HeroSword
   string heroSwordUid  = 9;        //当前穿戴的英雄武器唯一id
   repeated GemInfo gems = 10;        //宝石
   repeated EquipInfo equips = 11;        //拥有的装备
   repeated EquipPartInfo equipParts = 12;        //装备部位，1-头盔2-披风3-衣服4-项链5-戒指6-靴子，对应HeroEquip的ItemType。
   map<uint32, uint32> alchemys = 14;        //炼金 key:Alchemy表id value：炼金等级。
   map<uint32, uint32> dragons = 16;    	//龙。 key:Dragon表id。value：龙的星级
   map<uint32, uint32> dragonSkills = 17;   //龙技能。 key:DragonSkill表id。value：技能等级
   QianKunMirrorInfo qianKunMirrorInfo = 19;   // 乾坤镜，灵根淬炼
   repeated FairyFriendInfo fairyFriends = 20;   // 仙友数据
   map<uint32, uint32> fairyFriendFights = 21;   //仙友切磋数据。 key:FairyFriendFight表id。value：状态，1已挑战完， 2已领奖。
   repeated PetInfo pets = 22;   // 宠物数据
   map<uint32, uint32> petBook = 23;   // 宠物羁绊/图鉴数据，key：SoulPetBook表id  value： 图鉴等级
   int32 petBattleId = 26;  // 上阵的宠物id  SoulPet 表id
   repeated SecretscriptInfo secretscript= 27;  // 所有的神通
   map<uint32, uint32> secretscriptPos= 28;  // 神通融汇。key: 神通id value: 位置，1-5

//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼养成部分︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼

   repeated int32 headboxs = 29;  // 玩家拥有的头像框。
   repeated BattleInfo battles = 30;        //打过的战役，包括通关的和非通关的。
   int32 freeRougeTimes = 31; 				// 每日免费肉鸽刷新次数。
//   int32 daoHeartId = 32;					// 当前通关最新的道心磨砺关卡id（DaoHeart）表id
   int32 battleRewardMultipleTimes = 33 ;     // 每天看广告并分享获得多倍战斗奖励的次数。
   int32 shareReliveCount = 34 ;     // 每天分享复活次数。
   int32 adReliveCount = 35 ;     // 每天看广告复活次数。

   repeated MonthCardProto monthCards  = 40;        //月卡
   bool monthCardDoubleBonus = 42 ; 			// 是否可以领取双月卡奖励。
   repeated uint32 chapterPacks  = 41;        //购买过的章节礼包id(ChapterPacks表)
   repeated FundPassInfo fundPass  = 44;        //领过的通行证奖励
   map<uint32, uint32> heishiFreshTimes = 46;        //黑市手动刷新次数,key shop表id
   repeated string freeDayRentHeros = 47;  //免费日租卡的英雄id
   string freeDayRentHeroUid = 49; // 当前选择使用的日租卡英雄唯一id。

   repeated int32 storeStaminas = 48;  //储存的体力时间，秒时间戳

   CloudBoxInfo cloudBox = 50;  // 小云宝箱
   PatrolInfo patrol = 51;//巡逻/挂机
   repeated QuestGroupInfo questGroups = 55 ;  // 任务数据
   repeated QuestGroupPointRewardInfo questGroupPointRewards = 56 ;  // 任务积分奖励领取记录
   bool firstLogin = 57;		// 是否是每天第一次登陆
   map<uint32, uint32> guide = 59;    	//  引导进行到哪一步了。
   int32 heavenlyDaoLevel = 60;        //天道修为等级。HeavenlyDao表id
   map<uint32, uint32> potentialLvMap = 62;    	// 修炼数据，包括潜力和强援，key：属性id value：等级
   map<uint32, bool> potentialBreak = 63;    	// 潜力修炼每xx级需要突破，是否突破了。
   repeated GuideInfo guides = 65;    	// 弃用了。
   int32 battleType = 68 ;     // 已经开始，尚未结束的战斗类型，暂时没有用到。
   int32 battleId = 69 ;     // 已经开始，尚未结束的战斗id，battle 表id
   repeated BattleLineupInfo battleLineups = 70;  // 所有武将阵容。


   //︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻合并游戏独有的数据︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻
   repeated ShopGroupItemInfo shopGroupItems  = 100;        //商店数据
   int32 nextFreeOpenBoxTime  = 101;        //距离下一次看广告免费开宝箱时间(秒)，如果是0表示可以看广告开宝箱
   int32 mergeSweepTimes  = 102;        //当日已经扫荡次数
   repeated MergeEquipmentInfo  mergeEquips = 103; //装备数据
   repeated int32  mergeEquipIds = 104; //安装的装备id
   DayChallengeInfo mergeDayChallenge   = 105; //每日挑战。
   repeated HCHeroInfo hcHeros   = 107; //合成的英雄数据
   string curHcHeroUid = 108;  //当前使用的合成英雄uid
   int32 freeHcHeroUpTimes = 109;  //已经使用过的每日免费看广告升级英雄次数
   int32 freeHcHeroItemTimes = 110;  //已经使用过的每日免费看广告获得英雄升级道具次数
   map<uint32, uint32> freeHcHeroItemTimesMap = 111;   // 每个英雄，已经看过广告获得英雄升级道具的次数，key：HCHero配置表 ID value：次数

   bool battleSpeedUnlock = 112;  //是否已经解锁了战中倍速
   int32 battleSpeedAdsCount = 113;  //如果没有解锁战中倍速，已经看了多少次广告了


//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼合并游戏独有的数据︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
   string disableIosPayVersion  = 200;        //禁用ios充值的客户端版本，一般在提审中使用。
   repeated int32 closeFuncs = 202;  // 关闭的功能列表， FuncOpen表id
   bool shabiyincangguanggao = 250;  // 隐藏广告

}



