syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
import "BaseMsg.proto" ;
import "ShopMsg.proto" ;
import "BattleMsg.proto" ;
import "QuestMsg.proto";

/*** 登陆****/
message PlayerLoginRequest_01000001{
   string sessionId                    = 1;//登陆服产生的会话id
   bool reconnect = 2;						// 是否是断线重连,true:断线重连，false:普通登陆
   string verstion = 3;						// 客户端版本，如果版本不匹配不能登陆

   //其他一些和BI相关的参数
	int32 platform = 20;//平台标示：  1	IOS APP ，2	安卓 APP ，3	IOS小游戏，4	安卓小游戏，5	window 微信小游戏，6	mac微信小游戏
    string adChannel = 30; //推广渠道id
    string sdkPayChannel = 31; //充值渠道id ：0010安卓充值 ， 0020 IOS充值

	string sdkVersion = 40;  //  SDK版本号：小游戏定死为“NULL”
	string system = 41;  //  系统: 小游戏定死“system”

//    string deviceId = 25; //设备唯一标识：MAC或者UUID或者IMEI，这里小游戏变为账号id ，即微信的openid
//    string accountId = 26; //登录账号id，这里是微信的unionid
// 这两个暂时用不到
//  int32 accountType = 10; //渠道类型
//	string sdkDeviceId = 24;
}

/*** 用户登陆,返回游戏数据 ***/
message PlayerLoginResponse_01000002{
	PlayerAllInfo info = 1;					// 用户的所有游戏数据
	bool reconnect = 2;						// 是否是断线重连
	string time = 3;			// 服务器当前时间,毫秒时间戳
}

// 退出登录(客户端登录多个账号，或者服务器关闭等)
message PlayerLogoutPush_01100030{
}

/*** 修改名字 **/
message PlayerNameRequest_01000011{
    string name = 1;
}
/*** 修改名字返回 **/
message PlayerNameResponse_01000012{
}
/*** 修改头像 **/
message PlayerHeadRequest_01000013{
    int32 head = 1;
}
/*** 修改头像返回 **/
message PlayerHeadResponse_01000014{
}
/*** 修改头像框 **/
message PlayerHeadFrameRequest_01000015{
    int32 headFrame = 1;
}
/*** 修改头像框返回 **/
message PlayerHeadFrameResponse_01000016{
}


/*** 修改性别 **/
message PlayerGenderRequest_01000017{
    bool isMan = 1;
}
/*** 修改性别返回 **/
message PlayerGenderResponse_01000018{
}


/*** 断线重连，和手机端通用 **/
message PlayerReconnecRequest_01000065{
    string sessionId = 1;//登陆服产生的会话id
    uint32 playerId = 2;//玩家id
}
/*** 断线重连，和手机端通用 **/
message PlayerReconnecResponse_01000066{
	PlayerAllInfo playerInfo = 1;					// 用户的所有游戏数据
	string time = 2;			// 服务器当前时间,毫秒时间戳

}

/*** 心跳 ****/
message PlayerHeartbeatRequest_01000005{

}
/*** 心跳返回 ****/
message PlayerHeartbeatResponse_01000006{
	string time = 1;			// 服务器当前时间
}

/*** 获取一组玩家简略信息 本服 ***/
message PlayerBriefInfoRequest_01000007{
	repeated string playerIds = 1;
}

message PlayerBriefInfoResponse_01000008{
	repeated SimplePlayerInfo players = 1;
}

/*** 获取一组玩家简略信息 查询本服和跨服 ***/
message PlayerBriefInfoOtherRequest_01000009{
	repeated string playerIds = 1;
	repeated string serverIds = 2; // 服id
}

message PlayerBriefInfoOtherResponse_0100000a{
	repeated SimplePlayerInfo players = 1;
}


/*** 获取一个玩家的名片 ***/
message PlayerShowRequest_01000039{
	string playerId = 1;
	string serverId = 2; // 服id
}

message PlayerShowResponse_0100003a{
	PlayerShowInfo player = 1;
}

/*** 炼金请求 ***/
message PlayerAlchemyRequest_01000040{
  uint32 configId  = 1; //Alchemy配置表id
}

message PlayerAlchemyResponse_01000041{
}

/*** 通知客户端，重置一些本地的数据，大多是一些简单次数之类，对于复杂数据的刷新，通过单独定义协议，服务端推送来刷新 ****/
message PlayerResetPush_01100016{
	int32 type = 1 ; 	// 1 表示12点的刷新，  2表示5点的刷新
}


/*** 对于客户端的请求，如果服务器处理过程中出现未知异常，导致没有返回对应的响应包时，返回此错误消息 ****/
message PlayerErrorPush_01000099{
  string error = 1;    //服务端的异常堆栈 
}

//使用道具
message ItemUseRequest_01000050{
     uint32 id = 1;				//道具ID
     uint32 param = 2;			//使用道具的相关参数，比如道具类型是4时，表示任选英雄，此时设置值为Hero表id
}

// 使用道具后给的资源，道具等。
message ItemUseResponse_01000051{
	 repeated RewardInfo reward  = 1; // 获取的东西
}

// 炼金数据
message AlchemyInfo{
  uint32 configId  = 1; //Alchemy配置表id
  uint32 level = 2;	 	// 炼金等级
}


/*** 产生小云宝箱 推送 ***/
message PlayerCloudBoxPush_01100040{
	CloudBoxInfo cloudBox = 1;
}

/*** 领取小云宝箱奖励 ***/
message PlayerCloudBoxRequest_01000042{
}

message PlayerCloudBoxResponse_01000043{
	repeated RewardInfo rewards = 1;
}
// 小云宝箱
message CloudBoxInfo{
     repeated GoodsInfo items  = 5; // 宝箱里的物品
}

message ExpLevelInfo{
    uint32 id = 1;		//Asset表id,用来区分什么类型的经验或者等级
    uint32 exp = 2;  	//当前经验
    uint32 level = 3;	//当前等级。
}

/*** 如果经验和等级有变化的时候，推送这个协议，客户端用这个数据覆盖本地数据。 ***/
message PlayerExpLevelPush_01100050{
   ExpLevelInfo expLevel = 1;   //
}

//用户基本信息
message PlayerInfo{
    uint32 id = 1;//用户id
    string name = 2;//用户名,昵称
    bool isMan = 3;//性别，是否是男的
    uint32 head = 10;//头像id
    uint32 headFrame = 11;//头像框id
	string offlineTime	= 	22;	//上次下线时间的时间戳（毫秒）
}
/*** 玩家所有数据，一般在创建用户后，或者登陆后下发 ***/
message PlayerAllInfo{
   PlayerInfo player = 1;    	// 用户基本信息。
   map<uint32, uint64> assets = 2;   // 主要是货币，附带一些经验体力等数据。   key:Asset表id
   map<uint32, uint32> assetRecover = 3;    	// key:Asset表id。一些定时恢复的资源，例如体力，value：上次恢复的时间戳（秒）
   map<uint32, uint32> levels = 4;    	//key:Asset表id。 各种等级，比如key要是玩家经验，那value就是玩家等级；如果key是捕鱼玩法的经验，则value是捕鱼玩法的等级。
   repeated ItemInfo items  = 5;        //道具  Item表

//︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻养成部分︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻
   repeated HeroFashionInfo fashions = 6;        //所有时装
   repeated HeroInfo heros  = 7;        //英雄 Hero表
   repeated HeroSwordInfo swords = 8;        //所有英雄武器，HeroSword
   string heroSwordUid  = 9;        //当前穿戴的英雄武器唯一id
   repeated GemInfo gems = 10;        //宝石
   repeated EquipInfo equips = 11;        //拥有的装备
   repeated EquipPartInfo equipParts = 12;        //装备部位，1-头盔2-披风3-衣服4-项链5-戒指6-靴子，对应HeroEquip的ItemType。
   map<uint32, uint32> alchemys = 14;        //炼金 key:Alchemy表id value：炼金等级。
   map<uint32, uint32> dragons = 16;    	//龙。 key:Dragon表id。value：龙的星级
   map<uint32, uint32> dragonSkills = 17;   //龙技能。 key:DragonSkill表id。value：技能等级

//︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼养成部分︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
   repeated BattleInfo battles = 30;        //打过的战役，包括通关的和非通关的。
   int32 freeRougeTimes = 31; 				// 每日免费肉鸽刷新次数。
   int32 daoHeartId = 32;					// 当前通关最新的道心磨砺关卡id（DaoHeart）表id

   repeated MonthCardProto monthCards  = 40;        //月卡
   bool monthCardDoubleBonus = 42 ; 			// 是否可以领取双月卡奖励。
   repeated uint32 chapterPacks  = 41;        //购买过的章节礼包id(ChapterPacks表)
   repeated FundPassInfo fundPass  = 44;        //领过的通行证奖励
   int32 heishiFreshTimes = 46;        //黑市手动刷新次数
   repeated string freeDayRentHeros = 47;  //免费日租卡的英雄id
   repeated int32 storeStaminas = 48;  //储存的体力时间，秒时间戳

   CloudBoxInfo cloudBox = 50;  // 小云宝箱
   PatrolInfo patrol = 51;//巡逻/挂机
   repeated QuestGroupInfo questGroups = 55 ;  // 任务数据
   repeated QuestGroupPointRewardInfo questGroupPointRewards = 56 ;  // 任务积分奖励领取记录
}

