syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;

import "BaseMsg.proto" ;

// 奖励数据，可以包含所有类型的具体奖励，比如角色资源、道具、装备、宝石等类型的数据， 最多只能包含一种,哪个有值加哪个
// 当RewardInfo用在RewardPush_55000501(服务器主动推送) 协议里边时，客户端本地需要增加相关的物品，处理本地数据的更新，不做显示
// 当用在其他返回协议里时，通常既做显示,又更新数据（特殊情况除外，需要客户端服务端针对具体协议做约定）
message RewardInfo{
    AssetInfo asset = 1;		// 资源奖励
	ItemInfo item = 2;			// 道具类型的奖励
    HeroInfo role = 3;		// 英雄奖励
    EquipInfo equip = 7;  //装备奖励
    HeroFashionInfo fashion = 8;  //时装奖励
    GemInfo gem = 9;  //宝石奖励
    DragonInfo dragon = 10;  //龙奖励
    DragonSkillInfo dragonSkill = 11;  //龙技能奖励
    HeroSwordInfo sword = 12;  //武器
    MergeEquipmentInfo mergeEquip = 20;  //合并游戏里面的装备
    HCHeroInfo hcHero = 21;		// 合成英雄奖励
    int32 head = 22;		// 头像框
    PetInfo pet = 25;		// 宠物
    SecretscriptInfo secretscript = 26;		// 神通
}

//奖励推送,客户端收到这个协议之后，将奖励增加到本地。
message RewardPush_55000501{
	repeated RewardInfo rewards = 1;   // 获取的奖励
}

//消耗推送，客户端收到这个协议之后，减少本地的物品
message SpendPush_55001501{
	repeated GoodsInfo spend = 1;   // 消耗的物品
}

//显示奖励推送协议（客户端收到这个协议后，只显示这个奖励，不处理奖励的增加）
// 一般需要显示推送获得的奖励时，看情况使用。
message RewardShowPush_55002501{
	repeated RewardInfo rewards = 1;   // 获取的奖励
}



