syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;

import "BaseMsg.proto" ;

// 奖励数据，可以包含所有类型的具体奖励，比如角色资源，道具等类型的数据， 最多只能包含一种,哪个有值加哪个
// 当RewardInfo用在RewardPush_55000501 协议里边时，代表客户端需要增加相关的物品，需要处理数据的更新，
// 不做显示。当用在其他协议里时，只做显示,不更新数据（特殊情况除外，需要服务端在具体的奖励字段里边标明，
// 需要做数据更新。 ）
message RewardInfo{

	ItemInfo item = 1;			    // 道具类型的奖励
    HeroInfo role = 2;				// 角色奖励
    ResourceInfo resource = 6;		// 资源奖励
    EquipInfo equip = 7;  //装备奖励
}

//奖励推送,客户端收到这个协议之后，将奖励增加到本地。
message RewardPush_55000501{
	repeated RewardInfo rewards = 1;   // 获取的奖励
}

//消耗推送，客户端收到这个协议之后，减少本地的物品
message SpendPush_55001501{
	repeated GoodsInfo goods = 1;   // 消耗的物品
}

//显示奖励推送协议（客户端收到这个协议后，只显示这个奖励，不处理奖励的增加）
// 一般需要显示推送获得的奖励时
message RewardShowPush_55002501{
	repeated RewardInfo rewards = 1;   // 获取的奖励
}



