syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
//import "RewardMsg.proto" ;
//@File 神通相关协议

//@HandlerPackage cn.game.games.net.game.module.develop.secretscript
//@Function Avatar
//@MessageModule 38

//神通升级
message SecretscriptUpLevelRequest_38000003{
  int32 id = 1; // Secretscript表的SecretscriptMark字段。
}

message SecretscriptUpLevelResponse_38000004{
}

//神通突破，合成新神通也用这个
message SecretscriptBreakUpRequest_38000005{
  int32 id = 1; // Secretscript表的SecretscriptMark字段。
}

message SecretscriptBreakUpResponse_38000006{
}


//神通融汇
message SecretscriptFusionRequest_38000007{
  int32 id = 1; // Secretscript表的SecretscriptMark字段。
  int32 pos = 2; // 上阵位置，1-5，如果是0表示下阵
}

message SecretscriptFusionResponse_38000008{
}
//神通融汇 PVP
message SecretscriptFusionPvPRequest_38000011{
    map<int32, int32> secretscriptMap = 1; // 神通PVP 阵容 key  id; value 位置 1-5 0表示下阵
}
message SecretscriptFusionPvPResponse_38000012{
}
