syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "GmMsg.proto" ;
//import "PlayerMsg.proto" ;
// 服务端内部使用的协议

// Game服务器之间的玩家在线状态变更通知,Game-->Game
message GamePlayerOnlinePush_7d000010{
	uint64 playerId = 1;		// 玩家id
	string serverId = 2;		// 玩家所在服务器id
	bool online = 3 ; 			// 是否在线
}

// Game收到推送，将里面的具体消息发给指定的玩家,Game-->Game-->Player
message GamePlayerPush_7d000011{
	uint64 playerId = 1;		// 玩家id
	uint32 id = 2;				// 消息id
	bytes data = 3;				// 消息内容
	uint32 errorCode = 4;		// 消息错误码
}

// Game收到推送，将里面的具体消息发给指定的玩家,Game-->Game-->Player
message GamePlayerPush_7d000100{
	uint64 playerId = 1;		// 玩家id
	uint32 id = 2;				// 消息id
	bytes data = 3;				// 消息内容
	uint32 errorCode = 4;		// 消息错误码
}

// 退出某个玩家
message GamePlayerLogoutRequest_7d000101{
	uint64 playerId = 1;		// 玩家id
}
message GamePlayerLogoutResponse_7d000102{
}

// 测试的
message GameTestRequest_7d000500{
	uint32 id = 1;				// id
}

message GameTestResponse_7d000501{
	uint32 id = 1;				// +1
}

// 获取在线人数等数据
message ServerStatusRequest_7d000901{
}
message ServerStatusResponse_7d000902{
	uint32 online = 1 ;  // 在线人数
}

// 向某个服务器的玩家发送消息让玩家处理
message GamePlayerRequest_7d000015{
	uint64 playerId = 2;		// 接受消息的玩家id
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
}

// 向某个服务器的玩家发送消息让玩家处理，处理后返回
message GamePlayerResponse_7d000016{
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
	uint32 errorCode = 5;		// 消息错误码
}

// 广播服务器在线人数
message GameStatusPublish_7d000017{
	string serverId = 2;		// 服务器id
	uint32 onlinePlayerCount = 3;				// 当前服务器在线人数
}

message LoginPlayerUidRequest_7d000018{
	string passportSessionId = 1;
}
message LoginPlayerUidResponse_7d000019{
	int64 uid = 1;
	string accountId = 2; // unionid
	string deviceId = 3; // openid
}

// 请求创建支付订单
message PaymentOrderCreateRequest_7d000020{
	uint64 playerId = 1; // 玩家id
	string sessionId = 2; //
	uint32 goodsPrice = 4; // 单价（分）
	string itemId = 5; // 道具id
	string platform = 6; // 平台 Android/IOS
}
message PaymentOrderCreateResponse_7d000021{
	// 订单参数
	PaymentOrderProto order = 1;
	uint64 orderId = 3; // 订单唯一id
}
// 通知game，给玩家发货，执行支付后的流程
message PaymentOrderShipRequest_7d000022{
	uint64 playerId = 1; // 玩家id
	uint64 uid = 3; //
}
message PaymentOrderShipResponse_7d000023{
	bool success = 1; //是否发货成功
}


// 请求玩家gm显示数据
message GameGmPlayerInfoRequest_7d000050{
	uint64 playerId = 1; // 玩家id
}
message GameGmPlayerInfoResponse_7d000051{
	GmPlayerInfo player = 1;
}

//game 通知 login 记录gm操作日志
message GmOptRecordRequest_7d000052{
	string optmsg = 1;
	string	opt_param = 2;
	string opt_result = 3;
	string optPid = 4;
}
message GmOptRecordResponse_7d000053{
	bool result = 1;
}

//GM 添加封禁账号请求
message NotifyGmAddForbidAccountRequest_7d000054{
	repeated int64 pids = 1;
	string reason = 2;
	int64 timer = 3;
	int32 type = 4;//封禁类型 0 所有， 1 封禁账号，2 禁言
}
//GM 添加封禁账号响应
message NotifyGmAddForbidAccountResponse_7d000055{
	bool result = 1;
}

//GM 解封账号请求
message NotifyGmDelForbidAccountRequest_7d000056{
	repeated int64 pids = 1;
}
//GM 解封账号响应
message NotifyGmDelForbidAccountResponse_7d000057{
	bool result = 1;
}

//GM  刷新全局gm邮件 请求
message NotifyRefreshGlobalGmMailRequest_7d000058{
}
//GM  刷新全局gm邮件 响应
message NotifyRefreshGlobalGmMailResponse_7d000059{
	bool result = 1;
}

// GM  添加全局gm邮件 请求
message NotifyAddGlobalGmMailRequest_7d000060{
	int32 addGmMailId = 1;
}
// GM  添加全局gm邮件 响应
message NotifyAddGlobalGmMailResponse_7d000061{
	bool result = 1;
}
// GM  删除全局gm邮件 请求
message NotifyDelGlobalGmMailRequest_7d000062{
	int32 delGmMailId = 1;
}
// GM  删除全局gm邮件 响应
message NotifyDelGlobalGmMailResponse_7d000063{
	bool result = 1;
}
//login 通知其他 login 节点 更新IOS 腾讯的 access_token
message LoginUpdateIOSAccessTokenRequest_7d000074{
	string accessToken = 1; //更新的token
	int64 expireTime = 2;  //过期时间
	string jsapi_ticket = 3;//jsapi_ticket  公众号用于调用微信JS接口的临时票据
	int64 tickExpireTime = 4;	//jsapi_ticket 过期时间
}
message LoginUpdateIOSAccessTokenResponse_7d000075{
	bool result = 1;
}


// 问卷调查推送
message LoginGameQuestionnairePush_7d000090{
	int64 playerId = 1;
	int32 type = 2;  // 问卷id
}


// 通知game，改服务器状态
message GameStatusChangeRequest_7d000030{
	int32 status = 1; // 服务器状态
}
message GameStatusChangeResponse_7d000031{
}

// 通知game，关闭或者重启等
message GameOpRequest_7d000373{
	int32 opType = 1; // 1关闭 2重启
}
message GameOpResponse_7d000374{
}


// 清档，一般只在测试时使用。
message LoginPlayerDeleteRequest_7d000080{
	int64 playerId = 1;
}
message LoginPlayerDeleteResponse_7d000081{
}

//login 通知 其他 login 节点 更新 GM 白名单或者 维护公告
message LoginUpdateGmInfoRequest_7d000076{
	int32  type = 1; // 1 更新IP白名单列表， 2 更新维护公告
}
message LoginUpdateGmInfoResponse_7d000077{
	bool result = 1;
}

// 一个测试的协议，这里只使用了消息id，消息的内容由发送时指定，不在proto中定义
message ServerObjectTestRequest_7d000033{
}

message ServerObjectTestResponse_7d000034{
}
// ︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻旧协议，不用了︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻︻

// Game向Cross发数据，请求转发消息给指定玩家
message GameCrossForwardPush_7d000002{
	string serverId  = 1 ;	 	// 服务器id
	uint64 playerId = 2;		// 玩家id
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
	uint32 errorCode = 5;		// 消息错误码
}

// Game收到Cross推送，将里面的具体消息发给指定的玩家
message CrossGameForwardPush_7d000003{
	uint64 playerId = 2;		// 玩家id
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
	uint32 errorCode = 5;		// 消息错误码
	
}

// Game向Cross发数据，将数据包广播给不同Game服务器的玩家
message GameCrossPlayerBroadcast_7d000005{
	repeated string serverId  = 1 ;	 	// 服务器id
	repeated uint64 playerId = 2;		// 玩家id
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
	uint32 errorCode = 5;		// 消息错误码
}

// Game向Cross发数据，将里面的消息广播给指定Game，或者所有Game
message GameCrossBroadcast_7d000008{
	repeated string serverId  = 1 ;	 	// 接收消息的服务器id
	uint32 id = 2;				// 消息id
	bytes data = 3;				// 消息内容
}


// Game向Data发数据，执行数据库操作
message GameDataPush_7d00000a{
	string mapperClass  = 1 ;	 	// Mapper  class
	string method = 2;				// Mapper 里的方法
	bytes arg = 3;				// Mapper 里的参数
}
message DbTaskProto{
	string mapperClass  = 1 ;	 	// Mapper  class
	string method = 2;				// Mapper 里的方法
	bytes arg = 3;				// Mapper 里的参数
}
// Game向Data发数据，执行数据库操作
message GameDataPushBatch_7d00000b{
	repeated DbTaskProto dbTasks = 1;
}
message GameDataPushBatch2_7d00000c{
	bytes arg = 1;				//
}
// ︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼旧协议，不用了︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼︼
