syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "RewardMsg.proto" ;
// 商店、充值 相关协议

//查看商店里面的商品列表
message ShopItemListRequest_15000001{
  uint32 shopId = 1;  // 商店id  Shop表id
}

message ShopItemListResponse_15000002{
	repeated ShopItemProto items = 1;
}

// 商品
message ShopItemProto{
	uint32 itemId = 2; // 商品表ShopItem 表id
	uint32 buyTimes = 3; // 此商品已经购买次数
}

//购买商品
message ShopItemBuyRequest_15000003{
	uint32 shopId = 1; // 商店id  Shop表id
	uint32 itemId = 2; // 商品表ShopItem 表id
}

message ShopItemBuyResponse_15000004{
  repeated RewardInfo rewards = 1;  // 获得的具体物品
}

//手动刷新黑市请求
message ShopHeishiRefreshRequest_15000005{
	int32 shopId = 1;  // 刷新的Shop表id，目前只有类型是2的商店可以手动刷新。
}

message ShopHeishiRefreshResponse_15000006{
	repeated ShopItemProto items = 1;  // 黑市商品
}

//==================================月卡===============================

//购买月卡
message MonthCardBuyRequest_15000010{
  uint32 id = 1; // MonthCard表id
}

message MonthCardBuyResponse_15000011{
	MonthCardProto monthCard = 1;
	repeated RewardInfo rewards = 2;  // 月卡购买奖励

}

//领取月卡购买奖励，每个月卡只能领取一次
message MonthCardBuyRewardRequest_15000012{
  uint32 id = 1; // MonthCard表id
}

message MonthCardBuyRewardResponse_15000013{
}


//领取月卡每日奖励
message MonthCardDayRewardRequest_15000014{
  uint32 id = 1; // MonthCard表id
}

message MonthCardDayRewardResponse_15000015{
}


//领取双月卡一次性奖励
message MonthCardDoubleBonusRequest_15000016{
}

message MonthCardDoubleBonusResponse_15000017{
	  repeated RewardInfo rewards = 1;  // 获得的具体物品
}

message MonthCardProto{
	uint32 id = 1; // MonthCard表id
	uint32 expireTime = 2; // 月卡过期时间（秒时间戳）,0表示不过期
	bool isBuyRewards = 3; // 是否领取了购买奖励
	bool isDayRewards = 4; // 是否领取了每日奖励
}


//==================================礼包===============================

//购买章节礼包
message ShopChapterPacksBuyRequest_15000020{
  uint32 id = 1; // ChapterPacks表id
}

message ShopChapterPacksBuyResponse_15000021{
  repeated RewardInfo rewards = 2;  // 获得的礼包物品
}

// 充值
message ShopRechargeRequest_15000022{
  uint32 id = 1; // Recharge表id
}

message ShopRechargeResponse_15000023{
  repeated RewardInfo rewards = 2;  // 获得的资源
}

// 支付订单相关参数，客户端收到这个协议就可以利用里面的参数发起支付了
message PaymentOrderPush_15010020{
	PaymentOrderProto order = 1;
	string orderId = 2;
}


//==================================通行证===============================
//购买通行证
message ShopFundPassBuyRequest_15000030{
  uint32 id = 1; // FundPass表id
}

message ShopFundPassBuyResponse_15000031{
}

//领取通行证奖励
message ShopFundPassRewardRequest_15000032{
  repeated uint32 id = 1; // FundPassRewards表id
}

message ShopFundPassRewardResponse_15000033{
  repeated RewardInfo rewards = 2;  // 获得的物品
}

// 通行证数据
message FundPassInfo{
  int32 id = 1;  // FundPass表id
  repeated int32 rewardIds = 2;  // FundPassReward表id，已经领取过的奖励id
}

message ShopGroupItemInfo{
	uint32 shopId = 1;  // 商店id  Shop表id
	repeated ShopItemProto items = 2;  // 商品
}

//==================================开宝箱===============================
message ShopBoxOpenRequest_15000040{
  bool watchAds = 1;   // 是看广告开宝箱，还是直接使用钻石开宝箱。
}
message ShopBoxOpenResponse_15000041{
  repeated RewardInfo rewards = 2;  // 获得的物品
}
//==================================现时礼包===============================
message XianShiLiBaoInfo{
	int32 failTimer = 1;//过期时间戳  秒
	int32 groupId = 2;//该组限时礼包的组id
	repeated int32 buyIds = 3;//已经购买过的id
}

//获取现时礼包数据
message GetXianShiLiBaoInfoRequest_15000050{

}
message GetXianShiLiBaoInfoResponse_15000051{
	repeated XianShiLiBaoInfo infos = 1;
}

//购买限时礼包
message BuyXianShiLiBaoRequest_15000052{
	int32 id = 1;//限时礼包的id
}
message BuyXianShiLiBaoResponse_15000053{
	int32 id = 1;//限时礼包的id
	repeated RewardInfo rewards = 2;//购买的物品
	XianShiLiBaoInfo info = 3;//该组礼包信息
}
//解锁新的限时礼包
message NotifyNewXianShiLiBao_15000054{
	XianShiLiBaoInfo info = 1;
}







