syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "BaseMsg.proto" ;
import "RewardMsg.proto" ;
//import "ItemMsg.proto" ;

//@HandlerPackage cn.game.games.net.game.handler
//@MessageModule 6f

// gm指令
message TestGmCmdRequest_6f000001{
	string cmd = 1;  // 指令格式:  指令类型空格参数空格参数。。。不同类型的指令有不同的参数类型和数量 例如：item id 数量
	//具体的指令有：1
	// item 增加物品或者资源 ,参数1 为表id 参数2为数量
}

message TestGmCmdResponse_6f000002{

}

// 获取游戏中的各种物品
message TestAddItemRequest_6f000008{
	uint32 id 	= 1 ;		// 想要获取的奖励id,道具id，或者资源id等
	uint32 count = 2;		// 数量，如果是0，代表本类奖励的所有奖励，装备数量是1，道具数量999，角色数量1，数量设置为0时，id可以不设置具体id，用类型也可以，比如道具是2
}

message TestAddItemResponse_6f000009{
	repeated RewardInfo resource = 1;	// 获得的奖励
}

// 直接完成任务
message TestMissionFinishRequest_6f000022{
	repeated uint32 id 	= 1 ;		// 任务表id，完成多个任务注意任务的先后顺序
}

message TestMissionFinishResponse_6f000023{
	repeated RewardInfo resource = 1;	// 获得的奖励
}


/*** 请求玩家资产，测试使用，一般用来比对前后端资源，检查资源不同步的操作。  **/
message TestPlayerAssetDataRequest_6f000028{
}
/***  **/
message TestPlayerAssetDataResponse_6f000029{
   map<uint32, uint64> assets = 2;   // 主要是货币，附带一些经验体力等数据。   key:Asset表id
   repeated ItemInfo items  = 5;        //道具  Item表
}


// 清空资源和道具
message TestClearResourceAndItemRequest_6f000040{
}

message TestClearResourceAndItemResponse_6f000041{
}

// 将某人退出账号
message TestPlayerLogoutRequest_6f000042{
	uint64 playerId = 1;		// 玩家id
}

message TestPlayerLogoutResponse_6f000043{
}

// 将某人删档
message TestPlayerDeleteRequest_6f000044{
	uint64 playerId = 1;		// 玩家id
}

message TestPlayerDeleteResponse_6f000045{
}

// 只是测试
message TestRequest_6f000020{
	uint32 id 	= 1 ;		//
}

message TestResponse_6f000021{
	uint32 data 	= 1 ;		//

}

//模拟测试某玩家发送协议
message TestMessageRequest_6f000080{
	uint64 playerId = 2;		// 玩家id
	uint32 id = 3;				// 消息id
	bytes data = 4;				// 消息内容
}
message TestMessageResponse_6f000081{

}
//检查一些配置数据。
message TestConfigCheckRequest_6f000090{
}
message TestConfigCheckResponse_6f000091{

}

