syntax = "proto3";
option java_package = "cn.game.protocol.protobuf";
//option optimize_for = LITE_RUNTIME;
package Protos;
import "RewardMsg.proto" ;
//vip 相关
message VipInfo{
  int32 rewardFreeGiftTimer = 1; //免费礼包上一次领取时间戳 每日刷新
  repeated int32 buyGiftIdList = 2; // 已经购买的 一次性购买礼包id集合
  bool canRewardFreeGift = 3; //能否领取当前免费礼包
}

//获取VIP 信息 请求
message getVipInfoRequest_34000001{

}
//获取VIP 信息 返回
message getVipInfoResponse_34000002{
  VipInfo info = 1;//vip 信息
}

//领取每日免费奖励请求
message  rewardFreeVipGiftRequest_34000003{

}
//领取每日免费奖励响应
message  rewardFreeVipGiftResponse_34000004
{
  repeated RewardInfo drops = 1; //获取的奖励
  int32 rewardFreeGiftTimer = 2; //领取的时间戳
}
//购买一次性礼包奖励请求
message buyVipGiftRequest_34000005{
  int32 id = 1;    //要购买的VIP 礼包等级
}
//购买一次性礼包奖励响应
message buyVipGiftResponse_34000006{
  repeated RewardInfo drops = 1; //获取的奖励
  repeated int32  buyGiftIdList = 2; //购买过的id集合
}