<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
	</properties>

	<groupId>cn.game</groupId>
	<artifactId>simulationclient</artifactId>
	<version>1.0</version>


	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<testSourceDirectory>src/test/java</testSourceDirectory>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<!-- <excludes> <exclude>*.*</exclude> </excludes> -->
			</resource>
		</resources>
		<plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.12.1</version> <!-- 确保版本号正确 -->
            <configuration>
                <source>21</source>
                <target>21</target>
            </configuration>
        </plugin>
			<!-- 有的软件打包成bundle格式，需要这个插件 -->
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>
<!--		<plugin>-->
		
<!--    <artifactId>maven-resources-plugin</artifactId>-->
<!--    <executions>-->
<!--        <execution>-->
<!--            <id>copy-resource</id>-->
<!--            <phase>package</phase>-->
<!--            <goals>-->
<!--                <goal>copy-resources</goal>-->
<!--            </goals>-->
<!--            <configuration>-->
<!--                <outputDirectory>D:/apache-jmeter-5.4.1/lib/ext</outputDirectory>-->
<!--                <resources>-->
<!--                    <resource>-->
<!--									 文件地址 -->
<!--                        <directory>${basedir}/target</directory>-->
<!--                        <includes>-->
<!--                            <include>*.jar</include>-->
<!--                        </includes>-->
<!--                    </resource>-->
<!--                </resources>-->
<!--            </configuration>-->
<!--        </execution>-->
<!--    </executions>-->
<!--</plugin>-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<!-- 拷贝项目依赖包到lib/目录下 -->
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<!-- 间接依赖也拷贝 -->
							<excludeTransitive>false</excludeTransitive>
							<!-- 带上版本号 -->
							<stripVersion>false</stripVersion>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		
		
		<pluginManagement>
			<plugins>
			</plugins>
		</pluginManagement>
	</build>

	<dependencies>
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>util</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>cn.game</groupId>
			<artifactId>core</artifactId>
			<version>1.0</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>cn.game</groupId>-->
<!--			<artifactId>game</artifactId>-->
<!--			<version>1.0</version>-->
<!--		</dependency>-->

		<dependency>

			<groupId>org.apache.jmeter</groupId>

			<artifactId>ApacheJMeter_core</artifactId>

			<version>5.4.1</version>

			<exclusions>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>

			<groupId>org.apache.jmeter</groupId>

			<artifactId>ApacheJMeter_java</artifactId>

			<version>5.4.1</version>

		</dependency>


	</dependencies>

</project>