package cn.game.login.cache.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_pay_order
 */
public class PayOrder implements Serializable {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.id
     * @mbg.generated
     */
    private Long id;
    /**
     * Database Column Remarks:
     *   服务器id，不分服不需要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.game_server_id
     * @mbg.generated
     */
    private String gameServerId;
    /**
     * Database Column Remarks:
     *   渠道编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.channel_code
     * @mbg.generated
     */
    private String channelCode;
    /**
     * Database Column Remarks:
     *   渠道名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.channel_label
     * @mbg.generated
     */
    private String channelLabel;
    /**
     * Database Column Remarks:
     *   passport uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.user_id
     * @mbg.generated
     */
    private Long userId;
    /**
     * Database Column Remarks:
     *   某服务器里的玩家唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.player_id
     * @mbg.generated
     */
    private Long playerId;
    /**
     * Database Column Remarks:
     *   例如微信的openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.third_uid
     * @mbg.generated
     */
    private String thirdUid;
    /**
     * Database Column Remarks:
     *   环境配置 0：现网环境（也叫正式环境）1：沙箱环境
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.env
     * @mbg.generated
     */
    private Byte env;
    /**
     * Database Column Remarks:
     *   1未支付 2已支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.pay_state
     * @mbg.generated
     */
    private Byte payState;
    /**
     * Database Column Remarks:
     *   是否已发货
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.is_deliver
     * @mbg.generated
     */
    private Boolean isDeliver;
    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.create_date
     * @mbg.generated
     */
    private String createDate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.create_time
     * @mbg.generated
     */
    private String createTime;
    /**
     * Database Column Remarks:
     *   支付日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.pay_date
     * @mbg.generated
     */
    private String payDate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.pay_time
     * @mbg.generated
     */
    private String payTime;
    /**
     * Database Column Remarks:
     *   完成日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.complete_date
     * @mbg.generated
     */
    private String completeDate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.complete_time
     * @mbg.generated
     */
    private String completeTime;
    /**
     * Database Column Remarks:
     *   调试信息，记录最近的操作描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.debug_text
     * @mbg.generated
     */
    private String debugText;
    /**
     * Database Column Remarks:
     *   玩家支付成功后的回调
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.callback
     * @mbg.generated
     */
    private String callback;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_order
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.id
     *
     * @return the value of t_pay_order.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.id
     *
     * @param id the value for t_pay_order.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.game_server_id
     *
     * @return the value of t_pay_order.game_server_id
     * @mbg.generated
     */
    public String getGameServerId() {
        return gameServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.game_server_id
     *
     * @param gameServerId the value for t_pay_order.game_server_id
     * @mbg.generated
     */
    public void setGameServerId(String gameServerId) {
        this.gameServerId = gameServerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.channel_code
     *
     * @return the value of t_pay_order.channel_code
     * @mbg.generated
     */
    public String getChannelCode() {
        return channelCode;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.channel_code
     *
     * @param channelCode the value for t_pay_order.channel_code
     * @mbg.generated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.channel_label
     *
     * @return the value of t_pay_order.channel_label
     * @mbg.generated
     */
    public String getChannelLabel() {
        return channelLabel;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.channel_label
     *
     * @param channelLabel the value for t_pay_order.channel_label
     * @mbg.generated
     */
    public void setChannelLabel(String channelLabel) {
        this.channelLabel = channelLabel;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.user_id
     *
     * @return the value of t_pay_order.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.user_id
     *
     * @param userId the value for t_pay_order.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.player_id
     *
     * @return the value of t_pay_order.player_id
     * @mbg.generated
     */
    public Long getPlayerId() {
        return playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.player_id
     *
     * @param playerId the value for t_pay_order.player_id
     * @mbg.generated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.third_uid
     *
     * @return the value of t_pay_order.third_uid
     * @mbg.generated
     */
    public String getThirdUid() {
        return thirdUid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.third_uid
     *
     * @param thirdUid the value for t_pay_order.third_uid
     * @mbg.generated
     */
    public void setThirdUid(String thirdUid) {
        this.thirdUid = thirdUid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.env
     *
     * @return the value of t_pay_order.env
     * @mbg.generated
     */
    public Byte getEnv() {
        return env;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.env
     *
     * @param env the value for t_pay_order.env
     * @mbg.generated
     */
    public void setEnv(Byte env) {
        this.env = env;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.pay_state
     *
     * @return the value of t_pay_order.pay_state
     * @mbg.generated
     */
    public Byte getPayState() {
        return payState;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.pay_state
     *
     * @param payState the value for t_pay_order.pay_state
     * @mbg.generated
     */
    public void setPayState(Byte payState) {
        this.payState = payState;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.is_deliver
     *
     * @return the value of t_pay_order.is_deliver
     * @mbg.generated
     */
    public Boolean getIsDeliver() {
        return isDeliver;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.is_deliver
     *
     * @param isDeliver the value for t_pay_order.is_deliver
     * @mbg.generated
     */
    public void setIsDeliver(Boolean isDeliver) {
        this.isDeliver = isDeliver;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.create_date
     *
     * @return the value of t_pay_order.create_date
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.create_date
     *
     * @param createDate the value for t_pay_order.create_date
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.create_time
     *
     * @return the value of t_pay_order.create_time
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.create_time
     *
     * @param createTime the value for t_pay_order.create_time
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.pay_date
     *
     * @return the value of t_pay_order.pay_date
     * @mbg.generated
     */
    public String getPayDate() {
        return payDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.pay_date
     *
     * @param payDate the value for t_pay_order.pay_date
     * @mbg.generated
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.pay_time
     *
     * @return the value of t_pay_order.pay_time
     * @mbg.generated
     */
    public String getPayTime() {
        return payTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.pay_time
     *
     * @param payTime the value for t_pay_order.pay_time
     * @mbg.generated
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.complete_date
     *
     * @return the value of t_pay_order.complete_date
     * @mbg.generated
     */
    public String getCompleteDate() {
        return completeDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.complete_date
     *
     * @param completeDate the value for t_pay_order.complete_date
     * @mbg.generated
     */
    public void setCompleteDate(String completeDate) {
        this.completeDate = completeDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.complete_time
     *
     * @return the value of t_pay_order.complete_time
     * @mbg.generated
     */
    public String getCompleteTime() {
        return completeTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.complete_time
     *
     * @param completeTime the value for t_pay_order.complete_time
     * @mbg.generated
     */
    public void setCompleteTime(String completeTime) {
        this.completeTime = completeTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.debug_text
     *
     * @return the value of t_pay_order.debug_text
     * @mbg.generated
     */
    public String getDebugText() {
        return debugText;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.debug_text
     *
     * @param debugText the value for t_pay_order.debug_text
     * @mbg.generated
     */
    public void setDebugText(String debugText) {
        this.debugText = debugText;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.callback
     *
     * @return the value of t_pay_order.callback
     * @mbg.generated
     */
    public String getCallback() {
        return callback;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.callback
     *
     * @param callback the value for t_pay_order.callback
     * @mbg.generated
     */
    public void setCallback(String callback) {
        this.callback = callback;
    }
}