package cn.game.login.cache.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.pass
	 * @mbg.generated
	 */
	private String pass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.is_gm
	 * @mbg.generated
	 */
	private Integer isGm;
	/**
	 * Database Column Remarks: 1棱镜用户 2渠道用户  3自有用户 4易接 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_type
	 * @mbg.generated
	 */
	private Byte userType;
	/**
	 * Database Column Remarks: 渠道编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.channel_code
	 * @mbg.generated
	 */
	private String channelCode;
	/**
	 * Database Column Remarks: 渠道名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.channel_label
	 * @mbg.generated
	 */
	private String channelLabel;
	/**
	 * Database Column Remarks: 棱镜、渠道用户uid This field was generated by MyBatis Generator. This field corresponds to the database column t_user.third_uid
	 * @mbg.generated
	 */
	private String thirdUid;
	/**
	 * Database Column Remarks: 微信小游戏里面用户登陆后下发的 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.session_key
	 * @mbg.generated
	 */
	private String sessionKey;
	/**
	 * Database Column Remarks: 子渠道 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sub_channel_code
	 * @mbg.generated
	 */
	private String subChannelCode;
	/**
	 * Database Column Remarks: 创建日期 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_date
	 * @mbg.generated
	 */
	private String createDate;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_time
	 * @mbg.generated
	 */
	private String createTime;
	/**
	 * Database Column Remarks: 最后登陆日期 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_date
	 * @mbg.generated
	 */
	private String loginDate;
	/**
	 * Database Column Remarks: 最后登陆时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_time
	 * @mbg.generated
	 */
	private String loginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.device_uid
	 * @mbg.generated
	 */
	private String deviceUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.servers
	 * @mbg.generated
	 */
	private String servers;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.pass
	 * @return  the value of t_user.pass
	 * @mbg.generated
	 */
	public String getPass() {
		return pass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.pass
	 * @param pass  the value for t_user.pass
	 * @mbg.generated
	 */
	public void setPass(String pass) {
		this.pass = pass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.is_gm
	 * @return  the value of t_user.is_gm
	 * @mbg.generated
	 */
	public Integer getIsGm() {
		return isGm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.is_gm
	 * @param isGm  the value for t_user.is_gm
	 * @mbg.generated
	 */
	public void setIsGm(Integer isGm) {
		this.isGm = isGm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_type
	 * @return  the value of t_user.user_type
	 * @mbg.generated
	 */
	public Byte getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_type
	 * @param userType  the value for t_user.user_type
	 * @mbg.generated
	 */
	public void setUserType(Byte userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.channel_code
	 * @return  the value of t_user.channel_code
	 * @mbg.generated
	 */
	public String getChannelCode() {
		return channelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.channel_code
	 * @param channelCode  the value for t_user.channel_code
	 * @mbg.generated
	 */
	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.channel_label
	 * @return  the value of t_user.channel_label
	 * @mbg.generated
	 */
	public String getChannelLabel() {
		return channelLabel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.channel_label
	 * @param channelLabel  the value for t_user.channel_label
	 * @mbg.generated
	 */
	public void setChannelLabel(String channelLabel) {
		this.channelLabel = channelLabel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.third_uid
	 * @return  the value of t_user.third_uid
	 * @mbg.generated
	 */
	public String getThirdUid() {
		return thirdUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.third_uid
	 * @param thirdUid  the value for t_user.third_uid
	 * @mbg.generated
	 */
	public void setThirdUid(String thirdUid) {
		this.thirdUid = thirdUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.session_key
	 * @return  the value of t_user.session_key
	 * @mbg.generated
	 */
	public String getSessionKey() {
		return sessionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.session_key
	 * @param sessionKey  the value for t_user.session_key
	 * @mbg.generated
	 */
	public void setSessionKey(String sessionKey) {
		this.sessionKey = sessionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.sub_channel_code
	 * @return  the value of t_user.sub_channel_code
	 * @mbg.generated
	 */
	public String getSubChannelCode() {
		return subChannelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.sub_channel_code
	 * @param subChannelCode  the value for t_user.sub_channel_code
	 * @mbg.generated
	 */
	public void setSubChannelCode(String subChannelCode) {
		this.subChannelCode = subChannelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_date
	 * @return  the value of t_user.create_date
	 * @mbg.generated
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_date
	 * @param createDate  the value for t_user.create_date
	 * @mbg.generated
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_time
	 * @return  the value of t_user.create_time
	 * @mbg.generated
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_time
	 * @param createTime  the value for t_user.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_date
	 * @return  the value of t_user.login_date
	 * @mbg.generated
	 */
	public String getLoginDate() {
		return loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_date
	 * @param loginDate  the value for t_user.login_date
	 * @mbg.generated
	 */
	public void setLoginDate(String loginDate) {
		this.loginDate = loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_time
	 * @return  the value of t_user.login_time
	 * @mbg.generated
	 */
	public String getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_time
	 * @param loginTime  the value for t_user.login_time
	 * @mbg.generated
	 */
	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.device_uid
	 * @return  the value of t_user.device_uid
	 * @mbg.generated
	 */
	public String getDeviceUid() {
		return deviceUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.device_uid
	 * @param deviceUid  the value for t_user.device_uid
	 * @mbg.generated
	 */
	public void setDeviceUid(String deviceUid) {
		this.deviceUid = deviceUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.servers
	 * @return  the value of t_user.servers
	 * @mbg.generated
	 */
	public String getServers() {
		return servers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.servers
	 * @param servers  the value for t_user.servers
	 * @mbg.generated
	 */
	public void setServers(String servers) {
		this.servers = servers;
	}

}