// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HCCommonMsg.proto

package cn.game.protocol.protobuf;

public final class HCCommonMsg {
  private HCCommonMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HCBattleSpeedAdsRequest_28000020OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HCBattleSpeedAdsRequest_28000020)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *看广告获得战中倍速
   * </pre>
   *
   * Protobuf type {@code Protos.HCBattleSpeedAdsRequest_28000020}
   */
  public static final class HCBattleSpeedAdsRequest_28000020 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HCBattleSpeedAdsRequest_28000020)
      HCBattleSpeedAdsRequest_28000020OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HCBattleSpeedAdsRequest_28000020.newBuilder() to construct.
    private HCBattleSpeedAdsRequest_28000020(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HCBattleSpeedAdsRequest_28000020() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HCBattleSpeedAdsRequest_28000020();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HCBattleSpeedAdsRequest_28000020(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsRequest_28000020_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.class, cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 other = (cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *看广告获得战中倍速
     * </pre>
     *
     * Protobuf type {@code Protos.HCBattleSpeedAdsRequest_28000020}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HCBattleSpeedAdsRequest_28000020)
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsRequest_28000020_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.class, cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 build() {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 buildPartial() {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 result = new cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020) {
          return mergeFrom((cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 other) {
        if (other == cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HCBattleSpeedAdsRequest_28000020)
    }

    // @@protoc_insertion_point(class_scope:Protos.HCBattleSpeedAdsRequest_28000020)
    private static final cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020();
    }

    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HCBattleSpeedAdsRequest_28000020>
        PARSER = new com.google.protobuf.AbstractParser<HCBattleSpeedAdsRequest_28000020>() {
      @java.lang.Override
      public HCBattleSpeedAdsRequest_28000020 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HCBattleSpeedAdsRequest_28000020(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HCBattleSpeedAdsRequest_28000020> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HCBattleSpeedAdsRequest_28000020> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsRequest_28000020 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HCBattleSpeedAdsResponse_28000021OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HCBattleSpeedAdsResponse_28000021)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Protos.HCBattleSpeedAdsResponse_28000021}
   */
  public static final class HCBattleSpeedAdsResponse_28000021 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HCBattleSpeedAdsResponse_28000021)
      HCBattleSpeedAdsResponse_28000021OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HCBattleSpeedAdsResponse_28000021.newBuilder() to construct.
    private HCBattleSpeedAdsResponse_28000021(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HCBattleSpeedAdsResponse_28000021() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HCBattleSpeedAdsResponse_28000021();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HCBattleSpeedAdsResponse_28000021(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsResponse_28000021_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.class, cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 other = (cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.HCBattleSpeedAdsResponse_28000021}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HCBattleSpeedAdsResponse_28000021)
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsResponse_28000021_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.class, cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HCCommonMsg.internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 build() {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 buildPartial() {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 result = new cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021) {
          return mergeFrom((cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 other) {
        if (other == cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HCBattleSpeedAdsResponse_28000021)
    }

    // @@protoc_insertion_point(class_scope:Protos.HCBattleSpeedAdsResponse_28000021)
    private static final cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021();
    }

    public static cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HCBattleSpeedAdsResponse_28000021>
        PARSER = new com.google.protobuf.AbstractParser<HCBattleSpeedAdsResponse_28000021>() {
      @java.lang.Override
      public HCBattleSpeedAdsResponse_28000021 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HCBattleSpeedAdsResponse_28000021(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HCBattleSpeedAdsResponse_28000021> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HCBattleSpeedAdsResponse_28000021> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HCCommonMsg.HCBattleSpeedAdsResponse_28000021 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HCBattleSpeedAdsRequest_28000020_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HCBattleSpeedAdsResponse_28000021_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HCCommonMsg.proto\022\006Protos\"\"\n HCBattleS" +
      "peedAdsRequest_28000020\"#\n!HCBattleSpeed" +
      "AdsResponse_28000021B\033\n\031cn.game.protocol" +
      ".protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_HCBattleSpeedAdsRequest_28000020_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HCBattleSpeedAdsRequest_28000020_descriptor,
        new java.lang.String[] { });
    internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_HCBattleSpeedAdsResponse_28000021_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HCBattleSpeedAdsResponse_28000021_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
