// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeroMsg.proto

package cn.game.protocol.protobuf;

public final class HeroMsg {
  private HeroMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeroUpLevelRequest_16000001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HeroUpLevelRequest_16000001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * <pre>
   *英雄升级
   * </pre>
   *
   * Protobuf type {@code Protos.HeroUpLevelRequest_16000001}
   */
  public static final class HeroUpLevelRequest_16000001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HeroUpLevelRequest_16000001)
      HeroUpLevelRequest_16000001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroUpLevelRequest_16000001.newBuilder() to construct.
    private HeroUpLevelRequest_16000001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroUpLevelRequest_16000001() {
      uid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroUpLevelRequest_16000001();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeroUpLevelRequest_16000001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelRequest_16000001_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelRequest_16000001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.class, cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 other = (cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *英雄升级
     * </pre>
     *
     * Protobuf type {@code Protos.HeroUpLevelRequest_16000001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HeroUpLevelRequest_16000001)
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelRequest_16000001_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelRequest_16000001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.class, cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelRequest_16000001_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 build() {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 buildPartial() {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 result = new cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001) {
          return mergeFrom((cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 other) {
        if (other == cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HeroUpLevelRequest_16000001)
    }

    // @@protoc_insertion_point(class_scope:Protos.HeroUpLevelRequest_16000001)
    private static final cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001();
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroUpLevelRequest_16000001>
        PARSER = new com.google.protobuf.AbstractParser<HeroUpLevelRequest_16000001>() {
      @java.lang.Override
      public HeroUpLevelRequest_16000001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeroUpLevelRequest_16000001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeroUpLevelRequest_16000001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroUpLevelRequest_16000001> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelRequest_16000001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroUpLevelResponse_16000002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HeroUpLevelResponse_16000002)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Protos.HeroUpLevelResponse_16000002}
   */
  public static final class HeroUpLevelResponse_16000002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HeroUpLevelResponse_16000002)
      HeroUpLevelResponse_16000002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroUpLevelResponse_16000002.newBuilder() to construct.
    private HeroUpLevelResponse_16000002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroUpLevelResponse_16000002() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroUpLevelResponse_16000002();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeroUpLevelResponse_16000002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelResponse_16000002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelResponse_16000002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.class, cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 other = (cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.HeroUpLevelResponse_16000002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HeroUpLevelResponse_16000002)
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelResponse_16000002_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelResponse_16000002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.class, cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroUpLevelResponse_16000002_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 build() {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 buildPartial() {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 result = new cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002) {
          return mergeFrom((cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 other) {
        if (other == cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HeroUpLevelResponse_16000002)
    }

    // @@protoc_insertion_point(class_scope:Protos.HeroUpLevelResponse_16000002)
    private static final cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002();
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroUpLevelResponse_16000002>
        PARSER = new com.google.protobuf.AbstractParser<HeroUpLevelResponse_16000002>() {
      @java.lang.Override
      public HeroUpLevelResponse_16000002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeroUpLevelResponse_16000002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeroUpLevelResponse_16000002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroUpLevelResponse_16000002> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HeroMsg.HeroUpLevelResponse_16000002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroConflateRequest_16000003OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HeroConflateRequest_16000003)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 本体英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 本体英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @return A list containing the consumedUid.
     */
    java.util.List<java.lang.String>
        getConsumedUidList();
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @return The count of consumedUid.
     */
    int getConsumedUidCount();
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @param index The index of the element to return.
     * @return The consumedUid at the given index.
     */
    java.lang.String getConsumedUid(int index);
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the consumedUid at the given index.
     */
    com.google.protobuf.ByteString
        getConsumedUidBytes(int index);
  }
  /**
   * <pre>
   *英雄合成
   * </pre>
   *
   * Protobuf type {@code Protos.HeroConflateRequest_16000003}
   */
  public static final class HeroConflateRequest_16000003 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HeroConflateRequest_16000003)
      HeroConflateRequest_16000003OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroConflateRequest_16000003.newBuilder() to construct.
    private HeroConflateRequest_16000003(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroConflateRequest_16000003() {
      uid_ = "";
      consumedUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroConflateRequest_16000003();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeroConflateRequest_16000003(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                consumedUid_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              consumedUid_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          consumedUid_ = consumedUid_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateRequest_16000003_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateRequest_16000003_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.class, cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 本体英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 本体英雄唯一id
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUMEDUID_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList consumedUid_;
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @return A list containing the consumedUid.
     */
    public com.google.protobuf.ProtocolStringList
        getConsumedUidList() {
      return consumedUid_;
    }
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @return The count of consumedUid.
     */
    public int getConsumedUidCount() {
      return consumedUid_.size();
    }
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @param index The index of the element to return.
     * @return The consumedUid at the given index.
     */
    public java.lang.String getConsumedUid(int index) {
      return consumedUid_.get(index);
    }
    /**
     * <pre>
     * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
     * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
     * </pre>
     *
     * <code>repeated string consumedUid = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the consumedUid at the given index.
     */
    public com.google.protobuf.ByteString
        getConsumedUidBytes(int index) {
      return consumedUid_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      for (int i = 0; i < consumedUid_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, consumedUid_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < consumedUid_.size(); i++) {
          dataSize += computeStringSizeNoTag(consumedUid_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getConsumedUidList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 other = (cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getConsumedUidList()
          .equals(other.getConsumedUidList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      if (getConsumedUidCount() > 0) {
        hash = (37 * hash) + CONSUMEDUID_FIELD_NUMBER;
        hash = (53 * hash) + getConsumedUidList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *英雄合成
     * </pre>
     *
     * Protobuf type {@code Protos.HeroConflateRequest_16000003}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HeroConflateRequest_16000003)
        cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateRequest_16000003_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateRequest_16000003_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.class, cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        consumedUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateRequest_16000003_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 build() {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 buildPartial() {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 result = new cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003(this);
        int from_bitField0_ = bitField0_;
        result.uid_ = uid_;
        if (((bitField0_ & 0x00000001) != 0)) {
          consumedUid_ = consumedUid_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.consumedUid_ = consumedUid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003) {
          return mergeFrom((cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 other) {
        if (other == cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.consumedUid_.isEmpty()) {
          if (consumedUid_.isEmpty()) {
            consumedUid_ = other.consumedUid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureConsumedUidIsMutable();
            consumedUid_.addAll(other.consumedUid_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 本体英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 本体英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 本体英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本体英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本体英雄唯一id
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList consumedUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureConsumedUidIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          consumedUid_ = new com.google.protobuf.LazyStringArrayList(consumedUid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @return A list containing the consumedUid.
       */
      public com.google.protobuf.ProtocolStringList
          getConsumedUidList() {
        return consumedUid_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @return The count of consumedUid.
       */
      public int getConsumedUidCount() {
        return consumedUid_.size();
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param index The index of the element to return.
       * @return The consumedUid at the given index.
       */
      public java.lang.String getConsumedUid(int index) {
        return consumedUid_.get(index);
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the consumedUid at the given index.
       */
      public com.google.protobuf.ByteString
          getConsumedUidBytes(int index) {
        return consumedUid_.getByteString(index);
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param index The index to set the value at.
       * @param value The consumedUid to set.
       * @return This builder for chaining.
       */
      public Builder setConsumedUid(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureConsumedUidIsMutable();
        consumedUid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param value The consumedUid to add.
       * @return This builder for chaining.
       */
      public Builder addConsumedUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureConsumedUidIsMutable();
        consumedUid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param values The consumedUid to add.
       * @return This builder for chaining.
       */
      public Builder addAllConsumedUid(
          java.lang.Iterable<java.lang.String> values) {
        ensureConsumedUidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, consumedUid_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumedUid() {
        consumedUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 被消耗的英雄唯一id,注意需要对应HeroConflate表耗材1、2、3的顺序，服务端才能校验
       * 配置了消耗几个耗材，就发几个uid，如果对应的耗材没有，使用了万能耗材，则uid填0
       * </pre>
       *
       * <code>repeated string consumedUid = 2;</code>
       * @param value The bytes of the consumedUid to add.
       * @return This builder for chaining.
       */
      public Builder addConsumedUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureConsumedUidIsMutable();
        consumedUid_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HeroConflateRequest_16000003)
    }

    // @@protoc_insertion_point(class_scope:Protos.HeroConflateRequest_16000003)
    private static final cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003();
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroConflateRequest_16000003>
        PARSER = new com.google.protobuf.AbstractParser<HeroConflateRequest_16000003>() {
      @java.lang.Override
      public HeroConflateRequest_16000003 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeroConflateRequest_16000003(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeroConflateRequest_16000003> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroConflateRequest_16000003> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HeroMsg.HeroConflateRequest_16000003 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroConflateResponse_16000004OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.HeroConflateResponse_16000004)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     * @return Whether the hero field is set.
     */
    boolean hasHero();
    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     * @return The hero.
     */
    cn.game.protocol.protobuf.BaseMsg.HeroInfo getHero();
    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     */
    cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder getHeroOrBuilder();
  }
  /**
   * Protobuf type {@code Protos.HeroConflateResponse_16000004}
   */
  public static final class HeroConflateResponse_16000004 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.HeroConflateResponse_16000004)
      HeroConflateResponse_16000004OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroConflateResponse_16000004.newBuilder() to construct.
    private HeroConflateResponse_16000004(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroConflateResponse_16000004() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroConflateResponse_16000004();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeroConflateResponse_16000004(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder subBuilder = null;
              if (hero_ != null) {
                subBuilder = hero_.toBuilder();
              }
              hero_ = input.readMessage(cn.game.protocol.protobuf.BaseMsg.HeroInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hero_);
                hero_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateResponse_16000004_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateResponse_16000004_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.class, cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.Builder.class);
    }

    public static final int HERO_FIELD_NUMBER = 1;
    private cn.game.protocol.protobuf.BaseMsg.HeroInfo hero_;
    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     * @return Whether the hero field is set.
     */
    @java.lang.Override
    public boolean hasHero() {
      return hero_ != null;
    }
    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     * @return The hero.
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.BaseMsg.HeroInfo getHero() {
      return hero_ == null ? cn.game.protocol.protobuf.BaseMsg.HeroInfo.getDefaultInstance() : hero_;
    }
    /**
     * <pre>
     * 获得新的英雄。
     * </pre>
     *
     * <code>.Protos.HeroInfo hero = 1;</code>
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder getHeroOrBuilder() {
      return getHero();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hero_ != null) {
        output.writeMessage(1, getHero());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hero_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHero());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 other = (cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004) obj;

      if (hasHero() != other.hasHero()) return false;
      if (hasHero()) {
        if (!getHero()
            .equals(other.getHero())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHero()) {
        hash = (37 * hash) + HERO_FIELD_NUMBER;
        hash = (53 * hash) + getHero().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protos.HeroConflateResponse_16000004}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.HeroConflateResponse_16000004)
        cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateResponse_16000004_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateResponse_16000004_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.class, cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (heroBuilder_ == null) {
          hero_ = null;
        } else {
          hero_ = null;
          heroBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HeroMsg.internal_static_Protos_HeroConflateResponse_16000004_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 build() {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 buildPartial() {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 result = new cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004(this);
        if (heroBuilder_ == null) {
          result.hero_ = hero_;
        } else {
          result.hero_ = heroBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004) {
          return mergeFrom((cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 other) {
        if (other == cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004.getDefaultInstance()) return this;
        if (other.hasHero()) {
          mergeHero(other.getHero());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.game.protocol.protobuf.BaseMsg.HeroInfo hero_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.game.protocol.protobuf.BaseMsg.HeroInfo, cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder, cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder> heroBuilder_;
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       * @return Whether the hero field is set.
       */
      public boolean hasHero() {
        return heroBuilder_ != null || hero_ != null;
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       * @return The hero.
       */
      public cn.game.protocol.protobuf.BaseMsg.HeroInfo getHero() {
        if (heroBuilder_ == null) {
          return hero_ == null ? cn.game.protocol.protobuf.BaseMsg.HeroInfo.getDefaultInstance() : hero_;
        } else {
          return heroBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public Builder setHero(cn.game.protocol.protobuf.BaseMsg.HeroInfo value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hero_ = value;
          onChanged();
        } else {
          heroBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public Builder setHero(
          cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder builderForValue) {
        if (heroBuilder_ == null) {
          hero_ = builderForValue.build();
          onChanged();
        } else {
          heroBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public Builder mergeHero(cn.game.protocol.protobuf.BaseMsg.HeroInfo value) {
        if (heroBuilder_ == null) {
          if (hero_ != null) {
            hero_ =
              cn.game.protocol.protobuf.BaseMsg.HeroInfo.newBuilder(hero_).mergeFrom(value).buildPartial();
          } else {
            hero_ = value;
          }
          onChanged();
        } else {
          heroBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public Builder clearHero() {
        if (heroBuilder_ == null) {
          hero_ = null;
          onChanged();
        } else {
          hero_ = null;
          heroBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder getHeroBuilder() {
        
        onChanged();
        return getHeroFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      public cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder getHeroOrBuilder() {
        if (heroBuilder_ != null) {
          return heroBuilder_.getMessageOrBuilder();
        } else {
          return hero_ == null ?
              cn.game.protocol.protobuf.BaseMsg.HeroInfo.getDefaultInstance() : hero_;
        }
      }
      /**
       * <pre>
       * 获得新的英雄。
       * </pre>
       *
       * <code>.Protos.HeroInfo hero = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.game.protocol.protobuf.BaseMsg.HeroInfo, cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder, cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder> 
          getHeroFieldBuilder() {
        if (heroBuilder_ == null) {
          heroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.game.protocol.protobuf.BaseMsg.HeroInfo, cn.game.protocol.protobuf.BaseMsg.HeroInfo.Builder, cn.game.protocol.protobuf.BaseMsg.HeroInfoOrBuilder>(
                  getHero(),
                  getParentForChildren(),
                  isClean());
          hero_ = null;
        }
        return heroBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.HeroConflateResponse_16000004)
    }

    // @@protoc_insertion_point(class_scope:Protos.HeroConflateResponse_16000004)
    private static final cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004();
    }

    public static cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroConflateResponse_16000004>
        PARSER = new com.google.protobuf.AbstractParser<HeroConflateResponse_16000004>() {
      @java.lang.Override
      public HeroConflateResponse_16000004 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeroConflateResponse_16000004(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeroConflateResponse_16000004> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroConflateResponse_16000004> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HeroMsg.HeroConflateResponse_16000004 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HeroUpLevelRequest_16000001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HeroUpLevelRequest_16000001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HeroUpLevelResponse_16000002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HeroUpLevelResponse_16000002_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HeroConflateRequest_16000003_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HeroConflateRequest_16000003_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_HeroConflateResponse_16000004_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_HeroConflateResponse_16000004_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rHeroMsg.proto\022\006Protos\032\rBaseMsg.proto\"*" +
      "\n\033HeroUpLevelRequest_16000001\022\013\n\003uid\030\001 \001" +
      "(\t\"\036\n\034HeroUpLevelResponse_16000002\"@\n\034He" +
      "roConflateRequest_16000003\022\013\n\003uid\030\001 \001(\t\022" +
      "\023\n\013consumedUid\030\002 \003(\t\"?\n\035HeroConflateResp" +
      "onse_16000004\022\036\n\004hero\030\001 \001(\0132\020.Protos.Her" +
      "oInfoB\033\n\031cn.game.protocol.protobufb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.game.protocol.protobuf.BaseMsg.getDescriptor(),
        });
    internal_static_Protos_HeroUpLevelRequest_16000001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_HeroUpLevelRequest_16000001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HeroUpLevelRequest_16000001_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_Protos_HeroUpLevelResponse_16000002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_HeroUpLevelResponse_16000002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HeroUpLevelResponse_16000002_descriptor,
        new java.lang.String[] { });
    internal_static_Protos_HeroConflateRequest_16000003_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protos_HeroConflateRequest_16000003_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HeroConflateRequest_16000003_descriptor,
        new java.lang.String[] { "Uid", "ConsumedUid", });
    internal_static_Protos_HeroConflateResponse_16000004_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Protos_HeroConflateResponse_16000004_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_HeroConflateResponse_16000004_descriptor,
        new java.lang.String[] { "Hero", });
    cn.game.protocol.protobuf.BaseMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
