// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomePageMsg.proto

package cn.game.protocol.protobuf;

public final class HomePageMsg {
  private HomePageMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PosterGirlRequest_35000001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.PosterGirlRequest_35000001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 角色id
     * </pre>
     *
     * <code>int32 roleId = 1;</code>
     * @return The roleId.
     */
    int getRoleId();
  }
  /**
   * <pre>
   *请求设置看板娘
   * </pre>
   *
   * Protobuf type {@code Protos.PosterGirlRequest_35000001}
   */
  public static final class PosterGirlRequest_35000001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.PosterGirlRequest_35000001)
      PosterGirlRequest_35000001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PosterGirlRequest_35000001.newBuilder() to construct.
    private PosterGirlRequest_35000001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PosterGirlRequest_35000001() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PosterGirlRequest_35000001();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PosterGirlRequest_35000001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              roleId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlRequest_35000001_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlRequest_35000001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.class, cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.Builder.class);
    }

    public static final int ROLEID_FIELD_NUMBER = 1;
    private int roleId_;
    /**
     * <pre>
     * 角色id
     * </pre>
     *
     * <code>int32 roleId = 1;</code>
     * @return The roleId.
     */
    @java.lang.Override
    public int getRoleId() {
      return roleId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roleId_ != 0) {
        output.writeInt32(1, roleId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roleId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roleId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 other = (cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001) obj;

      if (getRoleId()
          != other.getRoleId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLEID_FIELD_NUMBER;
      hash = (53 * hash) + getRoleId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求设置看板娘
     * </pre>
     *
     * Protobuf type {@code Protos.PosterGirlRequest_35000001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.PosterGirlRequest_35000001)
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlRequest_35000001_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlRequest_35000001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.class, cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roleId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlRequest_35000001_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 build() {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 buildPartial() {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 result = new cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001(this);
        result.roleId_ = roleId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001) {
          return mergeFrom((cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 other) {
        if (other == cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001.getDefaultInstance()) return this;
        if (other.getRoleId() != 0) {
          setRoleId(other.getRoleId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int roleId_ ;
      /**
       * <pre>
       * 角色id
       * </pre>
       *
       * <code>int32 roleId = 1;</code>
       * @return The roleId.
       */
      @java.lang.Override
      public int getRoleId() {
        return roleId_;
      }
      /**
       * <pre>
       * 角色id
       * </pre>
       *
       * <code>int32 roleId = 1;</code>
       * @param value The roleId to set.
       * @return This builder for chaining.
       */
      public Builder setRoleId(int value) {
        
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色id
       * </pre>
       *
       * <code>int32 roleId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoleId() {
        
        roleId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.PosterGirlRequest_35000001)
    }

    // @@protoc_insertion_point(class_scope:Protos.PosterGirlRequest_35000001)
    private static final cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001();
    }

    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PosterGirlRequest_35000001>
        PARSER = new com.google.protobuf.AbstractParser<PosterGirlRequest_35000001>() {
      @java.lang.Override
      public PosterGirlRequest_35000001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PosterGirlRequest_35000001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PosterGirlRequest_35000001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PosterGirlRequest_35000001> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HomePageMsg.PosterGirlRequest_35000001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PosterGirlResponse_35000002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.PosterGirlResponse_35000002)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *响应设置看板娘结果
   * </pre>
   *
   * Protobuf type {@code Protos.PosterGirlResponse_35000002}
   */
  public static final class PosterGirlResponse_35000002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.PosterGirlResponse_35000002)
      PosterGirlResponse_35000002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PosterGirlResponse_35000002.newBuilder() to construct.
    private PosterGirlResponse_35000002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PosterGirlResponse_35000002() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PosterGirlResponse_35000002();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PosterGirlResponse_35000002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlResponse_35000002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlResponse_35000002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.class, cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 other = (cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应设置看板娘结果
     * </pre>
     *
     * Protobuf type {@code Protos.PosterGirlResponse_35000002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.PosterGirlResponse_35000002)
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlResponse_35000002_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlResponse_35000002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.class, cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.HomePageMsg.internal_static_Protos_PosterGirlResponse_35000002_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 build() {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 buildPartial() {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 result = new cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002) {
          return mergeFrom((cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 other) {
        if (other == cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.PosterGirlResponse_35000002)
    }

    // @@protoc_insertion_point(class_scope:Protos.PosterGirlResponse_35000002)
    private static final cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002();
    }

    public static cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PosterGirlResponse_35000002>
        PARSER = new com.google.protobuf.AbstractParser<PosterGirlResponse_35000002>() {
      @java.lang.Override
      public PosterGirlResponse_35000002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PosterGirlResponse_35000002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PosterGirlResponse_35000002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PosterGirlResponse_35000002> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.HomePageMsg.PosterGirlResponse_35000002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_PosterGirlRequest_35000001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_PosterGirlRequest_35000001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_PosterGirlResponse_35000002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_PosterGirlResponse_35000002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HomePageMsg.proto\022\006Protos\",\n\032PosterGir" +
      "lRequest_35000001\022\016\n\006roleId\030\001 \001(\005\"\035\n\033Pos" +
      "terGirlResponse_35000002B\033\n\031cn.game.prot" +
      "ocol.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protos_PosterGirlRequest_35000001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_PosterGirlRequest_35000001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_PosterGirlRequest_35000001_descriptor,
        new java.lang.String[] { "RoleId", });
    internal_static_Protos_PosterGirlResponse_35000002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_PosterGirlResponse_35000002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_PosterGirlResponse_35000002_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
