// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemMsg.proto

package cn.game.protocol.protobuf;

public final class ItemMsg {
  private ItemMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemUseRequest_0b000003OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.ItemUseRequest_0b000003)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *道具ID（Item表id）
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     *使用数量
     * </pre>
     *
     * <code>uint32 count = 2;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <pre>
     * 道具使用参数，比如当道具的ItemType为4任选英雄道具时，为选择的英雄id
     * </pre>
     *
     * <code>uint32 param = 3;</code>
     * @return The param.
     */
    int getParam();
  }
  /**
   * <pre>
   * 道具相关协议
   *使用道具
   * </pre>
   *
   * Protobuf type {@code Protos.ItemUseRequest_0b000003}
   */
  public static final class ItemUseRequest_0b000003 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.ItemUseRequest_0b000003)
      ItemUseRequest_0b000003OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemUseRequest_0b000003.newBuilder() to construct.
    private ItemUseRequest_0b000003(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemUseRequest_0b000003() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ItemUseRequest_0b000003();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemUseRequest_0b000003(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 16: {

              count_ = input.readUInt32();
              break;
            }
            case 24: {

              param_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseRequest_0b000003_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseRequest_0b000003_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.class, cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *道具ID（Item表id）
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <pre>
     *使用数量
     * </pre>
     *
     * <code>uint32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int PARAM_FIELD_NUMBER = 3;
    private int param_;
    /**
     * <pre>
     * 道具使用参数，比如当道具的ItemType为4任选英雄道具时，为选择的英雄id
     * </pre>
     *
     * <code>uint32 param = 3;</code>
     * @return The param.
     */
    @java.lang.Override
    public int getParam() {
      return param_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (count_ != 0) {
        output.writeUInt32(2, count_);
      }
      if (param_ != 0) {
        output.writeUInt32(3, param_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      if (param_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, param_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 other = (cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003) obj;

      if (getId()
          != other.getId()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (getParam()
          != other.getParam()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 道具相关协议
     *使用道具
     * </pre>
     *
     * Protobuf type {@code Protos.ItemUseRequest_0b000003}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.ItemUseRequest_0b000003)
        cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseRequest_0b000003_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseRequest_0b000003_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.class, cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        count_ = 0;

        param_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseRequest_0b000003_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 build() {
        cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 buildPartial() {
        cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 result = new cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003(this);
        result.id_ = id_;
        result.count_ = count_;
        result.param_ = param_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003) {
          return mergeFrom((cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 other) {
        if (other == cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getParam() != 0) {
          setParam(other.getParam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *道具ID（Item表id）
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *道具ID（Item表id）
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *道具ID（Item表id）
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <pre>
       *使用数量
       * </pre>
       *
       * <code>uint32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <pre>
       *使用数量
       * </pre>
       *
       * <code>uint32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *使用数量
       * </pre>
       *
       * <code>uint32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private int param_ ;
      /**
       * <pre>
       * 道具使用参数，比如当道具的ItemType为4任选英雄道具时，为选择的英雄id
       * </pre>
       *
       * <code>uint32 param = 3;</code>
       * @return The param.
       */
      @java.lang.Override
      public int getParam() {
        return param_;
      }
      /**
       * <pre>
       * 道具使用参数，比如当道具的ItemType为4任选英雄道具时，为选择的英雄id
       * </pre>
       *
       * <code>uint32 param = 3;</code>
       * @param value The param to set.
       * @return This builder for chaining.
       */
      public Builder setParam(int value) {
        
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 道具使用参数，比如当道具的ItemType为4任选英雄道具时，为选择的英雄id
       * </pre>
       *
       * <code>uint32 param = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParam() {
        
        param_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.ItemUseRequest_0b000003)
    }

    // @@protoc_insertion_point(class_scope:Protos.ItemUseRequest_0b000003)
    private static final cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003();
    }

    public static cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemUseRequest_0b000003>
        PARSER = new com.google.protobuf.AbstractParser<ItemUseRequest_0b000003>() {
      @java.lang.Override
      public ItemUseRequest_0b000003 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemUseRequest_0b000003(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemUseRequest_0b000003> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemUseRequest_0b000003> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.ItemMsg.ItemUseRequest_0b000003 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemUseResponse_0b000004OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.ItemUseResponse_0b000004)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> 
        getRewardList();
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    cn.game.protocol.protobuf.RewardMsg.RewardInfo getReward(int index);
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    int getRewardCount();
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
        getRewardOrBuilderList();
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 使用道具后可能会给资源，道具等。
   * </pre>
   *
   * Protobuf type {@code Protos.ItemUseResponse_0b000004}
   */
  public static final class ItemUseResponse_0b000004 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.ItemUseResponse_0b000004)
      ItemUseResponse_0b000004OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemUseResponse_0b000004.newBuilder() to construct.
    private ItemUseResponse_0b000004(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemUseResponse_0b000004() {
      reward_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ItemUseResponse_0b000004();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemUseResponse_0b000004(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                reward_ = new java.util.ArrayList<cn.game.protocol.protobuf.RewardMsg.RewardInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              reward_.add(
                  input.readMessage(cn.game.protocol.protobuf.RewardMsg.RewardInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          reward_ = java.util.Collections.unmodifiableList(reward_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseResponse_0b000004_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseResponse_0b000004_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.class, cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.Builder.class);
    }

    public static final int REWARD_FIELD_NUMBER = 1;
    private java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> reward_;
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    @java.lang.Override
    public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> getRewardList() {
      return reward_;
    }
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
        getRewardOrBuilderList() {
      return reward_;
    }
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    @java.lang.Override
    public int getRewardCount() {
      return reward_.size();
    }
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.RewardMsg.RewardInfo getReward(int index) {
      return reward_.get(index);
    }
    /**
     * <pre>
     * 获取的东西
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo reward = 1;</code>
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardOrBuilder(
        int index) {
      return reward_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < reward_.size(); i++) {
        output.writeMessage(1, reward_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reward_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reward_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 other = (cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004) obj;

      if (!getRewardList()
          .equals(other.getRewardList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRewardCount() > 0) {
        hash = (37 * hash) + REWARD_FIELD_NUMBER;
        hash = (53 * hash) + getRewardList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 使用道具后可能会给资源，道具等。
     * </pre>
     *
     * Protobuf type {@code Protos.ItemUseResponse_0b000004}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.ItemUseResponse_0b000004)
        cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseResponse_0b000004_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseResponse_0b000004_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.class, cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (rewardBuilder_ == null) {
          reward_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rewardBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.ItemMsg.internal_static_Protos_ItemUseResponse_0b000004_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 build() {
        cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 buildPartial() {
        cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 result = new cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004(this);
        int from_bitField0_ = bitField0_;
        if (rewardBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            reward_ = java.util.Collections.unmodifiableList(reward_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reward_ = reward_;
        } else {
          result.reward_ = rewardBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004) {
          return mergeFrom((cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 other) {
        if (other == cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004.getDefaultInstance()) return this;
        if (rewardBuilder_ == null) {
          if (!other.reward_.isEmpty()) {
            if (reward_.isEmpty()) {
              reward_ = other.reward_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRewardIsMutable();
              reward_.addAll(other.reward_);
            }
            onChanged();
          }
        } else {
          if (!other.reward_.isEmpty()) {
            if (rewardBuilder_.isEmpty()) {
              rewardBuilder_.dispose();
              rewardBuilder_ = null;
              reward_ = other.reward_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rewardBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardFieldBuilder() : null;
            } else {
              rewardBuilder_.addAllMessages(other.reward_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> reward_ =
        java.util.Collections.emptyList();
      private void ensureRewardIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          reward_ = new java.util.ArrayList<cn.game.protocol.protobuf.RewardMsg.RewardInfo>(reward_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> rewardBuilder_;

      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> getRewardList() {
        if (rewardBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reward_);
        } else {
          return rewardBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public int getRewardCount() {
        if (rewardBuilder_ == null) {
          return reward_.size();
        } else {
          return rewardBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo getReward(int index) {
        if (rewardBuilder_ == null) {
          return reward_.get(index);
        } else {
          return rewardBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder setReward(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.set(index, value);
          onChanged();
        } else {
          rewardBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder setReward(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder addReward(cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.add(value);
          onChanged();
        } else {
          rewardBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder addReward(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.add(index, value);
          onChanged();
        } else {
          rewardBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder addReward(
          cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.add(builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder addReward(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder addAllReward(
          java.lang.Iterable<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfo> values) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reward_);
          onChanged();
        } else {
          rewardBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder clearReward() {
        if (rewardBuilder_ == null) {
          reward_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rewardBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public Builder removeReward(int index) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.remove(index);
          onChanged();
        } else {
          rewardBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder getRewardBuilder(
          int index) {
        return getRewardFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardOrBuilder(
          int index) {
        if (rewardBuilder_ == null) {
          return reward_.get(index);  } else {
          return rewardBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
           getRewardOrBuilderList() {
        if (rewardBuilder_ != null) {
          return rewardBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reward_);
        }
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder addRewardBuilder() {
        return getRewardFieldBuilder().addBuilder(
            cn.game.protocol.protobuf.RewardMsg.RewardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder addRewardBuilder(
          int index) {
        return getRewardFieldBuilder().addBuilder(
            index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 获取的东西
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo reward = 1;</code>
       */
      public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder> 
           getRewardBuilderList() {
        return getRewardFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
          getRewardFieldBuilder() {
        if (rewardBuilder_ == null) {
          rewardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder>(
                  reward_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          reward_ = null;
        }
        return rewardBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.ItemUseResponse_0b000004)
    }

    // @@protoc_insertion_point(class_scope:Protos.ItemUseResponse_0b000004)
    private static final cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004();
    }

    public static cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemUseResponse_0b000004>
        PARSER = new com.google.protobuf.AbstractParser<ItemUseResponse_0b000004>() {
      @java.lang.Override
      public ItemUseResponse_0b000004 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemUseResponse_0b000004(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemUseResponse_0b000004> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemUseResponse_0b000004> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.ItemMsg.ItemUseResponse_0b000004 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_ItemUseRequest_0b000003_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_ItemUseRequest_0b000003_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_ItemUseResponse_0b000004_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_ItemUseResponse_0b000004_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rItemMsg.proto\022\006Protos\032\017RewardMsg.proto" +
      "\"C\n\027ItemUseRequest_0b000003\022\n\n\002id\030\001 \001(\r\022" +
      "\r\n\005count\030\002 \001(\r\022\r\n\005param\030\003 \001(\r\">\n\030ItemUse" +
      "Response_0b000004\022\"\n\006reward\030\001 \003(\0132\022.Prot" +
      "os.RewardInfoB\033\n\031cn.game.protocol.protob" +
      "ufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.game.protocol.protobuf.RewardMsg.getDescriptor(),
        });
    internal_static_Protos_ItemUseRequest_0b000003_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_ItemUseRequest_0b000003_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_ItemUseRequest_0b000003_descriptor,
        new java.lang.String[] { "Id", "Count", "Param", });
    internal_static_Protos_ItemUseResponse_0b000004_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_ItemUseResponse_0b000004_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_ItemUseResponse_0b000004_descriptor,
        new java.lang.String[] { "Reward", });
    cn.game.protocol.protobuf.RewardMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
