// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignMsg.proto

package cn.game.protocol.protobuf;

public final class SignMsg {
  private SignMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SeeSignRequest_36000001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.SeeSignRequest_36000001)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *请求签到界面
   * </pre>
   *
   * Protobuf type {@code Protos.SeeSignRequest_36000001}
   */
  public static final class SeeSignRequest_36000001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.SeeSignRequest_36000001)
      SeeSignRequest_36000001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SeeSignRequest_36000001.newBuilder() to construct.
    private SeeSignRequest_36000001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SeeSignRequest_36000001() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SeeSignRequest_36000001();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SeeSignRequest_36000001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignRequest_36000001_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignRequest_36000001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.class, cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 other = (cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求签到界面
     * </pre>
     *
     * Protobuf type {@code Protos.SeeSignRequest_36000001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.SeeSignRequest_36000001)
        cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignRequest_36000001_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignRequest_36000001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.class, cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignRequest_36000001_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 build() {
        cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 buildPartial() {
        cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 result = new cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001) {
          return mergeFrom((cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 other) {
        if (other == cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.SeeSignRequest_36000001)
    }

    // @@protoc_insertion_point(class_scope:Protos.SeeSignRequest_36000001)
    private static final cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001();
    }

    public static cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeeSignRequest_36000001>
        PARSER = new com.google.protobuf.AbstractParser<SeeSignRequest_36000001>() {
      @java.lang.Override
      public SeeSignRequest_36000001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SeeSignRequest_36000001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SeeSignRequest_36000001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeeSignRequest_36000001> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.SignMsg.SeeSignRequest_36000001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SeeSignResponse_36000002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.SeeSignResponse_36000002)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *当前时间时间戳(秒)
     * </pre>
     *
     * <code>uint32 nowDay = 1;</code>
     * @return The nowDay.
     */
    int getNowDay();

    /**
     * <pre>
     *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
     * </pre>
     *
     * <code>string signInfo = 2;</code>
     * @return The signInfo.
     */
    java.lang.String getSignInfo();
    /**
     * <pre>
     *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
     * </pre>
     *
     * <code>string signInfo = 2;</code>
     * @return The bytes for signInfo.
     */
    com.google.protobuf.ByteString
        getSignInfoBytes();
  }
  /**
   * <pre>
   *响应签到界面
   * </pre>
   *
   * Protobuf type {@code Protos.SeeSignResponse_36000002}
   */
  public static final class SeeSignResponse_36000002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.SeeSignResponse_36000002)
      SeeSignResponse_36000002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SeeSignResponse_36000002.newBuilder() to construct.
    private SeeSignResponse_36000002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SeeSignResponse_36000002() {
      signInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SeeSignResponse_36000002();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SeeSignResponse_36000002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nowDay_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              signInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignResponse_36000002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignResponse_36000002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.class, cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.Builder.class);
    }

    public static final int NOWDAY_FIELD_NUMBER = 1;
    private int nowDay_;
    /**
     * <pre>
     *当前时间时间戳(秒)
     * </pre>
     *
     * <code>uint32 nowDay = 1;</code>
     * @return The nowDay.
     */
    @java.lang.Override
    public int getNowDay() {
      return nowDay_;
    }

    public static final int SIGNINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object signInfo_;
    /**
     * <pre>
     *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
     * </pre>
     *
     * <code>string signInfo = 2;</code>
     * @return The signInfo.
     */
    @java.lang.Override
    public java.lang.String getSignInfo() {
      java.lang.Object ref = signInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
     * </pre>
     *
     * <code>string signInfo = 2;</code>
     * @return The bytes for signInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignInfoBytes() {
      java.lang.Object ref = signInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nowDay_ != 0) {
        output.writeUInt32(1, nowDay_);
      }
      if (!getSignInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, signInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nowDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, nowDay_);
      }
      if (!getSignInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, signInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 other = (cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002) obj;

      if (getNowDay()
          != other.getNowDay()) return false;
      if (!getSignInfo()
          .equals(other.getSignInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOWDAY_FIELD_NUMBER;
      hash = (53 * hash) + getNowDay();
      hash = (37 * hash) + SIGNINFO_FIELD_NUMBER;
      hash = (53 * hash) + getSignInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应签到界面
     * </pre>
     *
     * Protobuf type {@code Protos.SeeSignResponse_36000002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.SeeSignResponse_36000002)
        cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignResponse_36000002_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignResponse_36000002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.class, cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nowDay_ = 0;

        signInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SeeSignResponse_36000002_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 build() {
        cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 buildPartial() {
        cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 result = new cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002(this);
        result.nowDay_ = nowDay_;
        result.signInfo_ = signInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002) {
          return mergeFrom((cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 other) {
        if (other == cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002.getDefaultInstance()) return this;
        if (other.getNowDay() != 0) {
          setNowDay(other.getNowDay());
        }
        if (!other.getSignInfo().isEmpty()) {
          signInfo_ = other.signInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int nowDay_ ;
      /**
       * <pre>
       *当前时间时间戳(秒)
       * </pre>
       *
       * <code>uint32 nowDay = 1;</code>
       * @return The nowDay.
       */
      @java.lang.Override
      public int getNowDay() {
        return nowDay_;
      }
      /**
       * <pre>
       *当前时间时间戳(秒)
       * </pre>
       *
       * <code>uint32 nowDay = 1;</code>
       * @param value The nowDay to set.
       * @return This builder for chaining.
       */
      public Builder setNowDay(int value) {
        
        nowDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前时间时间戳(秒)
       * </pre>
       *
       * <code>uint32 nowDay = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNowDay() {
        
        nowDay_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object signInfo_ = "";
      /**
       * <pre>
       *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
       * </pre>
       *
       * <code>string signInfo = 2;</code>
       * @return The signInfo.
       */
      public java.lang.String getSignInfo() {
        java.lang.Object ref = signInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
       * </pre>
       *
       * <code>string signInfo = 2;</code>
       * @return The bytes for signInfo.
       */
      public com.google.protobuf.ByteString
          getSignInfoBytes() {
        java.lang.Object ref = signInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
       * </pre>
       *
       * <code>string signInfo = 2;</code>
       * @param value The signInfo to set.
       * @return This builder for chaining.
       */
      public Builder setSignInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
       * </pre>
       *
       * <code>string signInfo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignInfo() {
        
        signInfo_ = getDefaultInstance().getSignInfo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当月每天签到情况，0-&gt;未签到；1-&gt;已签到
       * </pre>
       *
       * <code>string signInfo = 2;</code>
       * @param value The bytes for signInfo to set.
       * @return This builder for chaining.
       */
      public Builder setSignInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.SeeSignResponse_36000002)
    }

    // @@protoc_insertion_point(class_scope:Protos.SeeSignResponse_36000002)
    private static final cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002();
    }

    public static cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeeSignResponse_36000002>
        PARSER = new com.google.protobuf.AbstractParser<SeeSignResponse_36000002>() {
      @java.lang.Override
      public SeeSignResponse_36000002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SeeSignResponse_36000002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SeeSignResponse_36000002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeeSignResponse_36000002> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.SignMsg.SeeSignResponse_36000002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignRequest_36000003OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.SignRequest_36000003)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *签哪一天:2-签2号,31-签31号
     * </pre>
     *
     * <code>uint32 signDay = 1;</code>
     * @return The signDay.
     */
    int getSignDay();
  }
  /**
   * <pre>
   *请求签到
   * </pre>
   *
   * Protobuf type {@code Protos.SignRequest_36000003}
   */
  public static final class SignRequest_36000003 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.SignRequest_36000003)
      SignRequest_36000003OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignRequest_36000003.newBuilder() to construct.
    private SignRequest_36000003(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignRequest_36000003() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignRequest_36000003();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignRequest_36000003(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              signDay_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignRequest_36000003_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignRequest_36000003_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.class, cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.Builder.class);
    }

    public static final int SIGNDAY_FIELD_NUMBER = 1;
    private int signDay_;
    /**
     * <pre>
     *签哪一天:2-签2号,31-签31号
     * </pre>
     *
     * <code>uint32 signDay = 1;</code>
     * @return The signDay.
     */
    @java.lang.Override
    public int getSignDay() {
      return signDay_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signDay_ != 0) {
        output.writeUInt32(1, signDay_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, signDay_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.SignMsg.SignRequest_36000003)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 other = (cn.game.protocol.protobuf.SignMsg.SignRequest_36000003) obj;

      if (getSignDay()
          != other.getSignDay()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNDAY_FIELD_NUMBER;
      hash = (53 * hash) + getSignDay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求签到
     * </pre>
     *
     * Protobuf type {@code Protos.SignRequest_36000003}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.SignRequest_36000003)
        cn.game.protocol.protobuf.SignMsg.SignRequest_36000003OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignRequest_36000003_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignRequest_36000003_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.class, cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signDay_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignRequest_36000003_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 build() {
        cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 buildPartial() {
        cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 result = new cn.game.protocol.protobuf.SignMsg.SignRequest_36000003(this);
        result.signDay_ = signDay_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.SignMsg.SignRequest_36000003) {
          return mergeFrom((cn.game.protocol.protobuf.SignMsg.SignRequest_36000003)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 other) {
        if (other == cn.game.protocol.protobuf.SignMsg.SignRequest_36000003.getDefaultInstance()) return this;
        if (other.getSignDay() != 0) {
          setSignDay(other.getSignDay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.SignMsg.SignRequest_36000003) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int signDay_ ;
      /**
       * <pre>
       *签哪一天:2-签2号,31-签31号
       * </pre>
       *
       * <code>uint32 signDay = 1;</code>
       * @return The signDay.
       */
      @java.lang.Override
      public int getSignDay() {
        return signDay_;
      }
      /**
       * <pre>
       *签哪一天:2-签2号,31-签31号
       * </pre>
       *
       * <code>uint32 signDay = 1;</code>
       * @param value The signDay to set.
       * @return This builder for chaining.
       */
      public Builder setSignDay(int value) {
        
        signDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签哪一天:2-签2号,31-签31号
       * </pre>
       *
       * <code>uint32 signDay = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignDay() {
        
        signDay_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.SignRequest_36000003)
    }

    // @@protoc_insertion_point(class_scope:Protos.SignRequest_36000003)
    private static final cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.SignMsg.SignRequest_36000003();
    }

    public static cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignRequest_36000003>
        PARSER = new com.google.protobuf.AbstractParser<SignRequest_36000003>() {
      @java.lang.Override
      public SignRequest_36000003 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignRequest_36000003(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignRequest_36000003> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignRequest_36000003> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.SignMsg.SignRequest_36000003 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignResponse_36000004OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.SignResponse_36000004)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> 
        getRewardsList();
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    cn.game.protocol.protobuf.RewardMsg.RewardInfo getRewards(int index);
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    int getRewardsCount();
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
        getRewardsOrBuilderList();
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *响应签到
   * </pre>
   *
   * Protobuf type {@code Protos.SignResponse_36000004}
   */
  public static final class SignResponse_36000004 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.SignResponse_36000004)
      SignResponse_36000004OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignResponse_36000004.newBuilder() to construct.
    private SignResponse_36000004(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignResponse_36000004() {
      rewards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignResponse_36000004();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignResponse_36000004(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                rewards_ = new java.util.ArrayList<cn.game.protocol.protobuf.RewardMsg.RewardInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              rewards_.add(
                  input.readMessage(cn.game.protocol.protobuf.RewardMsg.RewardInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          rewards_ = java.util.Collections.unmodifiableList(rewards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignResponse_36000004_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignResponse_36000004_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.class, cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.Builder.class);
    }

    public static final int REWARDS_FIELD_NUMBER = 1;
    private java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> rewards_;
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    @java.lang.Override
    public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> getRewardsList() {
      return rewards_;
    }
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
        getRewardsOrBuilderList() {
      return rewards_;
    }
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    @java.lang.Override
    public int getRewardsCount() {
      return rewards_.size();
    }
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.RewardMsg.RewardInfo getRewards(int index) {
      return rewards_.get(index);
    }
    /**
     * <pre>
     *签到成功奖励
     * </pre>
     *
     * <code>repeated .Protos.RewardInfo rewards = 1;</code>
     */
    @java.lang.Override
    public cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardsOrBuilder(
        int index) {
      return rewards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rewards_.size(); i++) {
        output.writeMessage(1, rewards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rewards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rewards_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.SignMsg.SignResponse_36000004)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 other = (cn.game.protocol.protobuf.SignMsg.SignResponse_36000004) obj;

      if (!getRewardsList()
          .equals(other.getRewardsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRewardsCount() > 0) {
        hash = (37 * hash) + REWARDS_FIELD_NUMBER;
        hash = (53 * hash) + getRewardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应签到
     * </pre>
     *
     * Protobuf type {@code Protos.SignResponse_36000004}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.SignResponse_36000004)
        cn.game.protocol.protobuf.SignMsg.SignResponse_36000004OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignResponse_36000004_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignResponse_36000004_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.class, cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.SignMsg.internal_static_Protos_SignResponse_36000004_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 build() {
        cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 buildPartial() {
        cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 result = new cn.game.protocol.protobuf.SignMsg.SignResponse_36000004(this);
        int from_bitField0_ = bitField0_;
        if (rewardsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rewards_ = java.util.Collections.unmodifiableList(rewards_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rewards_ = rewards_;
        } else {
          result.rewards_ = rewardsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.SignMsg.SignResponse_36000004) {
          return mergeFrom((cn.game.protocol.protobuf.SignMsg.SignResponse_36000004)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 other) {
        if (other == cn.game.protocol.protobuf.SignMsg.SignResponse_36000004.getDefaultInstance()) return this;
        if (rewardsBuilder_ == null) {
          if (!other.rewards_.isEmpty()) {
            if (rewards_.isEmpty()) {
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRewardsIsMutable();
              rewards_.addAll(other.rewards_);
            }
            onChanged();
          }
        } else {
          if (!other.rewards_.isEmpty()) {
            if (rewardsBuilder_.isEmpty()) {
              rewardsBuilder_.dispose();
              rewardsBuilder_ = null;
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rewardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardsFieldBuilder() : null;
            } else {
              rewardsBuilder_.addAllMessages(other.rewards_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.SignMsg.SignResponse_36000004) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> rewards_ =
        java.util.Collections.emptyList();
      private void ensureRewardsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rewards_ = new java.util.ArrayList<cn.game.protocol.protobuf.RewardMsg.RewardInfo>(rewards_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> rewardsBuilder_;

      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo> getRewardsList() {
        if (rewardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rewards_);
        } else {
          return rewardsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public int getRewardsCount() {
        if (rewardsBuilder_ == null) {
          return rewards_.size();
        } else {
          return rewardsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo getRewards(int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);
        } else {
          return rewardsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder setRewards(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.set(index, value);
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder setRewards(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder addRewards(cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder addRewards(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(index, value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder addRewards(
          cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder addRewards(
          int index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder addAllRewards(
          java.lang.Iterable<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfo> values) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rewards_);
          onChanged();
        } else {
          rewardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder clearRewards() {
        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public Builder removeRewards(int index) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.remove(index);
          onChanged();
        } else {
          rewardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder getRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder getRewardsOrBuilder(
          int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);  } else {
          return rewardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public java.util.List<? extends cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
           getRewardsOrBuilderList() {
        if (rewardsBuilder_ != null) {
          return rewardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rewards_);
        }
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder addRewardsBuilder() {
        return getRewardsFieldBuilder().addBuilder(
            cn.game.protocol.protobuf.RewardMsg.RewardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder addRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().addBuilder(
            index, cn.game.protocol.protobuf.RewardMsg.RewardInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *签到成功奖励
       * </pre>
       *
       * <code>repeated .Protos.RewardInfo rewards = 1;</code>
       */
      public java.util.List<cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder> 
           getRewardsBuilderList() {
        return getRewardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder> 
          getRewardsFieldBuilder() {
        if (rewardsBuilder_ == null) {
          rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.game.protocol.protobuf.RewardMsg.RewardInfo, cn.game.protocol.protobuf.RewardMsg.RewardInfo.Builder, cn.game.protocol.protobuf.RewardMsg.RewardInfoOrBuilder>(
                  rewards_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rewards_ = null;
        }
        return rewardsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.SignResponse_36000004)
    }

    // @@protoc_insertion_point(class_scope:Protos.SignResponse_36000004)
    private static final cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.SignMsg.SignResponse_36000004();
    }

    public static cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignResponse_36000004>
        PARSER = new com.google.protobuf.AbstractParser<SignResponse_36000004>() {
      @java.lang.Override
      public SignResponse_36000004 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignResponse_36000004(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignResponse_36000004> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignResponse_36000004> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.SignMsg.SignResponse_36000004 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_SeeSignRequest_36000001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_SeeSignRequest_36000001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_SeeSignResponse_36000002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_SeeSignResponse_36000002_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_SignRequest_36000003_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_SignRequest_36000003_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_SignResponse_36000004_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_SignResponse_36000004_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rSignMsg.proto\022\006Protos\032\017RewardMsg.proto" +
      "\"\031\n\027SeeSignRequest_36000001\"<\n\030SeeSignRe" +
      "sponse_36000002\022\016\n\006nowDay\030\001 \001(\r\022\020\n\010signI" +
      "nfo\030\002 \001(\t\"\'\n\024SignRequest_36000003\022\017\n\007sig" +
      "nDay\030\001 \001(\r\"<\n\025SignResponse_36000004\022#\n\007r" +
      "ewards\030\001 \003(\0132\022.Protos.RewardInfoB\033\n\031cn.g" +
      "ame.protocol.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.game.protocol.protobuf.RewardMsg.getDescriptor(),
        });
    internal_static_Protos_SeeSignRequest_36000001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_SeeSignRequest_36000001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_SeeSignRequest_36000001_descriptor,
        new java.lang.String[] { });
    internal_static_Protos_SeeSignResponse_36000002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_SeeSignResponse_36000002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_SeeSignResponse_36000002_descriptor,
        new java.lang.String[] { "NowDay", "SignInfo", });
    internal_static_Protos_SignRequest_36000003_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protos_SignRequest_36000003_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_SignRequest_36000003_descriptor,
        new java.lang.String[] { "SignDay", });
    internal_static_Protos_SignResponse_36000004_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Protos_SignResponse_36000004_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_SignResponse_36000004_descriptor,
        new java.lang.String[] { "Rewards", });
    cn.game.protocol.protobuf.RewardMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
