// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreNpcMsg.proto

package cn.game.protocol.protobuf;

public final class StoreNpcMsg {
  private StoreNpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 气泡枚举类型
   * </pre>
   *
   * Protobuf enum {@code Protos.BubbleType}
   */
  public enum BubbleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *每日气泡
     * </pre>
     *
     * <code>EVERY_DAY = 0;</code>
     */
    EVERY_DAY(0),
    /**
     * <pre>
     *等级气泡
     * </pre>
     *
     * <code>LEVEL = 1;</code>
     */
    LEVEL(1),
    /**
     * <pre>
     *爱心气泡
     * </pre>
     *
     * <code>LOVE = 2;</code>
     */
    LOVE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *每日气泡
     * </pre>
     *
     * <code>EVERY_DAY = 0;</code>
     */
    public static final int EVERY_DAY_VALUE = 0;
    /**
     * <pre>
     *等级气泡
     * </pre>
     *
     * <code>LEVEL = 1;</code>
     */
    public static final int LEVEL_VALUE = 1;
    /**
     * <pre>
     *爱心气泡
     * </pre>
     *
     * <code>LOVE = 2;</code>
     */
    public static final int LOVE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BubbleType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BubbleType forNumber(int value) {
      switch (value) {
        case 0: return EVERY_DAY;
        case 1: return LEVEL;
        case 2: return LOVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BubbleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BubbleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BubbleType>() {
            public BubbleType findValueByNumber(int number) {
              return BubbleType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.StoreNpcMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final BubbleType[] VALUES = values();

    public static BubbleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BubbleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Protos.BubbleType)
  }

  public interface StoreNpcClickBubbleRequest_50000001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.StoreNpcClickBubbleRequest_50000001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *气泡枚举类型
     * </pre>
     *
     * <code>.Protos.BubbleType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *气泡枚举类型
     * </pre>
     *
     * <code>.Protos.BubbleType type = 1;</code>
     * @return The type.
     */
    cn.game.protocol.protobuf.StoreNpcMsg.BubbleType getType();
  }
  /**
   * <pre>
   * 点击气泡获取好感值
   * </pre>
   *
   * Protobuf type {@code Protos.StoreNpcClickBubbleRequest_50000001}
   */
  public static final class StoreNpcClickBubbleRequest_50000001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.StoreNpcClickBubbleRequest_50000001)
      StoreNpcClickBubbleRequest_50000001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreNpcClickBubbleRequest_50000001.newBuilder() to construct.
    private StoreNpcClickBubbleRequest_50000001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreNpcClickBubbleRequest_50000001() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoreNpcClickBubbleRequest_50000001();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreNpcClickBubbleRequest_50000001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleRequest_50000001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *气泡枚举类型
     * </pre>
     *
     * <code>.Protos.BubbleType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *气泡枚举类型
     * </pre>
     *
     * <code>.Protos.BubbleType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public cn.game.protocol.protobuf.StoreNpcMsg.BubbleType getType() {
      @SuppressWarnings("deprecation")
      cn.game.protocol.protobuf.StoreNpcMsg.BubbleType result = cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.valueOf(type_);
      return result == null ? cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.EVERY_DAY.getNumber()) {
        output.writeEnum(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.EVERY_DAY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 other = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001) obj;

      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 点击气泡获取好感值
     * </pre>
     *
     * Protobuf type {@code Protos.StoreNpcClickBubbleRequest_50000001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.StoreNpcClickBubbleRequest_50000001)
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleRequest_50000001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 build() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 buildPartial() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 result = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001) {
          return mergeFrom((cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 other) {
        if (other == cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *气泡枚举类型
       * </pre>
       *
       * <code>.Protos.BubbleType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *气泡枚举类型
       * </pre>
       *
       * <code>.Protos.BubbleType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *气泡枚举类型
       * </pre>
       *
       * <code>.Protos.BubbleType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.BubbleType getType() {
        @SuppressWarnings("deprecation")
        cn.game.protocol.protobuf.StoreNpcMsg.BubbleType result = cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.valueOf(type_);
        return result == null ? cn.game.protocol.protobuf.StoreNpcMsg.BubbleType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *气泡枚举类型
       * </pre>
       *
       * <code>.Protos.BubbleType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cn.game.protocol.protobuf.StoreNpcMsg.BubbleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *气泡枚举类型
       * </pre>
       *
       * <code>.Protos.BubbleType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.StoreNpcClickBubbleRequest_50000001)
    }

    // @@protoc_insertion_point(class_scope:Protos.StoreNpcClickBubbleRequest_50000001)
    private static final cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001();
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreNpcClickBubbleRequest_50000001>
        PARSER = new com.google.protobuf.AbstractParser<StoreNpcClickBubbleRequest_50000001>() {
      @java.lang.Override
      public StoreNpcClickBubbleRequest_50000001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoreNpcClickBubbleRequest_50000001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreNpcClickBubbleRequest_50000001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreNpcClickBubbleRequest_50000001> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleRequest_50000001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StoreNpcClickBubbleResponse_50000002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.StoreNpcClickBubbleResponse_50000002)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *好感等级
     * </pre>
     *
     * <code>uint32 favorabilityLv = 1;</code>
     * @return The favorabilityLv.
     */
    int getFavorabilityLv();

    /**
     * <pre>
     *好感值
     * </pre>
     *
     * <code>uint32 favorabilityExp = 2;</code>
     * @return The favorabilityExp.
     */
    int getFavorabilityExp();
  }
  /**
   * <pre>
   * 服务器返回获取好感值回馈 更新
   * </pre>
   *
   * Protobuf type {@code Protos.StoreNpcClickBubbleResponse_50000002}
   */
  public static final class StoreNpcClickBubbleResponse_50000002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.StoreNpcClickBubbleResponse_50000002)
      StoreNpcClickBubbleResponse_50000002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreNpcClickBubbleResponse_50000002.newBuilder() to construct.
    private StoreNpcClickBubbleResponse_50000002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreNpcClickBubbleResponse_50000002() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoreNpcClickBubbleResponse_50000002();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreNpcClickBubbleResponse_50000002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              favorabilityLv_ = input.readUInt32();
              break;
            }
            case 16: {

              favorabilityExp_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleResponse_50000002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.Builder.class);
    }

    public static final int FAVORABILITYLV_FIELD_NUMBER = 1;
    private int favorabilityLv_;
    /**
     * <pre>
     *好感等级
     * </pre>
     *
     * <code>uint32 favorabilityLv = 1;</code>
     * @return The favorabilityLv.
     */
    @java.lang.Override
    public int getFavorabilityLv() {
      return favorabilityLv_;
    }

    public static final int FAVORABILITYEXP_FIELD_NUMBER = 2;
    private int favorabilityExp_;
    /**
     * <pre>
     *好感值
     * </pre>
     *
     * <code>uint32 favorabilityExp = 2;</code>
     * @return The favorabilityExp.
     */
    @java.lang.Override
    public int getFavorabilityExp() {
      return favorabilityExp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (favorabilityLv_ != 0) {
        output.writeUInt32(1, favorabilityLv_);
      }
      if (favorabilityExp_ != 0) {
        output.writeUInt32(2, favorabilityExp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (favorabilityLv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, favorabilityLv_);
      }
      if (favorabilityExp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, favorabilityExp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 other = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002) obj;

      if (getFavorabilityLv()
          != other.getFavorabilityLv()) return false;
      if (getFavorabilityExp()
          != other.getFavorabilityExp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FAVORABILITYLV_FIELD_NUMBER;
      hash = (53 * hash) + getFavorabilityLv();
      hash = (37 * hash) + FAVORABILITYEXP_FIELD_NUMBER;
      hash = (53 * hash) + getFavorabilityExp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务器返回获取好感值回馈 更新
     * </pre>
     *
     * Protobuf type {@code Protos.StoreNpcClickBubbleResponse_50000002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.StoreNpcClickBubbleResponse_50000002)
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleResponse_50000002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        favorabilityLv_ = 0;

        favorabilityExp_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 build() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 buildPartial() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 result = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002(this);
        result.favorabilityLv_ = favorabilityLv_;
        result.favorabilityExp_ = favorabilityExp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002) {
          return mergeFrom((cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 other) {
        if (other == cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002.getDefaultInstance()) return this;
        if (other.getFavorabilityLv() != 0) {
          setFavorabilityLv(other.getFavorabilityLv());
        }
        if (other.getFavorabilityExp() != 0) {
          setFavorabilityExp(other.getFavorabilityExp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int favorabilityLv_ ;
      /**
       * <pre>
       *好感等级
       * </pre>
       *
       * <code>uint32 favorabilityLv = 1;</code>
       * @return The favorabilityLv.
       */
      @java.lang.Override
      public int getFavorabilityLv() {
        return favorabilityLv_;
      }
      /**
       * <pre>
       *好感等级
       * </pre>
       *
       * <code>uint32 favorabilityLv = 1;</code>
       * @param value The favorabilityLv to set.
       * @return This builder for chaining.
       */
      public Builder setFavorabilityLv(int value) {
        
        favorabilityLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *好感等级
       * </pre>
       *
       * <code>uint32 favorabilityLv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFavorabilityLv() {
        
        favorabilityLv_ = 0;
        onChanged();
        return this;
      }

      private int favorabilityExp_ ;
      /**
       * <pre>
       *好感值
       * </pre>
       *
       * <code>uint32 favorabilityExp = 2;</code>
       * @return The favorabilityExp.
       */
      @java.lang.Override
      public int getFavorabilityExp() {
        return favorabilityExp_;
      }
      /**
       * <pre>
       *好感值
       * </pre>
       *
       * <code>uint32 favorabilityExp = 2;</code>
       * @param value The favorabilityExp to set.
       * @return This builder for chaining.
       */
      public Builder setFavorabilityExp(int value) {
        
        favorabilityExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *好感值
       * </pre>
       *
       * <code>uint32 favorabilityExp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFavorabilityExp() {
        
        favorabilityExp_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.StoreNpcClickBubbleResponse_50000002)
    }

    // @@protoc_insertion_point(class_scope:Protos.StoreNpcClickBubbleResponse_50000002)
    private static final cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002();
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreNpcClickBubbleResponse_50000002>
        PARSER = new com.google.protobuf.AbstractParser<StoreNpcClickBubbleResponse_50000002>() {
      @java.lang.Override
      public StoreNpcClickBubbleResponse_50000002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoreNpcClickBubbleResponse_50000002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreNpcClickBubbleResponse_50000002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreNpcClickBubbleResponse_50000002> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcClickBubbleResponse_50000002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StoreNpcInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protos.StoreNpcInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *已经获取的等级气泡 的最后一个等级 
     * </pre>
     *
     * <code>uint32 overRewardLv = 1;</code>
     * @return The overRewardLv.
     */
    int getOverRewardLv();

    /**
     * <pre>
     * 每日奖励领取次数
     * </pre>
     *
     * <code>uint32 everyCount = 2;</code>
     * @return The everyCount.
     */
    int getEveryCount();

    /**
     * <pre>
     * 爱心领取次数
     * </pre>
     *
     * <code>uint32 loveCount = 3;</code>
     * @return The loveCount.
     */
    int getLoveCount();
  }
  /**
   * <pre>
   * 登录时同步此结构
   * </pre>
   *
   * Protobuf type {@code Protos.StoreNpcInfo}
   */
  public static final class StoreNpcInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protos.StoreNpcInfo)
      StoreNpcInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreNpcInfo.newBuilder() to construct.
    private StoreNpcInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreNpcInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoreNpcInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreNpcInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              overRewardLv_ = input.readUInt32();
              break;
            }
            case 16: {

              everyCount_ = input.readUInt32();
              break;
            }
            case 24: {

              loveCount_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.Builder.class);
    }

    public static final int OVERREWARDLV_FIELD_NUMBER = 1;
    private int overRewardLv_;
    /**
     * <pre>
     *已经获取的等级气泡 的最后一个等级 
     * </pre>
     *
     * <code>uint32 overRewardLv = 1;</code>
     * @return The overRewardLv.
     */
    @java.lang.Override
    public int getOverRewardLv() {
      return overRewardLv_;
    }

    public static final int EVERYCOUNT_FIELD_NUMBER = 2;
    private int everyCount_;
    /**
     * <pre>
     * 每日奖励领取次数
     * </pre>
     *
     * <code>uint32 everyCount = 2;</code>
     * @return The everyCount.
     */
    @java.lang.Override
    public int getEveryCount() {
      return everyCount_;
    }

    public static final int LOVECOUNT_FIELD_NUMBER = 3;
    private int loveCount_;
    /**
     * <pre>
     * 爱心领取次数
     * </pre>
     *
     * <code>uint32 loveCount = 3;</code>
     * @return The loveCount.
     */
    @java.lang.Override
    public int getLoveCount() {
      return loveCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (overRewardLv_ != 0) {
        output.writeUInt32(1, overRewardLv_);
      }
      if (everyCount_ != 0) {
        output.writeUInt32(2, everyCount_);
      }
      if (loveCount_ != 0) {
        output.writeUInt32(3, loveCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (overRewardLv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, overRewardLv_);
      }
      if (everyCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, everyCount_);
      }
      if (loveCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, loveCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo)) {
        return super.equals(obj);
      }
      cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo other = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo) obj;

      if (getOverRewardLv()
          != other.getOverRewardLv()) return false;
      if (getEveryCount()
          != other.getEveryCount()) return false;
      if (getLoveCount()
          != other.getLoveCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OVERREWARDLV_FIELD_NUMBER;
      hash = (53 * hash) + getOverRewardLv();
      hash = (37 * hash) + EVERYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getEveryCount();
      hash = (37 * hash) + LOVECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getLoveCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 登录时同步此结构
     * </pre>
     *
     * Protobuf type {@code Protos.StoreNpcInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protos.StoreNpcInfo)
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.class, cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.Builder.class);
      }

      // Construct using cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        overRewardLv_ = 0;

        everyCount_ = 0;

        loveCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.internal_static_Protos_StoreNpcInfo_descriptor;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo getDefaultInstanceForType() {
        return cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo build() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo buildPartial() {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo result = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo(this);
        result.overRewardLv_ = overRewardLv_;
        result.everyCount_ = everyCount_;
        result.loveCount_ = loveCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo) {
          return mergeFrom((cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo other) {
        if (other == cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo.getDefaultInstance()) return this;
        if (other.getOverRewardLv() != 0) {
          setOverRewardLv(other.getOverRewardLv());
        }
        if (other.getEveryCount() != 0) {
          setEveryCount(other.getEveryCount());
        }
        if (other.getLoveCount() != 0) {
          setLoveCount(other.getLoveCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int overRewardLv_ ;
      /**
       * <pre>
       *已经获取的等级气泡 的最后一个等级 
       * </pre>
       *
       * <code>uint32 overRewardLv = 1;</code>
       * @return The overRewardLv.
       */
      @java.lang.Override
      public int getOverRewardLv() {
        return overRewardLv_;
      }
      /**
       * <pre>
       *已经获取的等级气泡 的最后一个等级 
       * </pre>
       *
       * <code>uint32 overRewardLv = 1;</code>
       * @param value The overRewardLv to set.
       * @return This builder for chaining.
       */
      public Builder setOverRewardLv(int value) {
        
        overRewardLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已经获取的等级气泡 的最后一个等级 
       * </pre>
       *
       * <code>uint32 overRewardLv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOverRewardLv() {
        
        overRewardLv_ = 0;
        onChanged();
        return this;
      }

      private int everyCount_ ;
      /**
       * <pre>
       * 每日奖励领取次数
       * </pre>
       *
       * <code>uint32 everyCount = 2;</code>
       * @return The everyCount.
       */
      @java.lang.Override
      public int getEveryCount() {
        return everyCount_;
      }
      /**
       * <pre>
       * 每日奖励领取次数
       * </pre>
       *
       * <code>uint32 everyCount = 2;</code>
       * @param value The everyCount to set.
       * @return This builder for chaining.
       */
      public Builder setEveryCount(int value) {
        
        everyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每日奖励领取次数
       * </pre>
       *
       * <code>uint32 everyCount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEveryCount() {
        
        everyCount_ = 0;
        onChanged();
        return this;
      }

      private int loveCount_ ;
      /**
       * <pre>
       * 爱心领取次数
       * </pre>
       *
       * <code>uint32 loveCount = 3;</code>
       * @return The loveCount.
       */
      @java.lang.Override
      public int getLoveCount() {
        return loveCount_;
      }
      /**
       * <pre>
       * 爱心领取次数
       * </pre>
       *
       * <code>uint32 loveCount = 3;</code>
       * @param value The loveCount to set.
       * @return This builder for chaining.
       */
      public Builder setLoveCount(int value) {
        
        loveCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 爱心领取次数
       * </pre>
       *
       * <code>uint32 loveCount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoveCount() {
        
        loveCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protos.StoreNpcInfo)
    }

    // @@protoc_insertion_point(class_scope:Protos.StoreNpcInfo)
    private static final cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo();
    }

    public static cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreNpcInfo>
        PARSER = new com.google.protobuf.AbstractParser<StoreNpcInfo>() {
      @java.lang.Override
      public StoreNpcInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoreNpcInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreNpcInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreNpcInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.game.protocol.protobuf.StoreNpcMsg.StoreNpcInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_StoreNpcClickBubbleRequest_50000001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_StoreNpcClickBubbleResponse_50000002_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protos_StoreNpcInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protos_StoreNpcInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021StoreNpcMsg.proto\022\006Protos\"G\n#StoreNpcC" +
      "lickBubbleRequest_50000001\022 \n\004type\030\001 \001(\016" +
      "2\022.Protos.BubbleType\"W\n$StoreNpcClickBub" +
      "bleResponse_50000002\022\026\n\016favorabilityLv\030\001" +
      " \001(\r\022\027\n\017favorabilityExp\030\002 \001(\r\"K\n\014StoreNp" +
      "cInfo\022\024\n\014overRewardLv\030\001 \001(\r\022\022\n\neveryCoun" +
      "t\030\002 \001(\r\022\021\n\tloveCount\030\003 \001(\r*0\n\nBubbleType" +
      "\022\r\n\tEVERY_DAY\020\000\022\t\n\005LEVEL\020\001\022\010\n\004LOVE\020\002B\033\n\031" +
      "cn.game.protocol.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protos_StoreNpcClickBubbleRequest_50000001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_StoreNpcClickBubbleRequest_50000001_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protos_StoreNpcClickBubbleResponse_50000002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_StoreNpcClickBubbleResponse_50000002_descriptor,
        new java.lang.String[] { "FavorabilityLv", "FavorabilityExp", });
    internal_static_Protos_StoreNpcInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protos_StoreNpcInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protos_StoreNpcInfo_descriptor,
        new java.lang.String[] { "OverRewardLv", "EveryCount", "LoveCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
