<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  
  <parent>
    <groupId>cn.game</groupId>
    <artifactId>server</artifactId>
    <version>1.0</version>
  </parent>
  <artifactId>core</artifactId>
  <name>core</name>
  <url>http://maven.apache.org</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
  
	<dependency>
		<groupId>cn.game</groupId>
		<artifactId>util</artifactId>
	</dependency>
	
	<dependency>
		<groupId>cn.game</groupId>
		<artifactId>protocol</artifactId>
	</dependency>
		
  </dependencies>
</project>
