package cn.game.login.mapper;

import cn.game.login.cache.entity.PayOrder;

public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int insert(PayOrder row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int insertSelective(PayOrder row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int insertOrUpdate(PayOrder row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    PayOrder selectByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayOrder row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayOrder row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     * @mbg.generated
     */
    int updateByPrimaryKey(PayOrder row);
}