package cn.game.login.mapper;

import java.util.List;

import cn.game.core.base.ServerList;


public interface ServerListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String scenseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	int insert(ServerList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	int insertSelective(ServerList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	ServerList selectByPrimaryKey(String scenseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ServerList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_scense_server_list
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ServerList record);


	List<ServerList> selectAll() ; 

	
}