package cn.game.login.mapper;

import java.util.HashMap;

import org.apache.ibatis.annotations.Param;

import cn.game.login.cache.entity.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int insertOrUpdate(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	User selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(User row);

	User selectByNameAndChannel(@Param("username") String username, @Param("channel") String channel);

	int updateServers(HashMap<String, String> map);

}